### ISSUE TITLE
Segmentation fault when saving image of size (0, 0)

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaImages/Images.jl#1018]
I recently found that `Images.save` can segfault if the image is of size (0,0) on Windows with `Images v0.25.2`. Here's what the error looks like:

```julia
julia> import Images

julia> img = Matrix{Images.RGB{Images.N0f8}}(zeros(0, 0))
0×0 Array{RGB{N0f8},2} with eltype ColorTypes.RGB{FixedPointNumbers.N0f8}

julia> Images.save("img.jpg", img)
[ Info: Precompiling JpegTurbo [b835a17e-a41a-41e7-81f0-2f016b05efe0]

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1f95e6379b0 -- unknown function (ip: 000001f95e6379b0)
in expression starting at REPL[3]:1
unknown function (ip: 000001f95e6379b0)
Allocations: 16708880 (Pool: 16697445; Big: 11435); GC: 14
```

Versioninfo:
```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_PKG_DEVDIR = dev/julia
```

Copy-paste-friendly mwe:

```julia
import Images
img = Matrix{Images.RGB{Images.N0f8}}(zeros(0, 0))
Images.save("img.jpg", img)
```

Maybe this should be moved into julia base, but I'm unfamiliar with how `Images.save` works.

**Comment by johnnychen94** [comment]
Not sure if it's possible to save empty data using jpeg turbo (my intuition is that JPEG format allows it), a quick patch is to check the size and throw an error eagerly in https://github.com/JuliaIO/JpegTurbo.jl/blob/33d53e772cb3c11c0f49082d6493b06bec6cbaea/src/encode.jl#L86-L87

**Comment by johnnychen94** [comment]
> Maybe this should be moved into julia base

Just a side note. Usually, the segfault is due to an incorrect C call and most of them are not Julia issues but library issues. People have to do extensive argument checks before calling the C routine.
