### ISSUE TITLE
Suggestion: rewrite docstrings for usage rather than reference

### ISSUE THREAD

**Issue by cormullion** [JuliaImages/Images.jl#1024]
When I want to lookup what the syntax is for a function, I find the REPL experience less than ideal sometimes. For example, I wanted to know what the syntax for padded arrays and borders was:

![imagespaddedarray](https://user-images.githubusercontent.com/52289/229585464-50239992-23b7-42ac-9ead-c01e380f0983.png)

(etc.)

Perhaps there's a little bit too much purple text for this text to be readable or helpful?

I think it would make sense to move these from the help to the manual.

**Comment by timholy** [comment]
Yes, or even `# Extended help`. See https://github.com/JuliaImages/ImageFiltering.jl/issues/153. I've had that open and tagged as "good first issue" for years, but even though we get thousands of downloads a month people don't seem so interested in stepping forward to help close it.

**Comment by cormullion** [comment]
I'd be happy to move that LATEX out of the docstring into the manual, where I think it should go. I'll make a PR and see how it goes.

**Comment by timholy** [comment]
Seems largely satisfied to me! Thanks again @cormullion for your heroism.
