### ISSUE TITLE
Bump version of ImageMagick.jl

### ISSUE THREAD

**Issue by jmanthony3** [JuliaImages/Images.jl#1061]
Citing this [issue](https://github.com/JuliaIO/ImageMagick.jl/issues/231) on the breaking of reading from an `IOBuffer()` with the release of Julia v1.11, it seems that the version of ImageMagick.jl used here needs to be bumped up to this new v1.4.0. I came across the cited issue in my workflow upon upgrading to Julia v1.11. I am using Images v0.26.1, and `] update` did not resolve said issue. However, after specifically adding the new version by `] add ImageMagick @1.4.0`, the issue was resolved.

**Comment by ViralBShah** [comment]
https://github.com/JuliaImages/Images.jl/pull/1063 should fix that. Help in fixing the failing tests in that PR would help get it in quick.

**Comment by ViralBShah** [comment]
#1064 is just the ImageMagick bump.

**Comment by ViralBShah** [comment]
Can you try out the Images master and see if things look good?

**Comment by jmanthony3** [comment]
Looks like everything works with `] dev https://github.com/JuliaImages/Images.jl.git` to add "Images@0.26.3" into my workflow. Thank you for working on this!
