### ISSUE TITLE
mac error noted at juliacon

### ISSUE THREAD

**Issue by alanedelman** [JuliaImages/Images.jl#120]
Just leaving a placeholder that on a mac , at least my mac,
it's a nuisance to use images

```
m = imread("IMG_0018.JPG")

error compiling imread: error compiling imread: could not load module : dlopen(.dylib, 1): image not found
while loading In[3], in expression starting on line 1
```

**Comment by juliohm** [comment]
@Evizero another one with `imread`, I appreciate if you can double check and close if possible.

**Comment by Evizero** [comment]
Its too old to still be relevant. If the current `load` causes problems, people will surely tell us
