### ISSUE TITLE
Keeping track of image geometry

### ISSUE THREAD

**Issue by kmsquire** [JuliaImages/Images.jl#124]
I've been implementing the kernel hough transform (http://www2.ic.uff.br/~laffernandes/projects/kht/), and have been finding it challenging to keep the coordinates straight in my code.  

Using `im["x", 100, "y", 200]` kind of works, but I'm not thrilled with it, and would prefer something more flexible.

What I'd like to do is write a thin `Axes` wrapper that takes into account the `Image` coordinate information and allows accessing the image in a consistent and useful manner for the task at hand--e.g., if I want to access an image like a matrix, I could create a set of axes that index by m[row, col] or m[row, col, color].  

But if I wanted Cartesian axes instead, I could put an origin at, e.g., the lower left, and have my image occupy the upper-right quadrant.  Or I could put the origin at the image center, flip, or scale it, as needed.  It should be easily extendable to image sequences as well.

Questions:
1. Is there functionality like this already that I missed?
2. What is/should be the overlap with other packages?  It would seem that Grid.jl might be useful here (and may already provide this functionality?).  Plotting systems already use axes, of course, but don't interact well with Images.jl.  PyPlot has this functionality, but also doesn't interact well with Images.jl

Thoughts?  If this doesn't exist already, would this be a useful addition to Images.jl?  Or should it be a separate package?

**Comment by timholy** [comment]
Closed by #577
