### ISSUE TITLE
None of the selected providers can install dependency libMagickWand

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#157]
> julia> Pkg.build("Images")
> INFO: Building Images
> ============================================================================[ ERROR: Images ]=============================================================================
> 
> None of the selected providers can install dependency libMagickWand.
> Use BinDeps.debug(package_name) to see available providers
> 
> while loading /home/julio/.julia/v0.3/Images/deps/build.jl, in expression starting on line 36
> # 
> 
> =============================================================================[ BUILD ERRORS ]=============================================================================
> 
> WARNING: Images had build errors.
> - packages with build errors remain installed in /home/julio/.julia/v0.3
>   - build a package and all its dependencies with `Pkg.build(pkg)`
>   - build a single package by running its `deps/build.jl` script
> # 
> 
> julia> BinDeps.debug("Images")
> INFO: Reading build script...
> The package declares 1 dependencies.
> - Library "libMagickWand"
>   - Satisfied by:
>     - System Paths at /usr/lib/libMagickWand-6.Q16HDRI.so
>   - Providers:
>     - AptGet package libmagickwand4 (can't provide)
>     - Yum package ImageMagick (can't provide)

`libMagickWand` is found on Arch, yet the build fails.

**Comment by ErikBjare** [comment]
Had a similar issue on Arch Linux (`failed to satisfy dependency libwand`), solved by installing `libmagick6` with pacman. Thanks for the hints! (and sorry for necroposting, hopefully it's of help to someone)
