### ISSUE TITLE
Building problem w7

### ISSUE THREAD

**Issue by dolejm1** [JuliaImages/Images.jl#216]
Actual version of Images doesn't compile on my windows 7.

Version 0.3.2+2 (2014-10-22 01:21 UTC)
release-0.3/6babc84\* (fork: 180 commits, 94 days)
x86_64-w64-mingw32

Here is what I'm doing, and resulting error:
julia> Pkg.build("Images")
INFO: Building Images
INFO: Installing ImageMagick library
INFO: Attempting to Create directory C:\Users\dolejm1.julia\v0.3\Images\deps\downloads
INFO: Directory C:\Users\dolejm1.julia\v0.3\Images\deps\downloads already created
INFO: Attempting to Create directory C:\Users\dolejm1.julia\v0.3\Images\deps\usr\lib\x64
INFO: Directory C:\Users\dolejm1.julia\v0.3\Images\deps\usr\lib\x64 already created
INFO: Attempting to Create directory C:\Users\dolejm1.julia\v0.3\Images\deps\downloads
INFO: Directory C:\Users\dolejm1.julia\v0.3\Images\deps\downloads already created
INFO: Downloading file http://www.imagemagick.org/download/binaries/ImageMagick-6.8.9-8-Q16-x64-dll.exe
INFO: Done downloading file http://www.imagemagick.org/download/binaries/ImageMagick-6.8.9-8-Q16-x64-dll.exe
INFO: Attempting to Create directory C:\Users\dolejm1.julia\v0.3\Images\deps\downloads
INFO: Directory C:\Users\dolejm1.julia\v0.3\Images\deps\downloads already created
INFO: Downloading file https://julialang.s3.amazonaws.com/bin/winnt/extras/innounp.exe
INFO: Done downloading file https://julialang.s3.amazonaws.com/bin/winnt/extras/innounp.exe
INFO: Changing Directory to C:\Users\dolejm1.julia\v0.3\Images\deps\downloads
The setup files are corrupted or made by incompatible version. Maybe it's not an
 Inno Setup installation at all.
(0047C56A)
===============================[ ERROR: Images ]================================

failed process: Process(`innounp.exe -q -y -b -e -x '-dC:\Users\dolejm1\.julia\v0.3\Images\deps\usr\lib\x64' ImageMagick-6.8.9-8-Q16-x64-dll.exe`, ProcessExited(1)) [1]
while loading C:\Users\dolejm1.julia\v0.3\Images\deps\build.jl, in expression starting on line 76
# 

================================[ BUILD ERRORS ]================================

WARNING: Images had build errors.
- packages with build errors remain installed in C:\Users\dolejm1.julia\v0.3
- build a package and all its dependencies with `Pkg.build(pkg)`
- build a single package by running its `deps/build.jl` script
#

**Comment by axsk** [comment]
Same issue again.

**Comment by timholy** [comment]
I've forgotten to tag a new release. It's the hazard of being the developer and the distributor: your own machine runs master and works fine, you forget that the rest of the world doesn't.

I think @rsrock noticed the need for a new version, too, and is tagging a new version tonight.

Going forward, the latest release should be more resistant to this problem (#249).

**Comment by rsrock** [comment]
New version tagged, you should be ready to go @axsk

**Comment by timholy** [comment]
Thanks, Ron!
