### ISSUE TITLE
Color space conversion with custom whitepoint definition

### ISSUE THREAD

**Issue by dolejm1** [JuliaImages/Images.jl#230]
Is it possible to convert XYZ Image to Lab Image (or other conversion which goes via XYZ) with custom white point? It is possible in Color module, but I can't find that option for Images.

**Comment by kvmanohar22** [comment]
@timholy  Is this feature implemented yet ?
If not I would like to implement this!

**Comment by timholy** [comment]
I haven't looked into it, but I suspect you could already do something like this:
```julia
src_white, ref_white = rand(RGB{Float64}), rand(RGB{Float64})
f = c->whitebalance(c, src_white, ref_white)
f.(img)
```
Does that cover your needs?

**Comment by kvmanohar22** [comment]
Yep, that seems to work !

**Comment by timholy** [comment]
Great. I'll close this then.
