### ISSUE TITLE
Move away from ImageMagick

### ISSUE THREAD

**Issue by timholy** [JuliaImages/Images.jl#24]
Relying on ImageMagick seems to be presenting problems for Mac users (see #15, #23), and also leads to slow performance. For at least PNG, JPG, and TIF it would be good to find an alternative, presumably by directly calling the corresponding libraries.

**Comment by ianshmean** [comment]
Given the JLL work recently, I thought, I'd see how far I could get with a `ImageIO.jl` package that bypasses ImageMagick, using libjpegturbo, libpng, libtiff directly. Research while working on it has uncovered a lot of the initial discussions around this, such as this issue, and https://github.com/JuliaImages/Images.jl/pull/41 

Currently I've wrapped each lib, and have functions from libpng and libtiff returning, but libjpegturbo is saying the functions are missing from the dylib. I saw that the branch was deleted in #41, does anyone know where/if I can track down that work?

Also, I don't know how much of an appetite there is for this kind of thing? I've always thought that ImageMagick is a bit slow, but that opinion is rather vague..

WIP: https://github.com/ianshmean/ImageIO.jl

**Comment by timholy** [comment]
It is potentially quite interesting! Benchmarks would obviously help make the case, as might increased API flexibility (e.g., loading just a rectangular block of an image).

The right place for such work to end up would indeed be an ImageIO package (or perhaps PNG.jl, JPEG.jl, and TIFF.jl packages) coupled with FileIO.

**Comment by ianshmean** [comment]
Some preliminary benchmarking..
The time to loaded image time seems better in this small-image PNG test case (via absorbed code from https://github.com/FugroRoames/LibPNG.jl):
```julia
@time using FileIO                      #0.311481 seconds (212.64 k allocations: 12.633 MiB)
@time img1 = load(testimg)              #5.867467 seconds (13.37 M allocations: 680.954 MiB, 6.01% gc time)
@btime img1 = load(testimg)             #487.182 μs (367 allocations: 21.88 KiB)

@time using ImageIO                     #1.287301 seconds (2.25 M allocations: 111.920 MiB, 1.60% gc time)
@time img2 = ModPNG.readimage(testimg)  #0.377399 seconds (1.14 M allocations: 57.108 MiB, 3.07% gc time)
@btime img2 = ModPNG.readimage(testimg) #26.236 μs (15 allocations: 992 bytes)
```

For LibTurboJpeg, I've only wrapped an encoder so far..
The smaller images are faster, larger are slower

|  | ImageIO.jl - libturbojpeg | FileIO - QuartzImageIO.jl | FileIO - ImageMagick.jl |
|-------------------------------|---------------------------------------|-----------------------------------------|-----------------------------------------|
| rand(RGB{N0f8}, 10, 20) | 101.484 μs (46 allocations: 2.81 KiB) | 534.594 μs (198 allocations: 12.84 KiB) | 460.599 μs (198 allocations: 12.84 KiB) |
| rand(RGB{N0f8}, 1000, 2000) | 92.338 ms (51 allocations: 5.72 MiB) | 89.069 ms (201 allocations: 22.90 MiB) | 90.524 ms (201 allocations: 22.90 MiB) |
| rand(RGB{N0f8}, 10000, 20000) | 14.329 s (51 allocations: 572.21 MiB) | 9.053 s (201 allocations: 2.24 GiB) | 9.378 s (201 allocations: 2.24 GiB) |

This should all be more structured, but getting an early idea of the benefit seemed worth it. Seems like it might be worth it for smaller images..

**Comment by ianshmean** [comment]
Also, @timholy your suggestion of skipping ImageIO and just pointing FileIO to JPEG.jl, TIFF.jl, PNG.jl is making more and more sense to me, given that we want to minimize both package loading time and image loading time, and people usually work in batches of same filetype images.

And just to cross-link, @tlnagy is working towards TIFF.jl, based on the basic TIFF handling elements of OMETIFF.jl https://github.com/tlnagy/OMETIFF.jl/issues/12#issuecomment-568213110

**Comment by norru** [comment]
Hi all, while you're collecting requirements, would it be possible to allow the backends which support it to write Float32 pixel data (such as TIFF) *directly* without a lossy conversion to UNorm? :)

**Comment by sdewaele** [comment]
Another motivation for having separate packages such as `PNG.jl` is open source licenses, especially when we include libraries in [relocatable apps](https://julialang.github.io/PackageCompiler.jl/dev/devdocs/relocatable_part_3/). Specifically, ImageMagick depends on `Zstd`  (ImageMagick -> ImageMagick_dll -> Libtiff_jll -> Zstd_jll -> Zstd), which has as a [BSD/GPLv2](https://github.com/facebook/zstd#license) license.

BTW, thanks a lot to @ianshmean  for putting together [this PR for LibPNG](https://github.com/ianshmean/LibPNG.jl/tree/jll) which should enable me to create a relocatable app with only LibPNG!

**Comment by ianshmean** [comment]
@sdewaele check out JuliaIO/PNGfiles.jl and JuliaIO/ImageIO.jl 

We’ve had it out in the wild for a month or so now and it seems to be going well

**Comment by sdewaele** [comment]
Thanks @ianshmean, this is even better. With `PNGFiles`, one has the option to only read/write PNG files, which is exactly what I was looking for. It works well.

Also, it is better to rely on a registered package as opposed to a PR...
