### ISSUE TITLE
Windows- or 32bit-specific `InexactError`

### ISSUE THREAD

**Issue by timholy** [JuliaImages/Images.jl#284]
Appveyor builds are failing:
https://ci.appveyor.com/project/timholy/images-jl/build/1.0.83/job/sgy1gmtq36rbsemh
https://ci.appveyor.com/project/timholy/images-jl/build/1.0.80/job/wv5yw4qxj0fvugqw
on the following command:

```
using FixedPointNumbers
aa = Ufixed12[0.6 0.2;
              1.4 0.8]
```

Can anyone on Windows test this? I don't understand what the problem could be.

**Comment by elsuizo** [comment]
In my 32-bits Debian laptop with Julia 0.3.7 works fine Tim

**Comment by timholy** [comment]
Thanks for the useful data point!

**Comment by timholy** [comment]
Ah, but it will probably only fail on 0.4---`trunc` didn't throw errors on 0.3.

**Comment by tkelman** [comment]
`Ufixed12[0.6 0.2; 1.4 0.8]` in isolation doesn't error for me on win32, 0.4, but it does give different answers every time I run it.

`Pkg.test("Images")` fails for me on win32, 0.4, with the same error you're seeing on appveyor.

**Comment by timholy** [comment]
That's alarming. Sounds like some kind of memory error?

I'm going to file this at FixedPointNumbers and CC some folks who know more. Just to double-check, this works for you on Linux, right? (You have Linux available, right?)

**Comment by timholy** [comment]
Sorry to pester you more, but can you also test things like:
```jl
Ufixed(0.2)
Ufixed(1.4)
Ufixed([0.2,1.4])
```
and let me know what happens?

**Comment by tkelman** [comment]
> Just to double-check, this works for you on Linux, right? (You have Linux available, right?)

Yes and yes.

> Ufixed(0.2)
> Ufixed(1.4)
> Ufixed([0.2,1.4])

```MethodError: `rawtype` has no method matching rawtype(::Type{FixedPointNumbers.Ufixed})` ```

With `Ufixed12(0.2)` things appear to work. Worth noting that for the array `Ufixed12[0.6 0.2; 1.4 0.8]` it looks like the first row is always zeros, the second row has different values every time.

**Comment by timholy** [comment]
Sorry for initially omitting the 12, and thanks for catching it.

**Comment by timholy** [comment]
I think I'm going to file this in julia proper, since I don't think this can be limited to FixedPointNumbers.

**Comment by tkelman** [comment]
Some more info: it's a 32 bit issue, but with different symptoms between Linux vs Windows:
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4524 (2015-04-27 00:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 982c60a* (0 days old master)
|__/                   |  i686-linux-gnu

julia> using FixedPointNumbers

julia> Ufixed12[0.6 0.2; 1.4 0.8]
ERROR: InexactError()
 in trunc at float.jl:341
 in hvcat_fill at abstractarray.jl:824
 in typed_hvcat at abstractarray.jl:843
```

**Comment by timholy** [comment]
That makes more sense than it being OS-specific!

**Comment by timholy** [comment]
Ah, above I see that it might have worked on 0.3.7. You don't happen to have a 32bit (either Windows or Linux) to test on with 0.3, do you?

**Comment by tkelman** [comment]
Looks like the bug is not present on 0.3.8-pre on win32.

**Comment by timholy** [comment]
Thanks, that's useful to confirm.

**Comment by johnnychen94** [comment]
Since this issue is five years old and the current CI passes, I'm closing it now.
