### ISSUE TITLE
imwrite() fails for Float64 array

### ISSUE THREAD

**Issue by waldyrious** [JuliaImages/Images.jl#30]
imwrite() fails if I try to write an image based on a Float64 array:

```
julia> using Images

julia> a=[2.1659 2.08545; 2.19507 2.16046]
2x2 Array{Float64,2}:
 2.1659   2.08545
 2.19507  2.16046

julia> img=convert(Image,a)
Gray Image with:
  data: 2x2 Array{Float64,2}
  properties:
    limits: (0.0,1.0)
    colordim: 0
    spatialorder:  y x
    colorspace: Gray

julia> imwrite(img,"2by2.png")
ERROR: key not found: 64
 in getindex at dict.jl:504
 in imwrite at /home/waldir/.julia/Images/src/io.jl:290
 in imwrite at /home/waldir/.julia/Images/src/io.jl:144
```

**Comment by RobBlackwell** [comment]
Just updating the thread to see if there is now a way to save floating point format TIFF files please?

```
using FileIO
x = Matrix{Float64}(100,100) .= 10.2
save("foo.tiff",x)
```
Fails with
```
ArgumentError: FixedPointNumbers.Normed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent 10.2
```
OMETIFF.jl only seems to support reading.

I guess I'm looking for something like https://stackoverflow.com/questions/5414586/how-do-i-save-a-mode-f-image-python-pil for Julia

**Comment by bjarthur** [comment]
the elements of your matrix need to be a [Colorant](https://github.com/JuliaGraphics/ColorTypes.jl).  try `save("foo.tiff", rand(Gray{Float64},5,5))`

**Comment by RobBlackwell** [comment]
Thanks but the TIFF spec appears to support storing actual floating point numbers  (so called mode "f") and if I understand correctly, the above is converting to Normed UInt8 before it hits the file. When reloaded, it's a
```
5x5 Array{Gray{N0f8},2}
```
so precision is lost?

I'd like to be able to store tiffs with full floating point for fidelity and compatibility with other apps. It appears to be possible in Python via PIL, but how can I do it in Julia I wonder?

**Comment by timholy** [comment]
It does, but AFAICT [there is no way to coerce ImageMagick](https://www.imagemagick.org/api/magick-image.php) into saving it with floating-point precision. If anyone knows to the contrary, would love to hear about it.

**Comment by bjarthur** [comment]
Gray{N0f16} works to save and re-load.  perhaps a good enough step in the right direction for you?  strangely, Gray{N0f32} does not.

if you're on a mac, you might try [QuartzImage.jl](https://github.com/JuliaIO/QuartzImageIO.jl) instead if ImageMagick.

**Comment by RobBlackwell** [comment]
Thank you!

I've found the following workaround for now:

```
using PyCall
@pyimport skimage.io as skimageio
skimageio.imsave("foo.tiff", A)
A = skimageio.imread("foo.tiff")
```

This seems to work for Float32 and Float64 arrays.

The underlying library appears to be tifffile, https://www.lfd.uci.edu/~gohlke/code/tifffile.c.html
 which I might be able to wrap directly at some later point.

**Comment by norru** [comment]
Hello, just had this problem myself. Has any progress been made?

**Comment by timholy** [comment]
In the long run we need to support something more capable than ImageMagick. Efforts underway:
- https://github.com/ianshmean/ImageIO.jl
- https://github.com/c42f/OpenImageIO.jl

Most things in open-source happen by someone deciding to take the plunge, and the most vigorous maintainers are busy with other tasks. Care to join one of these efforts?

**Comment by norru** [comment]
I know of other successful software who have adopted OIIO. Unfortunately I have no capacity right now, but I'll take note.
