### ISSUE TITLE
OSX: convert error when reading png file

### ISSUE THREAD

**Issue by kmsquire** [JuliaImages/Images.jl#302]
Should probably be a simple fix, but I don't have time to look at it right now.

(This came up while testing `VideoIO.jl`)

``` julia
julia> imread("/Users/kevin/.julia/v0.4/VideoIO/test/annie_oakley.png")
ERROR: MethodError: `convert` has no method matching convert(::Type{Ptr{UInt8}}, ::Array{UInt8,1})
This may have arisen from a call to the constructor Ptr{UInt8}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Ptr{T}}, ::UInt64)
  convert{T}(::Type{Ptr{T}}, ::Int64)
  ...
 in CFStringGetCString at /Users/kevin/.julia/v0.4/Images/src/ioformats/OSXnative.jl:327
 in read_and_release_imgsrc at /Users/kevin/.julia/v0.4/Images/src/ioformats/OSXnative.jl:50
 in imread at /Users/kevin/.julia/v0.4/Images/src/io.jl:128
```

**Comment by rsrock** [comment]
To be honest, I haven't done any testing of the native OS X reader on 0.4 yet. I know that there have been major changes to the ccall interface that are probably triggering this.  I've stayed on 0.3 while the dust settles (seems like it's settling rapidly now, and all the new goodies are so, so tempting)

Real-world duties are blocking for a couple of months here, but my plan is to rework all of this using objectivec.jl over the summer.  Hope to include image saving as well.

If this is blocking, you can always comment out this path and fall back to imagemagick.

**Comment by kmsquire** [comment]
Ok, thanks for the hint on commenting.

**Comment by rsrock** [comment]
Note to self-- this is probably https://github.com/JuliaLang/julia/issues/10994

**Comment by Evizero** [comment]
Just tried your VideoIO test image on OSX in 0.6 with QuartzImageIO and it works.

I'll go ahead and consider this fixed. Please let me know if that is not the case
