### ISSUE TITLE
Possible block reads?

### ISSUE THREAD

**Issue by jgbos** [JuliaImages/Images.jl#355]
Is it possible to read in blocks of images without reading in the entire image?  I am looking at options to analyse images that are many TBs in size.  Apologies if the functionality is there and I missed it.

**Comment by timholy** [comment]
If your image is in NRRD format, it uses `mmap` to "read" the data. Consequently, you can work with your image as if it's in memory, but really it reads the disk only for the pixels you're "working on" at the moment. This passes through transparently to ImageView. I routinely use this to analyze/visualize multi-TB images.

If your images are in a different format, then we can talk about what might need to change.

**Comment by jgbos** [comment]
Oh great, I was given samples of data in 3D TIF format, I will check what the raw format is.  I think it might be VTK but won't know until I'm back at work tomorrow.  Will that be a similar read as NRRD?

**Comment by timholy** [comment]
NRRD is basically a binary dump. 3D TIF will probably have headers between the frames? if so this will take a little more effort.

You could write out as NRRD if you prefer. Format specification is here:
http://teem.sourceforge.net/nrrd/format.html
(Despite the length of the page, you may only need a few fields, in which case this should be pretty simple.)

**Comment by jgbos** [comment]
OK, I was completely wrong on the file format, swear I saw VTK somewhere.  But the actual format is [LIF](https://www.openmicroscopy.org/site/support/bio-formats5.1/formats/leica-lif.html).  So I will have to do some digging around, looks like this might be similar to NRRD (i.e., binary format).  The TIFF files I have are slices in a dimension with no headers, each file is actually just a regular TIFF, I just concat on the third dimension when reading them in.  Not optimal, will have to figure out the LIF file.

**Comment by Evizero** [comment]
closing as non-actionable
