### ISSUE TITLE
grayim asymmetrie with IO

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaImages/Images.jl#368]
Should grayim always return `Array{Gray{T}}` ?
`imread` always returns this for any grayscale image and I think these two should match, shouldn't they?

Best,
Simon

**Comment by timholy** [comment]
Seems reasonable to me.

**Comment by timholy** [comment]
Gray was a johnny-come-lately to the Colors world.

**Comment by SimonDanisch** [comment]
Allright...this is already fixed on sd/fileio...
I think only `SIF.jl` and `Imagine.jl` are missing for a merge.
We could just leave them in Images.jl and just change the method signature?!

**Comment by timholy** [comment]
Maybe I'm not understanding correctly, but why is `grayim` even defined in `fileio`?

**Comment by SimonDanisch** [comment]
oh I meant in my Image branch ;)

**Comment by timholy** [comment]
Closed by #577
