### ISSUE TITLE
uint8sc deprecation incorrect?

### ISSUE THREAD

**Issue by DrTodd13** [JuliaImages/Images.jl#375]
@deprecate uint8sc      ufixed8sc

Should this be FixedPointNumbers.ufixed8 instead of ufixed8sc?

**Comment by lkuper** [comment]
@timholy @DrTodd13 The deprecation warning that Images.jl gives for `uint8sc` is a bit misleading.  It should say `Images.ufixed8sc`, not just `ufixed8sc`.  It looks like `Images.ufixed8sc` is defined in https://github.com/timholy/Images.jl/blob/master/src/map.jl .

**Comment by timholy** [comment]
Closed by #577
