### ISSUE TITLE
Reading jpgs from memory/Reading many small images

### ISSUE THREAD

**Issue by vollmersj** [JuliaImages/Images.jl#377]
Reading many small images from disk is slow - 1000 very small images takes around 30s. My questions are the following:
1. Is there way to use `imread` with say Byte arrays. 
2. the byte arrays could be stored in a HDF5 so that reading this file is much faster (and easier to keep in cache).

**Comment by lucasb-eyer** [comment]
1: Yes, see #365. We probably should document that.

**Comment by tlienart** [comment]
am I wrong to thing that the solution in #365 is outdated? Looking at the current version of `Images.jl` there is the:

```
import FileIO: load, save
@deprecate imread(filename; kwargs...) load(filename; kwargs...)
```

is there a way to bypass "load" and just do the conversion from byte array to RGB ?
the interest, as for OP, is to pre-process a very large number of images as a bunch of pre-processed chunks stored in HDF5 files.

thanks

**Comment by timholy** [comment]
Yes, this is in the process of switching to a new interface. (What's on master has not been tagged yet, however.) The code in #365 is now available in [ImageMagick.jl](https://github.com/JuliaIO/ImageMagick.jl).

**Comment by timholy** [comment]
Often in cases of performance issues, I'd recommend starting with the profiler to try to figure out the source of the slowness.

But either of your solutions sounds viable.

**Comment by Evizero** [comment]
closing as long outdated.
