### ISSUE TITLE
boundary identification

### ISSUE THREAD

**Issue by wadehenning** [JuliaImages/Images.jl#430]
Tim,

Once I have used something like `imedge` to detect the edges in an image (for example, the contours in a set of separated coffee beans) is there a function that will return the individual contours as a cell array or other object?   Similar to Matlab `bwboundaries`?  Or can you suggest another approach to identifying these types of boundaries?

Thank You,
Wade

**Comment by meaningofshape** [comment]
I did not receive a reply for this question and it is still important.  Is there a function that returns individual boundaries in an image?  Clearly, I can write my own code for this...
Thank you.

**Comment by timholy** [comment]
Sorry there was no response. I don't know of anything that returns the boundaries, but you can use `label_components` to find the connected regions. I would guess that may be more useful information than the boundaries?

**Comment by timholy** [comment]
You can just say `?Images` (after `using Images`) to get an API summary.

**Comment by meaningofshape** [comment]
Thank you.  We are often interested in studying the shapes of the objects that are identified in the images, where shape is defined by an object's boundary function.  We didn't want to write code for this if it was already implemented by someone with more experience writing nice Julia, but we are now trying to cut the Matlab cord!

**Comment by timholy** [comment]
Then I don't think there's anything existing; you will likely need to strike out on your own. If you come up with something nice, consider sharing!

**Comment by meaningofshape** [comment]
When we have something generally useful, we will be happy to share it with the community.

**Comment by pmargreff** [comment]
Hi, I'm doing some similar and using the function `canny_edges` to get the boundary, you can try that too.

**Comment by wadehenning** [comment]
@pmargreff how do you get the individual boundaries from the returned binary matrix? I have implemented an approach but I should improve the code.  Thanks!
