### ISSUE TITLE
Doc links broken

### ISSUE THREAD

**Issue by timholy** [JuliaImages/Images.jl#471]
At the bottom of the README, there are links to `core`, `function reference` and `Overlays`. These work on GitHub (though the markup shows in, e.g., `function reference`), but not on [github.io](http://timholy.github.io/Images.jl/home/). Should we make them all links to the io page?

**Comment by timholy** [comment]
Oh, also the images seem to be broken for me on github.io. That seems more serious. If you know how to fix it quickly, @rsrock, be my guest :smile:, otherwise I will learn how this works. Seems like https://github.com/MichaelHatherly/Documenter.jl is the new upcoming standard? (See deprecation notice at https://github.com/MichaelHatherly/Docile.jl.)

**Comment by rsrock** [comment]
No problem, I'll take care of it (probably on the weekend).  It looked to me like Documenter has the ability to let Travis update the docs for us, so we man not need any manual intervention in the future.  I'm looking forward to that!

**Comment by timholy** [comment]
Closed by #577
