### ISSUE TITLE
Some functions not working for all image types?

### ISSUE THREAD

**Issue by cormullion** [JuliaImages/Images.jl#540]
Some functions in Images.jl don't appear to work on all images. Perhaps there could be additional information about what sort of images are accepted by these functions:

```
julia> using Images, TestImages

julia> img = testimage("mandrill")
RGB Images.Image with:
  data: 512×512 Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> sc(img)
ERROR: MethodError: Cannot `convert` an object of type ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}} to an object of type FixedPointNumbers.UFixed{UInt8,8}
This may have arisen from a call to the constructor FixedPointNumbers.UFixed{UInt8,8}(...),
since type constructors fall back to convert methods.
 in _map_a!(::Images.ScaleMinMax{FixedPointNumbers.UFixed{UInt8,8},FixedPointNumbers.UFixed{UInt8,8},Float32}, ::Images.Image{FixedPointNumbers.UFixed{UInt8,8},2,Array{FixedPointNumbers.UFixed{UInt8,8},2}}, ::Images.Image{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}}) at /Users/me/.julia/v0.5/Images/src/map.jl:492
 in sc(::Images.Image{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}}) at /Users/me/.julia/v0.5/Images/src/map.jl:686

julia> findlocalmaxima(img)
ERROR: MethodError: no method matching isless(::ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}}, ::ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}})
 in macro expansion at /Users/me/.julia/v0.5/Images/src/algorithms.jl:1073 [inlined]
 in macro expansion at ./cartesian.jl:64 [inlined]
 in macro expansion at /Users/me/.julia/v0.5/Images/src/algorithms.jl:1071 [inlined]
 in macro expansion at ./cartesian.jl:64 [inlined]
 in macro expansion at /Users/me/.julia/v0.5/Images/src/algorithms.jl:1068 [inlined]
 in findlocalextrema(::Images.Image{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}}, ::Array{Int64,1}, ::Bool, ::Base.Order.ForwardOrdering) at /Users/me/.julia/v0.5/Images/src/algorithms.jl:1065
 in findlocalmaxima(::Images.Image{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}}) at /Users/me/.julia/v0.5/Images/src/algorithms.jl:1092

julia> imstretch(img, 1, 2)
ERROR: MethodError: Cannot `convert` an object of type ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}} to an object of type AbstractFloat
This may have arisen from a call to the constructor AbstractFloat(...),
since type constructors fall back to convert methods.
 in imstretch(::Images.Image{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}}, ::Int64, ::Int64) at /Users/me/.julia/v0.5/Images/src/exposure.jl:21
```

I've not yet tried them all.

I'm assuming that these functions aren't able to accept every type of img, but the error messages could perhaps be more specific?

julia> versioninfo()
Julia Version 0.5.0-rc0+0
Commit 0030eec\* (2016-07-26 20:22 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)

**Comment by timholy** [comment]
Agreed this is an issue, and that if nothing else a better error message would be helpful.

There is a common theme to these failures: these are functions that clearly make sense for grayscale images, but not always for RGB images. What exactly is a "local maximum" for an RGB image? (There is no ordering on RGB.)

**Comment by Evizero** [comment]
> There is no ordering on RGB

I wish the people designing the ANSI RGB colour codes shared your opinion

**Comment by bjarthur** [comment]
@evizero could you enlighten us with a link to the ANSI standard which explains whether `RGB(1,0,0)` is greater or less than `RGB(0,1,0)`?

**Comment by cormullion** [comment]
I was looking for a binaries/threshold/posterior function, so I tried some functions that perhaps I shouldn't have. Those Julia type signatures in the error messages are not very user-friendly. (Although I get that Images.jl isn't for the less experienced user.)

**Comment by mronian** [comment]
@cormullion Thanks for bringing this up...it will help novice users if we handle such errors in the new JuliaImages with a useful message.

**Comment by timholy** [comment]
Images *will* be for newbies someday, but it's not there yet.

**Comment by Evizero** [comment]
Looking at the error messages and docstrings today, I think that at least for the mentioned functions (that still exists) it should be clear enough what is happening.

I'll close this for now. Let us revisit this issue if some new users bring something like this up here or on discourse/slack.

**Comment by ashwani-rathee** [comment]
@johnnychen94  Can we reopen this?This issue is bugging me now,especially with convex_hull,imfill,clear_border tests

**Comment by johnnychen94** [comment]
The original issue is pretty old and Images internal has changed a lot since that. You could open a new one describing the problem you meet.
