### ISSUE TITLE
Images undisplayable in IJulia should fall back to `show`

### ISSUE THREAD

**Issue by timholy** [JuliaImages/Images.jl#554]
Errors during image display often confuse IJulia users, leading them to think that an operation has failed (rather than simply reflecting a display error). This needs to be fixed, most likely by displaying the text-result (`show`).

Ref https://groups.google.com/d/msg/julia-users/P40mahYKGyM/fgwo8yNFAAAJ

**Comment by stevengj** [comment]
You should implement a `mimewritable` method if an Image may or may not be able to display as a given mimetype.

**Comment by Evizero** [comment]
This seems fixed with the removal of the dedicated `Image` type. At least the issue discussed on the mailing list. I'll go ahead and close this
