### ISSUE TITLE
trying to view images on 0.6

### ISSUE THREAD

**Issue by sononix** [JuliaImages/Images.jl#568]
julia> using Images, Colors, FixedPointNumbers, ImageView

julia> using TestImages

julia> img = testimage("mandrill")
INFO: Recompiling stale cache file /var/root/.julia/lib/v0.6/QuartzImageIO.ji for module QuartzImageIO.
RGB Images.Image with:
  data: 512×512 Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: RGB
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> view(img)
ERROR: BoundsError: attempt to access ()
  at index [0]
 in rdims at ./reshapedarray.jl:52 [inlined]
 in reshape(::Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}, ::Type{Val{0}}) at ./reshapedarray.jl:45
 in view(::Images.Image{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}}) at /var/root/.julia/v0.6/Images/src/core.jl:513

version 

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.1133 (2016-10-27 03:53 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit 97ca164\* (0 days old master)
|__/                   |  x86_64-apple-darwin16.0.0

and installed Cairo using 
brew uninstall -f cairo, Pkg.add("Cairo"), brew install cairo

**Comment by timholy** [comment]
Use `ImageView.view`. julia-0.5 created a new meaning for `view`.

**Comment by fpreiswerk** [comment]
I get the same error on 0.5.0 when using `ImageView.view`.

**Comment by timholy** [comment]
Sorry for the delay.

```jl
julia> using ImageView, TestImages

julia> img = testimage("mandrill");

julia> ImageView.view(img)
WARNING: view is deprecated, use imshow instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in view(::Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}, ::Vararg{Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2},N}) at ./deprecated.jl:30
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
while loading no file, in expression starting on line 0
(ImageCanvas,ImageSlice2d: zoom = Graphics.BoundingBox(0.0,512.0,0.0,512.0))

julia> versioninfo()
Julia Version 0.5.1-pre+31
Commit 6a1e339* (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
I think that should work for you too. I am using https://github.com/timholy/Images.jl/issues/542#issuecomment-254059092, though.

**Comment by timholy** [comment]
It's now `imshow`.
