### ISSUE TITLE
Docs: minor formatting issue

### ISSUE THREAD

**Issue by cormullion** [JuliaImages/Images.jl#586]
I'm enjoying the new documentation for Images (and the new code!) and noticed this:

![screen shot 2017-02-07 at 09 26 31](https://cloud.githubusercontent.com/assets/52289/22685308/bee1d3ee-ed17-11e6-89cf-da402785e617.png)

Would these be better if they weren't indented in Markdown, so as not to be code blocks?

**Comment by timholy** [comment]
I'll fix this and also add docs for the new `feature_transform`/`distance_transform` functions (https://github.com/JuliaImages/Images.jl/pull/580).
