### ISSUE TITLE
Updating an existing Image in a Jupyter notebook

### ISSUE THREAD

**Issue by izaid** [JuliaImages/Images.jl#591]
So I'm trying to display streaming video from a device in the Jupyter notebook. The Images.jl `display` function is what I use to display each frame, i.e. `display(colorview(Gray, rand(200, 200))`. The streaming is happening asynchronously, and I show only one frame at a time using `IJulia.clear_output(true)`.

While this gives an animation, and it doesn't lock the notebook, if I run a computation in another cell the output will be the asynchronous display and not whatever was in the new cell. I think I could work around this if I had something to update.

Question: Is there a way I can update a displayed image in an Jupyter notebook?

**Comment by izaid** [comment]
Here is a very simple example of what I mean.

```
In[1]: import Images

In[2]: @async begin
    while true
        image = rand(200, 200)
        
        IJulia.clear_output(true)
        display(Images.colorview(Images.Gray, image))
    end
end

In[3]: 2 + 2
```

**Comment by SimonDanisch** [comment]
Try using Interact with signals.

e.g.:
```Julia
using Interact, Images, Colors
map(Reactive.every(0.5)) do t
    rand(RGB{N0f8}, 300, 300)
end
```

**Comment by Evizero** [comment]
Can confirm, simons solution still works. Note that you don't have to create that image inside the `map` function, so your use-case of changing the content in a different cell also works.

**Comment by izaid** [comment]
I tried @SimonDanisch solution as well, it worked great. Thanks!
