### ISSUE TITLE
Conversion from one colorspace to another colorspace

### ISSUE THREAD

**Issue by kvmanohar22** [JuliaImages/Images.jl#592]
We don't seem to have conversion from one colorspace (say `RGB`) to other colorspaces (eg. `gray`, `hed`, `hsv`, `lab`, `xyz`, etc). Maybe we can have `src/conversions.jl` which handles all these conversions ? Any suggestions ?

**Comment by bjarthur** [comment]
see https://github.com/JuliaGraphics/Colors.jl/blob/master/src/conversions.jl

**Comment by timholy** [comment]
Try `HSV.(img)`.
