### ISSUE TITLE
Build failure in Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#593]
Can you please confirm this error is coming from Images.jl?

https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/201223318#L1267

**Comment by timholy** [comment]
Yes it is. I have a branch locally that fixes that, but it's still far from getting through all the tests. Current pain point is https://github.com/JuliaArrays/StaticArrays.jl/issues/109.

**Comment by juliohm** [comment]
I am closing this one since I know there is a lot of work happening towards getting Images.jl on Julia v0.6.
