### ISSUE TITLE
No implementation of Hough Line Transform

### ISSUE THREAD

**Issue by annimesh2809** [JuliaImages/Images.jl#600]
I did not find any implementation of hough line transform in julia images. Can I add an implementation of hough line transform similar to that of matlab to julia?

**Comment by timholy** [comment]
That would be great. The one thing you need to be careful of is the license. This package (and all the packages in JuliaImages) are MIT licensed; if you even *read* code that has a restrictive license, you're not allowed to reimplement it using a permissive license. So make sure you check the license status of any code before you start looking at it.

**Comment by annimesh2809** [comment]
Okay thanks, I will be careful about it.

**Comment by mronian** [comment]
@annimesh2809 There is an OpenCV implementation as well. You could use that as a starting point 😄 It would be great to have [other hough transforms](https://en.wikipedia.org/wiki/Hough_transform) (circles etc) as well in ImageFeatures.jl.

**Comment by timholy** [comment]
Closed by https://github.com/JuliaImages/ImageFeatures.jl/pull/28.
