### ISSUE TITLE
How to convert to base64 encoded string to Image Object ?

### ISSUE THREAD

**Issue by vyas315** [JuliaImages/Images.jl#610]

**Comment by timholy** [comment]
It isn't possible to tell from that information alone. Did you try `img = base64decode(str)`? Another option might be that it's a base64-encoded PNG, in which case using `using FileIO; load(Stream(format"PNG", stream))` might work.

**Comment by vyas315** [comment]
I have the string of the following format 
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAAJnCAYAA....."
I tried img = base64decode(str), which returned a 1-D array, 

Is there a way to get Image object from this string (which is base64 encode of a canvas object in javascript) ??

**Comment by timholy** [comment]
Since that's `image/png;base64`, try the `Stream` version I showed you above.

**Comment by timholy** [comment]
Or even better, maybe `readblob` from ImageMagick. Demo:
```julia
julia> str = readstring("lighthouse.png");

julia> using ImageMagick

julia> img = readblob(str.data)
```

**Comment by vyas315** [comment]
@timholy  Thanks a lot, readblob() worked !!

**Comment by timholy** [comment]
Great, glad to hear it.

**Comment by Losses** [comment]
@timholy `format"PNG"` seems not working anymore, what should we use in 2019?

**Comment by timholy** [comment]
Should work. Can you provide an example I can copy/paste?
