### ISSUE TITLE
How does one create a matrix of images?

### ISSUE THREAD

**Issue by shashi** [JuliaImages/Images.jl#612]
This probably has a simple answer :)
```julia
x() = colorview(Gray, rand([0.250 0.5; 0.75 1.0], rand(2:1000), rand(2:1000)))
```

```julia
julia> [x() x(); x() x()]
ArgumentError: mismatched height in block row 1 (expected 378, got 35)

 in typed_hvcat(::Type{ColorTypes.Gray{Float64}}, ::Tuple{Int64,Int64}, ::Array{ColorTypes.Gray{Float64},2}, ::Vararg{Array{ColorTypes.Gray{Float64},2},N}) at ./abstractarray.jl:1282
 in hvcat(::Tuple{Int64,Int64}, ::Array{ColorTypes.Gray{Float64},2}, ::Vararg{Array{ColorTypes.Gray{Float64},2},N}) at ./array.jl:729

```

tries to concatenate the arrays of colors!
Same with

```julia
julia> typeof(x())[x() x(); x() x()]
MethodError: Cannot `convert` an object of type ColorTypes.Gray{Float64} to an object of type Array{ColorTypes.Gray{Float64},2}
This may have arisen from a call to the constructor Array{ColorTypes.Gray{Float64},2}(...),
since type constructors fall back to convert methods.
```

cc @dpsanders

**Comment by bjarthur** [comment]
`x()` returns a matrix of a different size each time because of the last two `rand` in the method definition.  to concatenate arrays one of the dimensions must be the same length.  or am i missing something?

**Comment by shashi** [comment]
So I want to create a matrix of matrices and not concatenate them into one big matrix...

**Comment by bjarthur** [comment]
you could `push!` onto an empty array and then `reshape` it.

**Comment by bjarthur** [comment]
or, you could `m=Array(Matrix,2,2)` and then `m[1]=...` etc

**Comment by shashi** [comment]
Thanks, those methods are not very satisfying though. It feels like there should be a natural way.

Anyway probably more a Julia syntax question than one for this package :)

**Comment by timholy** [comment]
Does `M = [x() for i = 1:2, j = 1:2]` do what you want?

**Comment by shashi** [comment]
Yes it does, I was looking for a literal syntax which would even work for image objects...

Yu Yichao suggested `[[a] [b]; [c] [d]]` which is quite nice!
