### ISSUE TITLE
Issue saving ImageAxes images

### ISSUE THREAD

**Issue by rsrock** [JuliaImages/Images.jl#618]
This is a FileIO issue, but as you'll see, I'm guessing that the relevant code sits in ImageMagick and QuartzImageIO.  I first ran into this on Julia 0.6, but it happens here on 0.5, so something changed in the last couple of months.

```
julia> using Images, TestImages

julia>         name = "mri-stack"
"mri-stack"

julia>         img = testimage(name)
3-dimensional AxisArray{Gray{N0f8},3,...} with axes:
    :P, 0:1:225
    :R, 0:1:185
    :S, 0:5:130
And data, a 226×186×27 Array{Gray{N0f8},3}:
[:, :, 1] =
 Gray{N0f8}(0.0)  Gray{N0f8}(0.0)  Gray{N0f8}(0.0)  Gray{N0f8}(0.0)  Gray{N0f8}(0.0)  …  

```

That's something new.  How did FileIO figure out that this file has three axes with those names?

```
julia> mydir = tempdir() * "/QuartzImages"
"/var/folders/2d/ls4zcgc523q37zzjppm8k9gw0000gn/T/QuartzImages"

julia>         out_name = joinpath(mydir, name * ".png")
"/var/folders/2d/ls4zcgc523q37zzjppm8k9gw0000gn/T/QuartzImages/mri-stack.png"

julia>         save(out_name, img)
Errors encountered while saving "/var/folders/2d/ls4zcgc523q37zzjppm8k9gw0000gn/T/QuartzImages/mri-stack.png".
All errors:
   MethodError(QuartzImageIO.to_explicit,(
ColorTypes.Gray{FixedPointNumbers.Normed{UInt8,8}}[Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0) Gray{N0f8}(0.0)...
```

Julia's final complaint (which I've snipped here) is something like: no method `to_explicit` for an `AxisArray` type.  So I guess I'm asking, how should I pop out the `AxisArray` into a good old `Array`? 😄 

I can't currently test against ImageMagick, because my Julia ImageMagick has decided not to read TIFFs today.

**Comment by timholy** [comment]
As for how it gets the AxisArray wrapper, [this might help explain](https://github.com/JuliaImages/TestImages.jl/blob/1ad8d4f7694b358e83c9f80850c654033672310b/src/TestImages.jl#L78-L82). (And yes, that's relatively new.)

I'm not sure about the second error. ImageMagick recently added https://github.com/JuliaIO/ImageMagick.jl/pull/83, maybe QuartzImageIO needs to follow suit? But I'm also noting a (spurious) ambiguity with `map` on AxisArrays (will fix), it's possible you'll encounter other problems. You could try `save(fn, img.data)` if you just want to strip the axes.

**Comment by rsrock** [comment]
Ah, that explains why my mri-stack test no longer works! I'm slowly getting used to this package "reading my mind", but this one went a bit over the top. "There's no metadata in this image, where's it finding those axis names?!"

`img.data` should do it for me.  Thanks.

My ImageMagick problem is probably related to a Homebrew issue.  I will investigate later.

**Comment by Evizero** [comment]
A quick side note, since I just tried it. I would have assumed based on my intuition of `parent` that `parent(img)` would return `img.data` for an axis array, which it doesn't.

**Comment by timholy** [comment]
I noticed that too. I think we should add that to AxisArrays.
