### ISSUE TITLE
Images in IJulia are displayed as millions of <rect> elements

### ISSUE THREAD

**Issue by rdeits** [JuliaImages/Images.jl#619]
This seems to have come up in a recent version of Images.jl, although I haven't tracked it down yet. It also only appears to happen on Linux, not on mac OS (perhaps it's really an ImageMagick issue?). Anyway, to reproduce, just run this in an IJulia notebook:

```julia
using TestImages
testimage("mandrill")
```

this will cause the browser to slow to a crawl as it tries to render 262,144 individual `<rect>` elements instead of an `<img>`. 

I will keep investigating.

**Comment by Evizero** [comment]
Does it happen when you do `using TestImages, Images` instead?

I am guessing this is because the efficient display logic isn't loaded by default

**Comment by Evizero** [comment]
This would also explain the discrepancy between `ImageMagick` and `QuartzImageIO`, since the former only loads `ImageCore`, while the later loads `Images`

**Comment by rdeits** [comment]
Aha, that does fix it, thanks! 

Presumably this is because QuartzImageIO requires Images.jl, but ImageMagick only requires ImageCore (which doesn't have the mime overloads).

**Comment by rdeits** [comment]
Er, yes, that :smile:

**Comment by rdeits** [comment]
Do you think this is something we should fix? It seems like one could either:

1. modify ImageMagick.jl to load Images instead of ImageCore
2. move the display code from Images to ImageCore

but I don't know enough about the Images ecosystem to evaluate which is preferable.

**Comment by timholy** [comment]
Nice diagnosis!

Yes, I think this should be fixed. I favor moving the display code to ImageCore. Are you up for tackling that?

**Comment by Evizero** [comment]
> I favor moving the display code to ImageCore.

Doesn't the display code use `restrict` or is there a workaround you are thinking about?

**Comment by timholy** [comment]
I had forgotten all about that (I should have looked at the code).

Dang, if we want to keep dependency chains "light" there doesn't seem to be a great solution. Most straightforward would be to have TestImages or ImageMagick load at least ImageTransformations. Another option would be to put an `eval(:(using ImageTransformations))` inside the branch of the display code that calls `restrict`. It eliminates the dependencies but is a pretty ugly hack.

**Comment by Evizero** [comment]
How about we add a `Images` dependency in `TestImages`? Doesn't sound too far

**Comment by Evizero** [comment]
I think it is fair enough to assume that efficient rendering in Jupyter requires more than just `using ImageCore`, but it shouldn't require more than `using TestImages` given it is a package that should be beginner friendly

**Comment by timholy** [comment]
The only problem with that strategy is it doesn't cover
```julia
using FileIO
img = load("some_file_from_my_harddrive.png")
```
So I guess we should have ImageMagick load Images. That does seem the best way.

**Comment by Evizero** [comment]
Good point

**Comment by rsrock** [comment]
Huh, I'd just noticed that ImageMagick was only using ImageCore, and not all of Images.  So I was about to make the same change to QuartzImageIO.  I guess I should hold off on that for now, then?

**Comment by timholy** [comment]
Yeah, seems like it.

**Comment by Evizero** [comment]
Alternatively - and this may be a bit out there - we could create a package `ImageInJupyter` which contains restrict and the `mime` code.

**Comment by rdeits** [comment]
Requiring Images in ImageMagick.jl seems reasonable to me as well. Would you like me to open a PR?

**Comment by timholy** [comment]
That'd be great, I've been a bit consumed with other tasks. :heart:
