### ISSUE TITLE
Names of float{32/64}{sc?}() conversion functions.

### ISSUE THREAD

**Issue by matthew-frank** [JuliaImages/Images.jl#62]
https://github.com/timholy/Images.jl/blob/master/doc/function_reference.md says that the pixel type conversion functions are called:
float32sc(img)
float64sc(img)
uint8sc(img)
uint16sc(img)
uint32sc(img)

But the defined functions for floating point conversion seem to be float32() and float64() (no "sc" in the name).

julia> myF32img = float32sc(img)
ERROR: no method ScaleMinMax{To,From}(Type{Float32}, Uint8, Int64, Float32)
 in float32sc at /nfs/fx/home/mifrank/.julia/Images/src/scaling.jl:269
julia> myF32img = float32(img)
Gray Image with:
  data: 512x512 Array{Float32,2}
  properties:
    limits: (0.0f0,255.0f0)
    storageorder:  x y
    colorspace: Gray

(Similarly with float64sc() and float64()).

I don't know whether the documentation or the implementation is correct, but they seem to disagree.

**Comment by manishshrestha** [comment]
Has this function float32sc() been deprecated? If not this bug seems not be fixed in 0.5.2 version of Images packages of Julia language. I am getting the same error.



```
julia>  function read_data(typeData, labelsInfo, imageSize, path)
        #Intialize x matrix
        x = zeros(size(labelsInfo, 1), imageSize)

        for (index, idImage) in enumerate(labelsInfo[:ID]) 
         #Read image file 
         nameFile = "$(path)/$(typeData)Resized/$(idImage).Bmp"
         img = imread(nameFile)

         #Convert img to float values 
         temp = float32sc(img)

         #Convert color images to gray images
         #by taking the average of the color scales. 
         if ndims(temp) == 3
          temp = mean(temp.data, 1)
         end
           
         #Transform image matrix to a vector and store 
         #it in data matrix 
         x[index, :] = reshape(temp, 1, imageSize)
        end 
        return x
       end
julia> xTrain = read_data("train", labelsInfoTrain, imageSize, path)
WARNING: imread(filename; kwargs...) is deprecated, use load(filename; kwargs...) instead.
 in depwarn at deprecated.jl:73
 in imread at deprecated.jl:50
 in read_data at none:14
while loading no file, in expression starting on line 0
ERROR: UndefVarError: float32sc not defined
 in read_data at none:17


julia> Pkg.status("Images")
 - Images                        0.5.2

```

**Comment by timholy** [comment]
It was deprecated a long time, and the deprecation was removed in 7503eeeab52a1c27396e91773e8dfcc2df5b6d88.

**Comment by manishshrestha** [comment]
Thank you for the prompt reply. :)

I was wondering what would be the alternative for float32sc() in above code.

**Comment by timholy** [comment]
Just click on the commit I linked to, it will be obvious.
