### ISSUE TITLE
JuliaImages Wiki and Tutorials

### ISSUE THREAD

**Issue by tejus-gupta** [JuliaImages/Images.jl#620]
I would like JuliaImages to be the home for everything image-processing. But right now there are a number of small packages that have important algorithms not present here. Would it be a good idea to add a Wiki listing these packages? Peter Kovesi's [ImageProjectiveGeometry.jl](https://github.com/peterkovesi/ImageProjectiveGeometry.jl), Maximiliano Suster's [OpenCV.jl](https://github.com/maxruby/OpenCV.jl) and [ImageRegistration.jl](https://github.com/seung-lab/ImageRegistration.jl) are some packages I have found very useful.

I think it would also be nice to have a place where users can contribute tutorials to JuliaImages. Users who have finished a project can present/share it with the community.
e.g., I have been using ImageFeatures and ImageProjectiveGeometry for a project involving monocular visual odometry. I think it would be a good tutorial on using ImageFeatures.
This can grow into a good collection of projects and paper implementations.

**Comment by timholy** [comment]
I know that @maxruby supports moving OpenCV.jl to JuliaImages. For the rest, the primary authors will have to chime in. If they don't want to move them to JuliaImages, we should definitely add some links, whether to a Wiki or to the documentation itself.

I've long wanted a set of tutorials, which I suspect should be added to https://github.com/JuliaImages/juliaimages.github.io. I'm not quite sure how to organize them, though.

**Comment by johnnychen94** [comment]
Close as it's a personal discussion and quite outdated now. We now have a demo page so if there's any idea, please just submit a PR there by adding your new demo.
