### ISSUE TITLE
Manipulation with Fixed Precision

### ISSUE THREAD

**Issue by ranjanan** [JuliaImages/Images.jl#622]
Suppose I try to implement a simple image blurring kernel: 
```julia
using Images, TestImages, ImageView

a = testimage("lighthouse")
b = similar(a)

for j = 2:size(a, 2) - 1 
   for i = 2:size(a, 1) - 1
       b[i,j] = (a[i,j+1] + a[i,j-1] + a[i+1,j] + a[i-1,j] )/4
   end
end
imshow(b)
```
The output looks like this: 

<img width="749" alt="screen shot 2017-04-13 at 12 31 01 pm" src="https://cloud.githubusercontent.com/assets/9101377/24993705/269d7bea-2045-11e7-99ef-e8c1062d3ecd.png">

But if I convert `a` to `Matrix{RGB{Float32}}`, I have enough precision to work with, and I get a decently blurred example. 

Is that a conscious decision? It would be nice to load images and straight up implement your own stencils for manipulating them without this problem.

**Comment by Evizero** [comment]
A non-breaking addition could be to allow users to specify a color depth in `testimage`

```julia
a = testimage(Float32, "lighthouse")
```

**Comment by timholy** [comment]
Images is just following Julia's lead here; if you created a `rand(UInt8, m, n)` array you'd get exactly the same phenomenon. And Images absolutely, positively, has to be able to work with 8-bit data.

However, Images does provide convenience functions to make "doing the right thing" easier: just change your stencil line to
```julia
(float32(a[i,j+1]) + a[i,j-1] + a[i+1,j] + a[i-1,j] )/4
```
(`float32` works on Colorants, not just numbers, which makes it different from `Float32(c)`).

**Comment by ranjanan** [comment]
Thanks for clarifying this. 

Could you point me to examples of Image manipulations done on strictly 8-bit data like how the image is loaded here?

**Comment by timholy** [comment]
Not quite sure what you mean. ImageFiltering is an example of a package that does stencil operations on all sorts of types. Also check out the implementation of [sum-of-square-differences](https://github.com/JuliaImages/Images.jl/blob/341d8964268977ea6624a233c9cace6301a29317/src/algorithms.jl#L274-L307) as an example of the ways in which this is a little tricky. (Though it's worth noting that with "modern" technology, `difftype` could be simplified to just 4 lines,
```julia
difftype{T<:Integer}(::Type{T}) = Int
difftype{T<:Real}(::Type{T}) = Float32
difftype(::Type{Float64}) = Float64
difftype{CV<:Colorant}(::Type{CV}) = base_colorant_type(CV){difftype(eltype(CV))}
```
). This is an "in-place" algorithm that's a model of computational efficiency. However, using a MappedArray to "virtually" change the element type is scarcely worse:
```julia
julia> function simplessd(init, a, b)
           s = init
           for i in eachindex(a, b)
               s += abs2(a[i]-b[i])
           end
           s
       end
simplessd (generic function with 1 method)

julia> using FixedPointNumbers

julia> a = rand(N0f8, 1000, 1001);

julia> b = rand(N0f8, 1000, 1001);

julia> simplessd(N0f8(0), a, b)
0.475N0f8                                 # oops, overflow

julia> using MappedArrays, Images

julia> ssd(a, b)
168094.44f0                               # no overflow

julia> simplessd(0.0f0, mappedarray(float32, a), mappedarray(float32, b))
168094.44f0                               # no overflow

julia> using BenchmarkTools

julia> @benchmark ssd($a, $b) seconds=1
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.353 ms (0.00% GC)
  median time:      5.553 ms (0.00% GC)
  mean time:        5.547 ms (0.00% GC)
  maximum time:     6.690 ms (0.00% GC)
  --------------
  samples:          180
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark simplessd(0.0f0, mappedarray($float32, $a), mappedarray($float32, $b)) seconds=1
BenchmarkTools.Trial: 
  memory estimate:  112 bytes
  allocs estimate:  7
  --------------
  minimum time:     7.029 ms (0.00% GC)
  median time:      7.299 ms (0.00% GC)
  mean time:        7.356 ms (0.00% GC)
  maximum time:     9.419 ms (0.00% GC)
  --------------
  samples:          136
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

**Comment by SimonDanisch** [comment]
I can just second @timholy here. It would be quite a big change, just to achieve that a person who does image manipulation, doesn't need to know about the fact that Images are usually stored with 8 bit per color which is insufficient for most manipulations...

You also can't possibly create a satisfactory default behaviour for all the different people using images. I'm in 90% of the cases fine with staying 8 bit, so why should I buy into 4x more memory plus a conversion? Others might want `Float64` all the time, while others want a compromise and would favor `Float32`. 
The only thing to do here is to document the fact, that `load(image)` might return a large variety of formats and people liking predictability should just always write something like `RGB{Float32}.(load(image))`.

**Comment by timholy** [comment]
Seems like there's nothing to do here. Feel free to ask for a reopen if you feel otherwise.
