### ISSUE TITLE
Incorrect grouping in multidimensional table of images

### ISSUE THREAD

**Issue by rdeits** [JuliaImages/Images.jl#625]
I love the table display introduced in https://github.com/JuliaImages/Images.jl/pull/574 :smile: 

But I think it might be grouping arrays of images with more than 2 dimensions in an odd way. Specifically, if I do the following:

```julia
using Colors
[fill(Gray{Float32}(z), 2, 2) for x in 1:2, y in 1:2, z in 0:1]
```

(the `fill(..., 2, 2)` is necessary to work around #623 )

I see:

```
2×2×2 Array{Array{ColorTypes.Gray{Float32},2},3}:
[:, :, 1] =
 ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]  …  ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]
 ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]     ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]

[:, :, 2] =
 ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]  …  ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]
 ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]     ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]
```

The above is hard to read, but the important point is that Julia arrays display in chunks by `[:, :, 1]`, `[:, :, 2]`, etc... which you can confirm by observing that the Gray values in the second chunk are all 1. 

When I load the Images.jl display code, however, I see:

![screenshot from 2017-04-13 16 16 08](https://cloud.githubusercontent.com/assets/591886/25022703/e74846c6-2064-11e7-8589-6e3bd62b7dd4.png)

which groups the elements differently. 

I think the fix for this is just to switch `i` and `colons...` in https://github.com/JuliaImages/Images.jl/blob/master/src/showmime.jl#L65 and https://github.com/JuliaImages/Images.jl/blob/master/src/showmime.jl#L53 but I'd like to make sure this isn't the intended behavior before I try to change that.

**Comment by rdeits** [comment]
cc @shashi

**Comment by shashi** [comment]
Well I thought of it like this: to reach `x[1,2,2]` you find the first of the outermost set of boxes, then the second box inside it and then the third 2nd box inside that. Which would lead you to a white box?

We should probably do what Julia would cause you to be familiar with though. (I rarely ever look at n-d arrays printed, so I'm not familiar with it).

**Comment by timholy** [comment]
I agree with making that switch. Thanks for the clear diagnosis, @rdeits.
