### ISSUE TITLE
Resolver blocks installation of Images-critical packages

### ISSUE THREAD

**Issue by mouryarahul** [JuliaImages/Images.jl#630]
```
julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

The results of package test:

```
julia> Pkg.test("Images")
INFO: Computing test dependencies for Images...
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of FactCheck from https://github.com/JuliaArchive/FactCheck.jl.git
INFO: Cloning cache of ImageMagick from https://github.com/JuliaIO/ImageMagick.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Installing BinDeps v0.4.7
INFO: Installing FactCheck v0.4.3
INFO: Installing ImageMagick v0.2.3
INFO: Installing SHA v0.3.2
INFO: Installing URIParser v0.1.8
INFO: Building ImageMagick
INFO: Testing Images
Test Summary:  | Pass  Total
  ColorizedArray |   15     15
Restriction: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: ImageTransformations.restrict(::AxisArrays.AxisArray{ColorTypes.RGB{Float64},2,Array{ColorTypes.RGB{Float64},2},Tuple{AxisArrays.Axis{:y,Base.OneTo{Int64}},AxisArrays.Axis{:x,Base.OneTo{Int64}}}}, ::Tuple{Int64,Int64}) is ambiguous. Candidates:
    restrict(A::AbstractArray, region::Tuple{Vararg{Int64,N<:Any}}) at /home/rahul/.julia/v0.5/ImageTransformations/src/resizing.jl:16
    restrict{T,N}(img::AxisArrays.AxisArray{T,N,D<:Any,Ax<:Any}, region::Union{Array{Int64,1},Tuple{Vararg{Int64,N<:Any}}}) at /home/rahul/.julia/v0.5/Images/src/algorithms.jl:504
   in macro expansion; at /home/rahul/.julia/v0.5/Images/test/algorithms.jl:260 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at /home/rahul/.julia/v0.5/Images/test/algorithms.jl:230 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at ./client.jl:265
   in _start() at ./client.jl:321
Test Summary:              | Pass  Error  Total
  Algorithms               |  211      1    212
  Statistics               |    6             6
  Features                 |   19            19
  Complement               |    5             5
  Entropy                  |    3             3
  Reductions               |   87            87
  fft and ifft             |    2             2
  Restriction              |    4      1      5
  Erode/ dilate            |    4             4
  Opening / closing        |    2             2
  Morphological Top-hat    |    2             2
  Morphological Bottom-hat |    1             1
  Morphological Gradient   |    2             2
  Morphological Laplacian  |    2             2
  Label components         |    9             9
  Phantoms                 |    2             2
  Image resize             |    3             3
  Interpolations           |   54            54
  Convex Hull              |    4             4
ERROR: LoadError: LoadError: Some tests did not pass: 211 passed, 0 failed, 1 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:498
 in macro expansion; at ./test.jl:681 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/rahul/.julia/v0.5/Images/test/algorithms.jl, in expression starting on line 4
while loading /home/rahul/.julia/v0.5/Images/test/runtests.jl, in expression starting on line 2
=============================================================================================[ ERROR: Images ]==============================================================================================

failed process: Process(`/home/rahul/DevTools/Julia-0.5.1/bin/julia -Cx86-64 -J/home/rahul/DevTools/Julia-0.5.1/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/rahul/.julia/v0.5/Images/test/runtests.jl`, ProcessExited(1)) [1]

============================================================================================================================================================================================================
INFO: Removing BinDeps v0.4.7
INFO: Removing FactCheck v0.4.3
INFO: Removing ImageMagick v0.2.3
INFO: Removing SHA v0.3.2
INFO: Removing URIParser v0.1.8
ERROR: Images had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:749
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
```

what could be the workaround ?

_edited by @Evizero for readability_

**Comment by timholy** [comment]
See https://github.com/JuliaImages/Images.jl/pull/628. There's a problem with `Pkg.resolver` that prevents the first half of the fix from being tagged. You can check out the master branch of ImageCore, and from there the fix isn't hard.

**Comment by mouryarahul** [comment]
Once I added the package "PyCall", it removed many of packages from "Images". Is this due to Pkg.resolver()?

Pkg.add("PyCall")
INFO: Cloning cache of Conda from https://github.com/JuliaPy/Conda.jl.git
INFO: Cloning cache of PyCall from https://github.com/JuliaPy/PyCall.jl.git
INFO: Downgrading ColorTypes: v0.4.1 => v0.2.12
INFO: Downgrading ColorVectorSpace: v0.4.2 => v0.1.12
INFO: Downgrading Colors: v0.7.3 => v0.6.9
INFO: Installing Conda v0.5.3
INFO: Downgrading FixedPointNumbers: v0.3.6 => v0.2.1
INFO: Downgrading Images: v0.9.1 => v0.5.14
INFO: Installing PyCall v1.11.1
INFO: Downgrading VT100: v0.1.0 => v0.0.2
INFO: Installing Zlib v0.1.12
INFO: Removing AxisAlgorithms v0.1.6
INFO: Removing AxisArrays v0.1.2
INFO: Removing CatIndices v0.0.2
INFO: Removing ComputationalResources v0.0.2
INFO: Removing CoordinateTransformations v0.4.1
INFO: Removing CustomUnitRanges v0.0.4
INFO: Removing DualNumbers v0.3.0
INFO: Removing FFTViews v0.0.2
INFO: Removing ImageAxes v0.2.1
INFO: Removing ImageCore v0.3.0
INFO: Removing ImageFiltering v0.1.4
INFO: Removing ImageMetadata v0.2.3
INFO: Removing ImageTransformations v0.2.2
INFO: Removing IndirectArrays v0.1.1
INFO: Removing Interpolations v0.4.0
INFO: Removing IntervalSets v0.0.5
INFO: Removing Iterators v0.3.0
INFO: Removing MappedArrays v0.0.7
INFO: Removing OffsetArrays v0.3.0
INFO: Removing RangeArrays v0.1.2
INFO: Removing Ratios v0.0.4
INFO: Removing Rotations v0.3.5
INFO: Removing ShowItLikeYouBuildIt v0.0.1
INFO: Removing SimpleTraits v0.4.0
INFO: Removing StaticArrays v0.3.0
INFO: Removing TiledIteration v0.0.2
INFO: Removing WoodburyMatrices v0.2.2
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /home/rahul/DevTools/anaconda3/bin/python (Python 3.6.0) at /home/rahul/DevTools/anaconda3/bin/python, libpython = /home/rahul/DevTools/anaconda3/lib/libpython3.6m
INFO: /home/rahul/.julia/v0.5/PyCall/deps/deps.jl has been updated
INFO: /home/rahul/.julia/v0.5/PyCall/deps/PYTHON has been updated
INFO: Package database updated

I'm stuck with this problem ! :(

**Comment by timholy** [comment]
For the resolver issue, let's CC @tkelman, since he's been very helpful on issues related to package versions. It might help if you posted your `Pkg.status()`.

But in what I said above, I was a bit confused. A fix is on the way, see #631.

**Comment by mouryarahul** [comment]
I cannot reproduce the same above situation because I removed .julia folder at all. But now after installing some packages, when I try to install package "Atom", I get following error, which I guess is due to Pkg.resolver:
Pkg.add("Atom")
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: ColorVectorSpace
  (you may try increasing the value of the
   JULIA_PKGRESOLVE_ACCURACY environment variable)
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at ./pkg/resolve.jl:37
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:495
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at ./pkg/entry.jl:30
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in macro expansion at ./task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in add(::String) at ./pkg/pkg.jl:100

Package status is as follow:
Pkg.status()
7 required packages:
 - Distributions                 0.12.4
 - Grid                          0.4.2
 - Images                        0.9.1
 - MPI                           0.5.0
 - PyCall                        1.11.1
 - PyPlot                        2.3.1
 - Roots                         0.3.0
59 additional packages:
 - AxisAlgorithms                0.1.6
 - AxisArrays                    0.1.2
 - BinDeps                       0.4.7
 - Calculus                      0.2.2
 - CatIndices                    0.0.2
 - ColorTypes                    0.4.1
 - ColorVectorSpace              0.4.2
 - Colors                        0.7.3
 - Combinatorics                 0.4.0
 - Compat                        0.23.0
 - ComputationalResources        0.0.2
 - Conda                         0.5.3
 - CoordinateTransformations     0.4.1
 - CustomUnitRanges              0.0.4
 - DataStructures                0.5.3
 - DiffBase                      0.1.0
 - DualNumbers                   0.3.0
 - FFTViews                      0.0.2
 - FileIO                        0.3.1
 - FixedPointNumbers             0.3.6
 - ForwardDiff                   0.4.2
 - Graphics                      0.2.0
 - ImageAxes                     0.2.1
 - ImageCore                     0.3.0
 - ImageFiltering                0.1.4
 - ImageMetadata                 0.2.3
 - ImageTransformations          0.2.2
 - IndirectArrays                0.1.1
 - Interpolations                0.5.0
 - IntervalSets                  0.0.5
 - Iterators                     0.3.0
 - JSON                          0.9.0
 - LaTeXStrings                  0.2.1
 - MacroTools                    0.3.6
 - MappedArrays                  0.0.7
 - NaNMath                       0.2.4
 - OffsetArrays                  0.3.0
 - PDMats                        0.5.6
 - PolynomialFactors             0.0.4
 - Polynomials                   0.1.5
 - Primes                        0.1.3
 - QuadGK                        0.1.2
 - RangeArrays                   0.1.2
 - Ratios                        0.0.4
 - Reexport                      0.0.3
 - Rmath                         0.1.6
 - Rotations                     0.3.5
 - SHA                           0.3.2
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.0.1
 - SimpleTraits                  0.4.0
 - SpecialFunctions              0.1.1
 - StaticArrays                  0.3.0
 - StatsBase                     0.13.1
 - StatsFuns                     0.5.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.2
 - URIParser                     0.1.8
 - WoodburyMatrices              0.2.2

**Comment by mouryarahul** [comment]
I cannot reproduce the same above situation because I removed .julia folder at all. But now after installing some packages, when I try to install package "Atom", I get following error, which I guess is due to Pkg.resolver:
Pkg.add("Atom")
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: ColorVectorSpace
(you may try increasing the value of the
JULIA_PKGRESOLVE_ACCURACY environment variable)
in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at ./pkg/resolve.jl:37
in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:495
in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at ./pkg/entry.jl:30
in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:360
in sync_end() at ./task.jl:311
in macro expansion at ./task.jl:327 [inlined]
in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:59
in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
in add(::String) at ./pkg/pkg.jl:100

Package status is as follow:
Pkg.status()
7 required packages:

Distributions 0.12.4
Grid 0.4.2
Images 0.9.1
MPI 0.5.0
PyCall 1.11.1
PyPlot 2.3.1
Roots 0.3.0
59 additional packages:
AxisAlgorithms 0.1.6
AxisArrays 0.1.2
BinDeps 0.4.7
Calculus 0.2.2
CatIndices 0.0.2
ColorTypes 0.4.1
ColorVectorSpace 0.4.2
Colors 0.7.3
Combinatorics 0.4.0
Compat 0.23.0
ComputationalResources 0.0.2
Conda 0.5.3
CoordinateTransformations 0.4.1
CustomUnitRanges 0.0.4
DataStructures 0.5.3
DiffBase 0.1.0
DualNumbers 0.3.0
FFTViews 0.0.2
FileIO 0.3.1
FixedPointNumbers 0.3.6
ForwardDiff 0.4.2
Graphics 0.2.0
ImageAxes 0.2.1
ImageCore 0.3.0
ImageFiltering 0.1.4
ImageMetadata 0.2.3
ImageTransformations 0.2.2
IndirectArrays 0.1.1
Interpolations 0.5.0
IntervalSets 0.0.5
Iterators 0.3.0
JSON 0.9.0
LaTeXStrings 0.2.1
MacroTools 0.3.6
MappedArrays 0.0.7
NaNMath 0.2.4
OffsetArrays 0.3.0
PDMats 0.5.6
PolynomialFactors 0.0.4
Polynomials 0.1.5
Primes 0.1.3
QuadGK 0.1.2
RangeArrays 0.1.2
Ratios 0.0.4
Reexport 0.0.3
Rmath 0.1.6
Rotations 0.3.5
SHA 0.3.2
SIUnits 0.1.0
ShowItLikeYouBuildIt 0.0.1
SimpleTraits 0.4.0
SpecialFunctions 0.1.1
StaticArrays 0.3.0
StatsBase 0.13.1
StatsFuns 0.5.0
TexExtensions 0.0.3
TiledIteration 0.0.2
URIParser 0.1.8
WoodburyMatrices 0.2.2

**Comment by timholy** [comment]
I believe this is fixed now, comment or reopen if not.
