### ISSUE TITLE
Blob_LoG does not work with N dim arrays

### ISSUE THREAD

**Issue by AShedko** [JuliaImages/Images.jl#641]
See https://github.com/JuliaImages/Images.jl/blob/master/src/algorithms.jl#L430

The kernel function (`Kernel.LoG`) should take `ntuple(d->sigmas[isigma],Val{N})`

Also: What is the point of tail(x.I) on line 433 if x.I is a N+1 tuple of Int (i.e. an array index)? 

The error:
```
blob_LoG(mr,[i for i ∈ 1:0.4:10]);
ArgumentError: ImageFiltering.Pad{2}(:replicate,(4,4),(13,15)) lacks the proper padding sizes for an array with 3 dimensions
```
where `mr::Array{Float64,3}`

**Comment by bjarthur** [comment]
it used to be the case that `imfilter_LoG`, which `blob_LoG` depends on, did not support N>2.  it's replacement, `Kernel.LoG` appears to have removed this limitation.  unfortunately, it doesn't appear that any tests for `blob_LoG` were added when this change was made for the case that N>2.

**Comment by timholy** [comment]
Hmm, yes. One thing I wonder about: how useful is a scalar `σ` for 3d images? Often the resolution is not isotropic, and if `σ` is measured in voxels then it probably doesn't make sense. OTOH, if we have `σ` in physical units, and the image encodes the pixel spacing with an AxisArray, then maybe scalar `σ` would be OK.

**Comment by bjarthur** [comment]
@AShedko if your fix works, please submit a PR.  would be great to have `blob_LoG` working on N-D arrays.

**Comment by timholy** [comment]
Sorry, I forgot to respond to this:

> Also: What is the point of tail(x.I) on line 433 if x.I is a N+1 tuple of Int (i.e. an array index)?

The `maxima` array has the index for `σs` as its first index. So the `tail` just gives you the image position.

@bjarthur or others, any thoughts about the scalar `σ` question? I think we need a different interface, and it would be great to hear other people's thoughts on it. Two options that occur:

- changing `σs` to be a `Vector{<:SVector}`. This is very generic but the supplied vectors may not fall into some kind of linear order
- use two arguments, a `σbase::Union{AbstractVector,Tuple}` and then an iterable `σfactors`, where at the `i`th scale we have `σ = σfactors[i] * σbase`.

**Comment by bjarthur** [comment]
definitely need to be able to handle anisotropic images.  using `AxisArrays` makes sense to me, as does making `σs` a vector.  but what do you mean by "not fall into some kind of linear order"?

**Comment by AShedko** [comment]
I belive this "not fall into some kind of linear order" refers to the ambiguity when ordering vectors.
Is [1,2,3] larger than [2,1,3]? What about [2,√5,√5]? They all have the same magnitude,
The two argument option would break less existing code if we pass `ones(Val{N})` as default.

**Comment by timholy** [comment]
That's exactly right. Moreover, I think even `[2, 2, 1.5]` and `[1, 1, 1]`, while you can defend premise that these can be ordered, would still be a little weird. Perhaps we should support it in case it's useful, but to me it seems the default should assume that they are scalar multiples of one another.
