### ISSUE TITLE
Load returning zeros for tiff file

### ISSUE THREAD

**Issue by dryden4482** [JuliaImages/Images.jl#644]
Windows, Julia 0.5.2 ImageMagick. I have tried both 6 and seven versions of image magick. 
Thank you For your help!

dump(img2)
Array{ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}}((26918,24784))
  1: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  2: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  3: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  4: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  5: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  ...
  667135708: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  667135709: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  667135710: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  667135711: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0
  667135712: ColorTypes.Gray{FixedPointNumbers.Normed{UInt16,16}}
    val: FixedPointNumbers.Normed{UInt16,16}
      i: UInt16 0

**Comment by timholy** [comment]
No way to debug this without having the image you're trying to load. But I wonder if this is similar to https://github.com/JuliaIO/ImageMagick.jl/issues/99.

**Comment by dryden4482** [comment]
I see, I don't think I can share the image. Have you seen any issue with loading on the size of the image? A cropped version of the same image about a tenth of it loads no problem. The same is true of ArrayFire's image loading. The image is loaded fine for the cropped version but returns zeros for the non cropped versions.

**Comment by timholy** [comment]
How big is your image? What's the threshold for problems?

**Comment by dryden4482** [comment]
The original image is about 1.45 GBs. The cropped version is 34MBs. I can use cropped versions of the image as the julia code is further segmenting the image. It would just be nice to do it all within Julia. 

The problem I'm currently having is not being able to use the FileIO functionality withen atom on windows. loading an image in the terminal julia works great! However when i run the same code from withen atom i get the following error. 

no decode delegate for this image format `TIFF'

Atom is being started from the terminal and has the appropriate values within the ENV array.

**Comment by dryden4482** [comment]
Here is the test image I'm currently using. 

[test1.zip](https://github.com/JuliaImages/Images.jl/files/1075743/test1.zip)

**Comment by timholy** [comment]
That atom error suggests some kind of failure in the ImageMagick library, but I don't know why atom would be using a different version that the REPL. It's likely to take some debugging to figure that one out, I don't really have any ideas. (You might check `ImageMagick.libversion`. If that isn't helpful, @Allardvm recently debugged such a problem recently, perhaps he might have some tips? https://github.com/JuliaPackaging/Homebrew.jl/issues/175#issuecomment-304019539).

With regards to your image, for me it loads as a `GrayA{N0f8}` image of size 570x570, and it's a picture of a tree in fog. Seems like it's working for me. You're saying that when you try the same image, you don't get something that's reasonable? If so, what does `Pkg.status("ImageMagick")` and `ImageMagick.libversion` return?

**Comment by dryden4482** [comment]
I, should have been more specific. That is the image that I'm trying to load from within atom itself. I can not share the original image. The other problem with loading images is trying to load it by running the script for example julia image_analysis.jl returns the same no decode delegate for this image format `TIFF' error. 
Yet the image loads just fine from within the julia power shell.

**Comment by timholy** [comment]
It also works for me inside atom.

**Comment by dryden4482** [comment]
It seems as though the problem is coming from ArrayFirejl. I deleted the .julia file and reinstalled the packages one at a time. After installing Array Fire I received the error no decode delegate for this image format `TIFF'. Even if I explicitly call ImageMagick.load(image).

**Comment by timholy** [comment]
Hmm, surprising. Can you raise the issue with ArrayFire? You might also show some full backtraces, so we know which code is being called when the error is triggered.

**Comment by timholy** [comment]
Since Images.jl anyway isn't doing any IO, I'm going to close this. If this resurfaces or needs more discussion, let's move this to ImageMagick.jl.
