### ISSUE TITLE
Rotating multiple objects in a fast way in channel view mode

### ISSUE THREAD

**Issue by ereday** [JuliaImages/Images.jl#646]
Hi, 
Is there a way to rotate bunch of images that are stored as `Array{Float32,4} ` in a fast way without going back to `colorview` mode ? Formally, I have an 4 dimensional `x` array with size of `(128,128,3,24)` that stores 24 images each of which is 128x128 color image. For now, I'm able to rotate them as follows:

```
x = permutedims(x,[3,1,2,4])
xout = zeros(136,136,3,24)
tfm = recenter(RotMatrix(0.05), center(colorview(RGB,rand(3, 128, 128))))
for i=1:size(x,4)
   x1 = x[:,:,:,i]
   x2 = colorview(RGB,x1)
   x3 = convert(Array{ColorTypes.RGB{N0f8},2},x2)
   x4 = warp(x3,tfm)
   x5 = permutedims(channelview(parent(x4)),[2,3,1])
   xout[:,:,:,i] = x5 # Here size of x5 might change time to time. I see it as both 136x136 and 136x135
end
```

**Comment by timholy** [comment]
Presumably you could rotate each channel separately, but that might actually be slower because it has to compute the interpolation coefficients many times. Still, you could do your warping in 4d:
```julia
using Interpolations, StaticArrays
itp = interpolate(x, (BSpline(Linear()), BSpline(Linear()), NoInterp(), NoInterp()), OnGrid())
etp = extrapolate(itp, NaN)
# Define a 4-dimensional transformation function. Applies the rotation defined above to just the first two dimensions
tfm4 = x->(y = tfm(@SVector([x[1], x[2]])); @SVector([y[1], y[2], x[3], x[4]]))
xout = similar(x)
ImageTransformations.warp!(xout, etp, tfm4)
```

**Comment by ereday** [comment]
So, I just applied the recipe you provided. (Just added the tfm definition) 
```julia
using Interpolations, StaticArrays
function rotateBatches(x)
 itp = interpolate(x, (BSpline(Linear()), BSpline(Linear()), NoInterp(), NoInterp()), OnGrid())
    etp = extrapolate(itp, NaN)
    # Define a 4-dimensional transformation function. Applies the rotation defined above to just the first two dimensions
    tfm = recenter(RotMatrix(0.05), center(colorview(RGB,rand(3, 128, 128)))) # Added by me
    tfm4 = x->(y = tfm(@SVector([x[1], x[2]])); @SVector([y[1], y[2], x[3], x[4]]))
    xout = similar(x)
    ImageTransformations.warp!(xout, etp, tfm4)
    return xout
end
```
Then I create a batch of images as below, resize them and run the above function: 
```julia
function resizer(img,sz)
    σ = map((o,n)->0.75*o/n, size(img), sz)
    kern = KernelFactors.gaussian(σ)   # from ImageFiltering
    imgr = imresize(imfilter(img, kern, NA()), sz)
    return imgr
end

 
    img  = load("demo-img.png")
    imgr = resizer(img,(128,128))
    xx = channelview(imgr)
    x = permutedims(xx,[2,3,1])[:,:,1:3]
    imgbatch  = cat(4,[x for i=1:64]...)
    out = rotateBatches(imgbatch)
```
However, there are lot's of NaN values in out. (There were none when I rotate them as I explained in my first message.)

**Comment by Evizero** [comment]
> However, there are lot's of NaN values in out.

change `etp = extrapolate(itp, NaN)` to your desire of `NaN` isn't what you want for extrapolated points

**Comment by ereday** [comment]
Yea, I realized that, but I believe, both of the options(option1 & rotateBatches) should output the same thing whereas in this case they don't.

**Comment by timholy** [comment]
Two differences:
- when you call `warp!` you "trim" any edges that don't fall within the indices out `out`
- Are you not using `warp_new`? If not, keep in mind that it's *really* important to pay attention to and fix deprecation warnings: soon we will remove the warning and default to the behavior of `warp_new`, and if you haven't fixed the warning in your own code then suddenly all your code will do something different than it used to.

**Comment by timholy** [comment]
@ereday, when you're satisfied, please close the issue.
