### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaImages/Images.jl#647]
It would be good to tag a release that includes #642. Folks are running into problems https://discourse.julialang.org/t/images-save-downsizes-images/4329. 

@timholy

**Comment by davidanthoff** [comment]
It seems that the problem is fixed with #642, according to https://discourse.julialang.org/t/images-save-downsizes-images/4329. So either tagging ``master`` or releasing a point release is probably a high priority right now to fix this...

**Comment by timholy** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/9855. Thanks for the reminder, I haven't had the time lately to follow discourse.
