### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ssulun16** [JuliaImages/Images.jl#649]
Hi there. I thought there might be a memory leak with the function "load".
When I run
```
using Images
while true
    I = load("im.jpg")
end
```
My CPU memory usage keeps increasing. Is this normal? Thanks

```
julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by timholy** [comment]
I can't replicate on 0.6:
```julia
julia> versioninfo()
Julia Version 0.6.1-pre.0
Commit dcf39a1 (2017-06-19 13:06 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
Can you test? If you still get this phenomenon, then to debug it might be helpful to save an image as a `*.ppm` file, as that uses the Netpbm.jl package rather than ImageMagick. (It might help figure out where the issue is coming from.)

**Comment by ssulun16** [comment]
You're right, no problems on 0.6. Thanks to your advice, here is the workaround for 0.5:

```
using Netpbm, FileIO
while true
  I = Netpbm.load(File(format"PPMBinary","im.ppm"))
end
```

Thanks a lot!

**Comment by timholy** [comment]
Great, glad that worked.

Just FYI, it's even easier:
```
using FileIO

while true
    I = load("im.ppm")
end
```
(The main point of FileIO is so that users don't have to know which package is used to open which format.)

**Comment by ssulun16** [comment]
Strangely this also causes a continuous increase in memory usage.

**Comment by timholy** [comment]
Now that's surprising! But I can't replicate this locally even with 0.5.

If you're happy with 0.6 I think we can leave this as a mystery, but if there's some reason you need 0.5 and the workaround doesn't always work, by all means reopen.

**Comment by ssulun16** [comment]
I actually do need 0.5 since some libraries I use don't work on 0.6. Plus I realized the file size of ppm is much larger than jpeg which can create some problems while working with large datasets, therefore I'll reopen. Thanks again.

**Comment by timholy** [comment]
OK, next step: can you try 0.5.2?

**Comment by ssulun16** [comment]
Still the same. Also checked on Amazon remote server.

```
julia> versioninfo()
Julia Version 0.5.2
Commit f4c6c9d (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by timholy** [comment]
You're using `top` or some equivalent to check memory usage, right? Just to make sure I'm doing things the same way you are.

Also, for reference:
```julia
julia> Pkg.status("FileIO")
 - FileIO                        0.3.1

julia> Pkg.status("Netpbm")
 - Netpbm                        0.2.0
```

**Comment by ssulun16** [comment]
Yes, I use `top`.

```
julia> Pkg.status("FileIO")
 - FileIO                        0.4.1              master

julia> Pkg.status("Netpbm")
 - Netpbm                        0.2.0

```

**Comment by timholy** [comment]
I upgraded my 0.5 FileIO to 0.4.1 just to be sure that wasn't it. I still can't replicate the problem. I'm not sure I see a way for me to debug this further, so if it really bothers you it might be necessary for you to dig into it. (There are many online resources about identifying memory leaks.) That said, it might be easier for you to simply update the packages you depend on to 0.6? It needs to happen anyway...

**Comment by ssulun16** [comment]
Unfortunately the update isn't available for the package I'm working with. Thanks again for all your help.

**Comment by timholy** [comment]
If it's open-source, you could be the one to fix it! :smile: Anyway, best of luck.
