### ISSUE TITLE
bwdist

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/Images.jl#65]
I'm dying to move from Matlab to Julia, and doing my best, but there are a few power-functions that Matlab has and Julia doesn't. One of which is bwdist:

> D = bwdist(BW) computes the Euclidean distance transform of the binary image BW. For each pixel in BW, the distance transform assigns a number that is the distance between that pixel and the **nearest nonzero pixel** of BW.  

The Matlab algorithm is based on [A linear time algorithm for computing exact Euclidean distance transforms of binary images in arbitrary dimensions](http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1177156), which is beyond my scope as a novice Julia user :(
This is a suggestion for an enhancement... Seems natural it should belong to Images.jl (as opposed to https://github.com/JuliaStats/Distance.jl), but I might be wrong!

P.S.
Thanks for all the awesome work!!!

**Comment by juliohm** [comment]
@yakir12, meanwhile you can use the nice PyCall package:

```julia
using PyCall
@pyimport scipy.ndimage.morphology as pymorph

A = eye(5)
D = pymorph.distance_transform_edt(1-A)
```

Check this thread on SO: http://stackoverflow.com/questions/5260232/matlab-octave-bwdist-in-python-or-c

**Comment by timholy** [comment]
There's also #99. It would be great if someone who uses this function could test it.

**Comment by yakir12** [comment]
This is great! I'll test #99 ASAP.

**Comment by muhlba91** [comment]
Work of #99 has been carried on in #576

**Comment by juliohm** [comment]
I think this issue can be closed now, can you confirm?

**Comment by yakir12** [comment]
Yes!

Den 2 okt 2017 07:54 skrev "Júlio Hoffimann" <notifications@github.com>:
