### ISSUE TITLE
file-reading discrepancy between older and newer versions (no error message)

### ISSUE THREAD

**Issue by tomerarnon** [JuliaImages/Images.jl#651]
I've got some legacy code that relies on a very old version of Images.jl and two other related packages. I'd like to be able to update to the latest version of these packages and I was hoping someone might know what could be causing a particular issue I encounter when using the new versions.

First, the issue does not occur in the following versions (running in Julia v0.5 on a windows machine) but updating any one of them to its latest release creates a problem:
> Images:            v0.5.14
> ImageMagick:   v0.1.8
> DataArrays:      v0.3.9

The issue stems from the fact that the following lines produce different values for the same pixel of an image when run with the different package versions:

```
i = Images.load(filename)
c = convert(Image{Images.Gray}, i)
c[1196, 1475]     #(a random pixel that I happen to know is affected)
```

With the old package versions, the pixel is a `Gray{N0f8}` with value `0.784` (opening the image in paint/gimp/etc. suggests that this is the correct value). With updated packages, the pixel has the value `0.0`. The PNG this was done with is attached at the bottom for reference, but the problem isn't unique to it. This discrepancy is wreaking havoc on the old code, which reads hundreds of these images and uses information from specific pixel values.

Could this be something as simple as a different indexing convention? Unfortunately I can't run both versions of Images in the same session, to directly compare the images loaded in the two different ways. 

In any case, I was hoping this had to do with something glaring and obvious and that someone here could help me solve it.

Thanks!

![ldem_80n_20m img dsn 2021-09-15t18-00-00 050](https://user-images.githubusercontent.com/25778104/27672209-0d8320c0-5c4e-11e7-81ae-4d20b020e12b.png)

**Comment by rdeits** [comment]
I believe that older versions of Images.jl treated indices (by default) as (x, y) pairs, which made sense for images but was pretty unexpected when you expected an image to be treated like an array of pixels. The new versions of Images.jl default to treating an image *exactly* like a matrix of pixels, so the image indices are now (row, col), just like matrices. You can just transpose your images or use `permuteddimsview()` to get a view of the image data with the row and col indices swapped. 

Some documentation about this here: http://juliaimages.github.io/latest/conversions_views.html#Changing-the-order-of-dimensions-1

**Comment by tomerarnon** [comment]
Thanks for the reply! This is excellent news.
I can't test this tonight, unfortunately, but I'll report back tomorrow!
