### ISSUE TITLE
Move morphological operations to a separate package

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#660]
The number of dependencies in Images.jl has increased a lot since its initial version. For my package ImageQuilting.jl I only need imfilter() and dilate(). The former is available in ImageFiltering.jl, but the latter is still implemented at Images.jl.

Could we move all morphology-related operations to a separate package like ImageMorphology.jl or even to ImageFiltering.jl? That would reduce the number of dependencies tremendously.

**Comment by timholy** [comment]
Please do! https://github.com/JuliaImages/ImageMorphology.jl. You have push access.

**Comment by juliohm** [comment]
Thank you Tim! Will do it.

**Comment by juliohm** [comment]
Hi Tim, I tried pushing, but it seems I don't have the permission:

>ERROR: Permission to JuliaImages/ImageMorphology.jl.git denied to juliohm.
fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
and the repository exists.

**Comment by juliohm** [comment]
I have everything setup locally, just need push access to the repo to configure Travis and codecov.

**Comment by juliohm** [comment]
@Evizero @mronian @kmsquire since you are owners of the organization as well, could you please give me push access to ImageMorphology.jl as proposed by Tim? I wanted to finish this before the weekend, too many things to solve next week.

**Comment by SimonDanisch** [comment]
I added you!

**Comment by juliohm** [comment]
Thanks @SimonDanisch! I will proceed with the push.

**Comment by juliohm** [comment]
@SimonDanisch could you please activate Travis for the repo as well? This is the only missing component, everything should be working already.

**Comment by timholy** [comment]
Thanks for helping, all, I'm away and can't easily handle such things.
