### ISSUE TITLE
Error in `var(::Vector{<:RGB})`

### ISSUE THREAD

**Issue by rdeits** [JuliaImages/Images.jl#669]
It looks like `var()` works fine for 2D color arrays, but tries to construct the color elements incorrectly for 1D color arrays:

```julia
julia> pxs = [zero(RGB{Float32}) for i in 1:2]
2-element Array{RGB{Float32},1}:
 RGB{Float32}(0.0,0.0,0.0)
 RGB{Float32}(0.0,0.0,0.0)

julia> var(pxs)
ERROR: MethodError: no method matching ColorTypes.RGB(::Float32, ::Float32, ::Float32, ::Float32, ::Float32, ::Float32)
Closest candidates are:
  ColorTypes.RGB(::T<:Union{AbstractFloat, FixedPointNumbers.FixedPoint}, ::T<:Union{AbstractFloat, FixedPointNumbers.FixedPoint}, ::T<:Union{AbstractFloat, FixedPointNumbers.FixedPoint}) where T<:Union{AbstractFloat, FixedPointNumbers.FixedPoint} at /Users/rdeits/.julia/v0.6/ColorTypes/src/types.jl:97
  ColorTypes.RGB(::Real, ::Real, ::Real) at /Users/rdeits/.julia/v0.6/ColorTypes/src/types.jl:442
Stacktrace:
 [1] #var#2(::Array{Any,1}, ::Function, ::Array{ColorTypes.RGB{Float32},1}) at /Users/rdeits/.julia/v0.6/Images/src/algorithms.jl:89
 [2] var(::Array{ColorTypes.RGB{Float32},1}) at /Users/rdeits/.julia/v0.6/Images/src/algorithms.jl:80

julia> var(reshape(pxs, 2, 1))
RGB{Float32}(0.0f0,0.0f0,0.0f0)
```

This is on Images.jl master with

```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
```

**Comment by Evizero** [comment]
This looks like a bug in `ImageCore.channelview` to me

```julia
julia> pxs = [zero(RGB{Float32}) for i in 1:2]
2-element Array{RGB{Float32},1}:
 RGB{Float32}(0.0,0.0,0.0)
 RGB{Float32}(0.0,0.0,0.0)

julia> channelview(pxs)
6-element Array{Float32,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```

vs

```julia
julia> channelview(pxs')
3×1×2 Array{Float32,3}:
[:, :, 1] =
 0.0
 0.0
 0.0

[:, :, 2] =
 0.0
 0.0
 0.0
```

**Comment by rdeits** [comment]
Good point! More fundamentally, it's due to channelview calling https://github.com/JuliaImages/ImageCore.jl/blob/a278c6d92cb195ea153bbb5f57ee27592bdb82d0/src/convert_reinterpret.jl#L21 for 1-D arrays. I guess this mirrors the Base behavior, in which `reinterpret(T, x::Vector)` automatically gives you a (potentially longer) vector. 

I guess the question is: Should `reinterpret(Float32, ::Vector{RGB{Float32}})` give a 6-element vector (like Base) or a 3x2 matrix (like channelview). If it's the former, then we should fix `channelview`; if it's the latter then we should fix `reinterpret`.

**Comment by Evizero** [comment]
I am unsure about the future of `reinterpret` in 0.7, but as far as 0.6 is concerned I'd say that the current behaviour is the correct one.

I think the most appropriate fix would be for `channelview` to dispatch on vectors and just treat them differently. Probably some combination of `reshape` and `reinterpret` could do the trick. I didn't test how the situation is for `ChannelView`. That may or may not require some tweaks as well.

Interested in submitting a PR ? I'd be happy to provide quick reviews

**Comment by rdeits** [comment]
Sure, I'll take a shot.

**Comment by zygmuntszpak** [comment]
Can we close this issue since a solution appears to have been merged?

**Comment by rdeits** [comment]
Yes, thanks!
