### ISSUE TITLE
Question: image filtering

### ISSUE THREAD

**Issue by mdhe1248** [JuliaImages/Images.jl#674]
Would it be possible to filter only given dimensions?
For example,
```jl
img = rand(10,10, 3)
imgf = imfilter(img, Kernel.gaussian((3,3,0))) # I want to filter 1st and 2nd dimensions, but not 3rd
```

I use for loop, but I guess there is better way.
```jl
img = rand(10,10,3)
imgf = similar(img)
for i in 1:size(imgf,3)
    imgf[:,:,i] = imfilter(view(img, :,:,i), Kernel.gaussian((3,3)))
end
```

**Comment by timholy** [comment]
The version you tried is exactly the right way to do it. Note:
```julia
imgf1 = imfilter(img, Kernel.gaussian((3,3,0)))
imgf2 = similar(img)
for i in 1:size(imgf2,3)
    imgf2[:,:,i] = imfilter(view(img, :,:,i), Kernel.gaussian((3,3)))
end

julia> imgf1 ≈ imgf2
true
```
There are very tiny roundoff-error differences between the two, but that's it.

This should also work and be more efficient:
```julia
kern = KernelFactors.gaussian((3, 3, 0))
imfilter(img, kern)
```
but there's a bug:
```julia
julia> kern[3]
ImageFiltering.KernelFactors.ReshapedOneD{Float64,3,2,OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}}}([NaN])
```
That should be 1.0 instead of `NaN`. Fix in https://github.com/JuliaImages/ImageFiltering.jl/pull/43.

**Comment by timholy** [comment]
Also note that if you are using one axis to represent color, usually a more straightforward approach is to just use colors:
```julia
img = rand(RGB{Float64}, 10, 10)
imgf = imfilter(img, KernelFactors.gaussian((3,3)))
```
If you have to interoperate with e.g., Python, then the storage order difference may make this less desirable. You can of course use `permutedims` or `permuteddimsview` in combination with `colorview` to fix this, but in some cases just filtering specially along the color axis might be easiest.

**Comment by timholy** [comment]
Please suggest anything else that needs doing to clarify your initial concern. Specifically, I'm wondering what made you doubt your initial solution. Does it need more docs?

Or if satisfied, close the issue.

**Comment by mdhe1248** [comment]
Thanks for great answers! 
I didn't clarify the issue, which is returning `NaN` when a kernel has 0 in a dimension. Fixing the bug cleared everything I need. Thanks!
