### ISSUE TITLE
Please clarify pixel coordinates when refering to x and y

### ISSUE THREAD

**Issue by Affie** [JuliaImages/Images.jl#683]
Hello everyone, Please forgive me if I'm missing something. I had a look at https://github.com/JuliaImages/Images.jl/issues/539, https://github.com/JuliaImages/ImageTransformations.jl/issues/25, the documentation, and also a few different functions referring to x and y to try and figure things out.
First off I understand an affine map (lets say only translation and rotation) to be of the form:
```
w =  [cos(a)  -sin(a) x_off;
      sin(a)   cos(a) y_off]
```
I few functions that refer to x and y as [y,x]:
```julia
forwarddiffx(img) forwarddiffy(img) #etc
keypoint = Keypoint(y, x)
```
However, from how I see it, warp seems to be different. 
For example, the following code moves the image in the first dimension (vertical)
```julia
θ = 0.
W_p = AffineMap(SMatrix{2,2}((cos(θ), sin(θ), -sin(θ), cos(θ))), SVector(10,0))
    AffineMap([1.0 -0.0; 0.0 1.0], [10, 0])
imgw = warp(img, W_p)
```
Rotation seems to follow axis-rotation for the 'z' axis pointing out of the image.
Can someone please clarify?

**Comment by dehann** [comment]
+1

**Comment by johnnychen94** [comment]
closed in favor of https://github.com/JuliaImages/juliaimages.github.io/issues/173
