### ISSUE TITLE
Resize functionality?

### ISSUE THREAD

**Issue by malmaud** [JuliaImages/Images.jl#69]
Are there methods for resizing an image? I'm not seeing them in the docs, but I might be blind. If not, libmagickwand already provides them, so it's just a matter of wrapping them.

**Comment by mbauman** [comment]
Just a note for posterity since this is a top search result for "Images.jl resize" — this has since been implemented as [`Images.imresize`](https://github.com/timholy/Images.jl/blob/dc78510d112b330eab39c9257e4f9cf0e5864d85/src/algorithms.jl#L1068-L1090).  I imagine it just needs documentation/export for this issue to be closed.

**Comment by timholy** [comment]
Now that we're committed to 0.4, I can start using Interpolations within Images. That will be quite a game-changer, and allow for implementations (or better implementations) of quite a few algorithms.

But I'm stuck on updating ImageView first. So in the meantime, keep using `Images.resize`.

**Comment by juliohm** [comment]
Sorry reviving old issues, but I think this one can also be closed?

**Comment by Evizero** [comment]
Yes, `imresize` (and `imresize!`) is alive and well.

- implemented in https://github.com/JuliaImages/ImageTransformations.jl
- available by `using Images`
- see http://juliaimages.github.io/latest/function_reference.html#Spatial-transformations-and-resizing-1

**Comment by ekinakyurek** [comment]
Which interpolation method does `imresize` use for subpixels?  Currently, there is no way to specify interpolation type in `imresize`. Are you planning to add this feature?

**Comment by Evizero** [comment]
you should be able to just pass a `AbstractInterpolation` from Interpolations.jl to it

see https://github.com/JuliaImages/ImageTransformations.jl/blob/master/src/resizing.jl#L239

**Comment by ekinakyurek** [comment]
Thank you for your help. 

Is it better to make this a keyword argument in [user functions](https://github.com/JuliaImages/ImageTransformations.jl/blob/master/src/resizing.jl#L199) as in [PIL](
https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.resize) package of Python

**Comment by Evizero** [comment]
its certainly worth thinking about it post 0.7. AFAIK a lot of functions in base also started to use keyword arguments more casually

**Comment by ekinakyurek** [comment]
This issue was closed. Should I open a new issue on that?

**Comment by Evizero** [comment]
sure! the best place for the issue would be at https://github.com/JuliaImages/ImageTransformations.jl
