### ISSUE TITLE
Proposal: ImageDistances.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#691]
I am planning to create a package for computing distances between images to accommodate the Hausdorff distance in [distances.jl](https://github.com/JuliaImages/Images.jl/blob/master/src/distances.jl) plus other distances to be implemented in the future. In this package I would like to be compatible with the Distances.jl API.

I would like to ask you if the JuliaImages organization is a good place to host the package or if I should create it on my personal GitHub account?

**Comment by Evizero** [comment]
I feel like I have read some very similar post/conversation about a image distance package before somewhere, but I can't find anything to link to. Did you by any chance bring this idea up before somewhere?

**Comment by juliohm** [comment]
I did mention it in the past. I think at that time it was considered low priority (which I know it still is). My research is depending on these more efficient implementations of Hausdorff and pairwise evaluations similar to what Distances.jl provides. Since I will have to work on this anyways, I thought I would ask here first before I create a package on my personal account.

**Comment by timholy** [comment]
I'm fine with it being in JuliaImages if you think it might give it more visibility.

**Comment by juliohm** [comment]
Yes, I think the main benefit of having it in JuliaImages is that other people will be willing to contribute more distances in the future. If it is ok, I appreciate if you can create the repository and add me as contributor so that I can push to it.

**Comment by Evizero** [comment]
> If it is ok, I appreciate if you can create the repository and add me as contributor so that I can push to it.

I can take care of this

**Comment by Evizero** [comment]
done: https://github.com/JuliaImages/ImageDistances.jl

let me know if there is anything else. I think setting up CI should work for your normal account

**Comment by juliohm** [comment]
Thank you Christof, I will check it.
