### ISSUE TITLE
julia0.6: Exported but undefined functions(grayim, colorim, colorspace, ...)

### ISSUE THREAD

**Issue by takagiy** [JuliaImages/Images.jl#697]
When I type `gray` and press tab key, REPL displays `grayim` which is actually an undefined function as a candidate. Some symbols such as `colorim` and `colorspace` exhibit the same behavior, is this correct?
```
julia> gray
gray   grayim
julia> grayim
ERROR: UndefVarError: grayim not defined
```

**Comment by Evizero** [comment]
good catch. I think its a relic of long ago.

As far as I can tell the original function was removed with https://github.com/JuliaImages/Images.jl/commit/3c034fc9c46eb587995537642fe415253d40614a , but I suspect there was some deprecated version somewhere (?). 

Might be worth going through all the explicit exports and checking if the names still exist

**Comment by Evizero** [comment]
Right, the function was moved to `ImageCore` and marked as deprecated there. This deprecation warning was removed with https://github.com/JuliaImages/ImageCore.jl/commit/e808091ba0f774a443e39526329a31665b4d83b0 .

Seems like leaving the explicit `export` here in Images was just an accidental oversight, given that `ImageCore` is reexported.

**Comment by GobanTKG** [comment]
Thanks a lot. I looked for other relics and got 28 symbols, but I'm not sure that this check is accurate. Could I leave the fix to you?

```
julia> using Images

julia> filter(n -> ! isdefined(Images,n), names(Images))
28-element Array{Symbol,1}:
 :assert2d           
 :assert_scalar_color
 :assert_xfirst      
 :assert_yfirst      
 :colorim            
 :colorspace         
 :getindexim         
 :grayim             
 :imfilter_LoG       
 :isdirect           
 :isxfirst           
 :isyfirst           
 :limits             
 :mapinfo            
 :nchannels          
 :ncolorelem         
 :raw                
 :rerange!           
 :reslice!           
 :sc                 
 :scale              
 :separate           
 :sliceim            
 :spatialpermutation 
 :storageorder       
 :subim              
 :ufixed8sc          
 :ufixedsc
```

**Comment by aquatiko** [comment]
@Evizero This still persists!! should they be removed?

**Comment by Evizero** [comment]
yes

**Comment by aminya** [comment]
I am updating an old package ([MatlabCompat](https://github.com/aminya/MatlabCompat.jl)) that uses these functions (e.g ``raw, grayim``). What should I use instead of those?
