### ISSUE TITLE
Shouldn't complement live in Colors.jl?

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/Images.jl#698]
Small function, small issue, but seems like `complement` which acts on a color should live in `Colors.jl`.

**Comment by SimonDanisch** [comment]
I think there are a few functions, that should actually live in Colors.jl instead of Images.jl.
E.g. clamp01, reexport of N0f8 - probably more! How about we make a list, confirm that they should move and then make a PR?

**Comment by bjarthur** [comment]
`mapwindow` also strikes me as misplaced, as i often use it for time series.  seems equally suited to me to be in a signal processing package.

**Comment by yakir12** [comment]
I agree with all of that. 

Since there are currently [448](https://juliaobserver.com/packages?dependent_id=Colors) packages that depend on `Colors`, there might be some resistance to adding *any* functions to it (thus making it ever so slightly larger).

I tried to find the methods that use Color in Images by looking at the output from `methodswith(Color)` after `using Images`, but didn't get any useful result. Can you compile a list of `Images` functions that act upon types of `Colors`? 

As to `mapwindow`, yea I find myself `using Images` just for some of the filter functions there, even when I only need it for a `Vector`...

**Comment by kimikage** [comment]
BTW, if you move `complement` to another package, I think `ColorVectorSpace.jl` is more appropriate package than `Colors.jl`.

**Comment by wizofe** [comment]
I attempted a PR for both steps! Being a GSoC student; be kind ^_^

- Step 1: (PR125)[https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/125]
- Step 2: (PR)[https://github.com/JuliaImages/Images.jl/pull/879]

Thanks!
