### ISSUE TITLE
Binary images are smoothed when saved to disk

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#700]
I am not sure if that is expected behavior, but whenever I have a binary image say `eye(Bool, 100,100)` and save it to disk, I get a smoothed version:

```julia
using Images

img = eye(Bool, 100, 100)
save("foo.jpg", img)

img = load("foo.jpg")
length(unique(img)) # more than 2
```

Is there a way to save the binary image in a sharp {0, 255} set of values?

**Comment by kmsquire** [comment]
Try saving as png (or some other lossless format).  JPEG is inherently lossy, and will always introduce artifacts into images (although the effect will be minimized if you crank up the jpeg quality).

**Comment by juliohm** [comment]
Thank you @kmsquire for the quick reply, makes total sense. :)

**Comment by juliohm** [comment]
Regarding the range of values, how can we save a binary image with {0,255} instead of {0,1} values?

**Comment by juliohm** [comment]
I think I got it, the values are always normalized with N0f8 type.
