### ISSUE TITLE
Showing an Image on IJulia Notebook

### ISSUE THREAD

**Issue by ereday** [JuliaImages/Images.jl#710]
Hi,

In order to display an image on IJulia Notebook, I tried to do the following (which is shown in the documentation):
```
using ImageView
imshow(x) # where x is a type of Array{RGB}
```
However,  I get an error in using ImageView step:
```
INFO: Precompiling module ImageView.
ERROR: LoadError: error compiling anonymous: could not load library "libgtk-3"
libgtk-3.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /home/ec2-user/.julia/v0.6/Gtk/src/Gtk.jl, in expression starting on line 37
ERROR: LoadError: Failed to precompile Gtk to /home/ec2-user/.julia/lib/v0.6/Gtk.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/ec2-user/.julia/v0.6/ImageView/src/ImageView.jl, in expression starting on line 7
```

Is this the only way to display an image on IJulia ? If so, how can I fix this error ?

**Comment by Evizero** [comment]
You don't need ImageView for working in a notebook.

`using Images` should suffice, just let the image you want to display be the last element in the cell

**Comment by ereday** [comment]
Thank you for prompt reply. In my real application, I need to plot a heatmap and show an image side by side.
To plot the heatmap , I use plots.jl .  In that case,  I am not sure how the img can be the last element in the cell. Do you know any idea ?  I opened similar issue in the Plots.jl repository but couldn't hear back yet.

If I apply the snippet at below, they wont be displayed side by side
```
using Images,Plots
hinput = rand(3,4)
heatmap(input)
x 
```

**Comment by Evizero** [comment]
```
plot(
    heatmap(rand(5,4)),
    plot(img, seriestype = :image)
)
```

<img width="450" alt="screen shot 2018-03-28 at 10 14 49" src="https://user-images.githubusercontent.com/10854026/38016977-093437ee-3271-11e8-8aac-70a2f91d0dc4.png">
