### ISSUE TITLE
convert Image to Array{Float64}?

### ISSUE THREAD

**Issue by tbenst** [JuliaImages/Images.jl#715]
I read through https://juliaimages.github.io/latest/arrays_colors.html but I think I'm missing something basic:

```julia
> using TestImages
> img = testimage("mandrill")

> convert(Array{Float64}, img)
MethodError: Cannot `convert` an object of type ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.

Stacktrace:
 [1] _collect(::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}, ::Base.Generator{Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2},Type{Float64}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:488
 [2] map(::Type{T} where T, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at ./abstractarray.jl:1868
 [3] include_string(::String, ::String) at ./loading.jl:522
```

I also tried `map(Float64, img)` and `Float64.(img)` with the same error. Also, if there could be an example of how to convert an array to an Image that would be great!

Many thanks for the help!

**Comment by zygmuntszpak** [comment]
One way to create a multidimensional array of `Float64` where the third dimension corresponds to the red, green and blue channel is as follows:

```julia
using TestImages, Colors
img = testimage("mandrill")
I = Float64.(cat(3,red(img),green(img),blue(img)))
```

Another option is to create a view using `channelview`. 
```julia
using TestImages, Colors, Images
img = testimage("mandrill")
mat = channelview(img)
```

However, this creates a view with dimensions `3 x 512 x 512` where the first dimension is used to index into the red, green and blue channels.

**Comment by tbenst** [comment]
Awesome thanks! My code to read in a video is now working and you really helped my understanding, thanks so much!

```julia
function readVideo(videoPath, nframes=100)
    vid = VideoIO.openvideo(videoPath)
    img = read(vid)
    frames = zeros(ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},nframes, size(img)...)
    i = 1
    while !eof(vid)
        read!(vid,img)
        frames[i,:,:] = img
        if size(frames, 1) >= nframes
            break
        end
        i+=1
        end 
    return frames
end
frames = readVideo(videopath);
```

**Comment by Evizero** [comment]
as a side note. The main upside of `channelview` is that in general it does not need to copy/change your data; it simple reinterprets the memory in most practical cases. This is why it makes sense to have the colorchannel in the first dimension, because then RGB are right next to each other in memory and can simply be grouped. check out this article if you'd like to know more https://evizero.github.io/Augmentor.jl/images/
