### ISSUE TITLE
Padding an offset array by padarray() gives an error

### ISSUE THREAD

**Issue by suiato** [JuliaImages/Images.jl#718]
Using padarray() for an offset array gives an error, while using it for an array results in an offset array.
Is this expected? If so, what should be used to pad an offset array?

The last line below gives an error: > size not supported for arrays with axes (0:1, 0:2);
while a_o1 is OK.

```
using Images, OffsetArrays
a = [1 2 3; 4 5 6]
a_o = OffsetArray(a, -1, -1)
a_o1 = padarray(a, Fill(0, (2, 2)))
a_o2 = padarray(a_o, Fill(0, (2, 2)))
```

**Comment by zygmuntszpak** [comment]
Thanks for reporting this, that is certainly a bug. I'll work on fixing this.
