### ISSUE TITLE
Update to Julia 0.7

### ISSUE THREAD

**Issue by tawheeler** [JuliaImages/Images.jl#726]
Images.jl (or perhaps its dependencies) currently fail to load and pass tests on Julia 0.7 (technically beta 2). Love the Images package and it is critical for my stuff. Would be great to be able to use it on 0.7.

**Comment by rdeits** [comment]
It's happening, don't worry. There has already been a ton of work done to bring the dependencies up to 0.7, but there's still more to do. If you want this to happen faster, hop on the `#upgradathon` channel on the [Julia Slack](https://slackinvite.julialang.org/) and people there can help direct you to whatever the currently blocking packages are.

**Comment by tawheeler** [comment]
Sweet, thanks @rdeits

**Comment by rsrock** [comment]
I just ran `@oxinabox`'s test script, found here: https://discourse.julialang.org/t/script-to-find-which-of-your-dependencies-is-not-working-in-julia-0-7/11528.  Looks manageable.

```
----------------------------------------------------------------------
Failing Dependency Tree  for Images
----------------------------------------------------------------------
Images
	ImageCore
	ImageTransformations
		ImageCore
		IdentityRanges
		ShowItLikeYouBuildIt
	ImageFiltering
		ImageCore
		CatIndices
			CustomUnitRanges
		FFTViews
			CustomUnitRanges
		ComputationalResources
	AxisArrays
	ImageAxes
		ImageCore
		AxisArrays
	ImageMetadata
		IndirectArrays
		ImageCore
		ImageAxes
			ImageCore
			AxisArrays
	IndirectArrays
	SIUnits
		TexExtensions
----------------------------------------------------------------------
```

**Comment by rsrock** [comment]
As of right now:
```
----------------------------------------------------------------------
Failing Dependency Tree  for Images
----------------------------------------------------------------------
Images
	ImageTransformations
		ShowItLikeYouBuildIt
	ImageFiltering
		CatIndices
		FFTViews
	AxisArrays
	ImageAxes
		AxisArrays
	ImageMetadata
		ImageAxes
			AxisArrays
	SIUnits
		TexExtensions
----------------------------------------------------------------------
```

ShowItLikeYouBuildIt should be replaced by Base.showarg().  We also should probably switch to Unitful instead of SIUnits.  That's probably a breaking change, but since everything is breaking anyway right now, no better time than the present.

**Comment by damiendr** [comment]
Looks like `CatIndices#master` already passes all tests; `FFTViews` has one error that's not obvious to me (incorrect results); `AxisArrays` will need more work because of name clash with new `Base.axes`. But it seems that neither `AxisArrays` nor `ImageAxes` are required for core functionality — could these be fully decoupled and removed from `Images`'s `REQUIRE`?

**Comment by leo60228** [comment]
AxisArrays now supports 1.0.

**Comment by leo60228** [comment]
So does FFTViews; perhaps Images.jl is the only things still needing to be updated?

**Comment by Evizero** [comment]
Actually Images.jl has been updated for a while now. so this can  be closed
