### ISSUE TITLE
Update to 1.0

### ISSUE THREAD

**Issue by ikshv** [JuliaImages/Images.jl#730]
Julia 1.0,  latest Mac OS, after successfully adding and building Images, 
`using Images` 
leads to

[ Info: Precompiling Images [916415d5-f1e6-5110-898d-aaa5f9f070e0]
WARNING: could not import Base.atan2 into Images
WARNING: could not import Base.ctranspose into Images
WARNING: could not import Base.fft into Images
WARNING: could not import Base.ifft into Images
WARNING: could not import Base.linearindexing into Images
WARNING: could not import Base.mimewritable into Images
WARNING: could not import Base.showcompact into Images
WARNING: could not import Base.squeeze into Images
WARNING: could not import Base.atan2 into ColorVectorSpace
ERROR: LoadError: UndefVarError: ctranspose not defined
ERROR: LoadError: Failed to precompile ImageCore

**Comment by SilvesterHsu** [comment]
Same issue

**Comment by Evizero** [comment]
Images is not updated yet, but its being worked on. see also #727

**Comment by zygmuntszpak** [comment]
Images works on 1.0 so closing this issue.
