### ISSUE TITLE
Proposal: move color types to ColorTypes.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#731]
Dear all,

Could we move these const definitions in the Images.jl source to ColorTypes.jl?

```julia
const AbstractGray{T}                    = Color{T,1}
const TransparentRGB{C<:AbstractRGB,T}   = TransparentColor{C,T,4}
const TransparentGray{C<:AbstractGray,T} = TransparentColor{C,T,2}
```

I am having difficulties to port many packages because of the current fragmentation of concepts in the project. Please let me know if that makes sense or if these types are just meant to be used for tests.

**Comment by Evizero** [comment]
I am guessing those started out as little helpers, but then people saw them and used them because they thought these come from ColorTypes (myself included, funny enough).

I think there is a case for moving them

**Comment by juliohm** [comment]
I will work on it when I find some time :+1:

**Comment by juliohm** [comment]
These definitions are already in ColorTypes.jl, and also in Colors.jl. We definitely need to clean things up and be more picky reviewing PRs in the future to avoid reintroducing similar fragmentation. I will submit a PR to Images.jl and a PR to Colors.jl.

**Comment by juliohm** [comment]
Relevant PRs:

- ColorTypes.jl: https://github.com/JuliaGraphics/ColorTypes.jl/pull/111
- Colors.jl: https://github.com/JuliaGraphics/Colors.jl/pull/320

**Comment by juliohm** [comment]
This one is fixed, closing it :+1:
