### ISSUE TITLE
imresize throw StackOverflowError with sz of array type

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#742]
The document of `imresize` doesn't say sz must be `Tuple` type, so I just try the MATLAB way of using `imresize`, and it throws an unexpected StackOverflowError.

```julia
using Images, TestImages
lena = testimage("lena_gray_256")

imresize(lena, (128,128)) # work as expected
imresize(lena, [128,128]) # throw StackOverflowError
```

**Comment by Evizero** [comment]
Good catch!. At the very least this should throw a more informative error.

looks like the culprint is https://github.com/JuliaImages/ImageTransformations.jl/blob/master/src/resizing.jl#L171

**Comment by Evizero** [comment]
this is a issue in ImageTransformations.jl, so I will close the issue here.

**Comment by johnnychen94** [comment]
Well, it looks like the document is not clear enough to me, on what argument type should be, and what `inds` is...

I think it should be something like
```julia
imresize(img, sz::Tuple{T}) where T <: Integer -> imgr
imresize(img, ind1::T, ind2::T, ...) where T <: Integer -> imgr
```
