### ISSUE TITLE
reimplement imROF

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#755]
https://github.com/JuliaImages/Images.jl/blob/582e1130189ffd42d4270ae1648b0886e48e6999/src/algorithms.jl#L614
If I'm not confusing, the current implementation uses the **Algorithm 1** in 
> Getreuer, P. (2012). Rudin-Osher-Fatemi total variation denoising using split Bregman. Image Processing On Line, 2, 74-95.

In the same paper, there's a split-bregman implementation, which is a more robust and widely-used algorithm.
> Goldstein, T., & Osher, S. (2009). The split Bregman method for L1-regularized problems. SIAM journal on imaging sciences, 2(2), 323-343.

I'm going to reimplemente this `imROF` with split-bregman iteration @timholy . To do this, a `psf2otf` function is needed to accelerate the computation(PR: https://github.com/JuliaImages/ImageFiltering.jl/pull/81)

**Comment by johnnychen94** [comment]
https://github.com/JuliaImages/Images.jl/blob/582e1130189ffd42d4270ae1648b0886e48e6999/src/algorithms.jl#L563

@timholy There're five helper functions to implement current `imROF` here. May I change/delete this when I do my own implementations?

As a simple test, I reimplemented my version of ROF_gradientdescent(by changing this), which is 5~10x faster than the current one.

For example, one of the changes is
```julia
function forwarddiffx(u::AbstractMatrix) # ∇x
    out = similar(u)
    out[:, 2:end] = u[:, 2:end] - u[:, 1:end-1]
    out[:, 1] = u[:, 1] - u[:, end]
    return out
end
```

**Benchmark**

```julia
julia> @time imdenoise(noisy_img,N=500);
19.789209 seconds (36.89 k allocations: 27.350 GiB, 35.50% gc time)
julia> @time imROF(noisy_img,1e-3,500);
106.927849 seconds (1.33 G allocations: 40.441 GiB, 20.57% gc time)
```

BTW, do we have `psnr`/`ssim` implemented in Images? If not, I might help doing this.

**Comment by timholy** [comment]
Changing the *algorithm* is perfectly fine. Changing the *result* would require some kind of deprecation strategy. Or if you want to add circular boundary conditions as an option, we could follow the model of ImageFiltering.

**Comment by johnnychen94** [comment]
@timholy are you available these days to implement the `psf2otf` and `otf2psf` utils? 😄

**Comment by timholy** [comment]
Sure. Keep in mind that unless you want to change sizes, `psf2otf` is just called `fft` :smile: :

```julia
julia> using ImageFiltering

julia> kern = Kernel.gaussian(2)
OffsetArray(::Array{Float64,2}, -4:4, -4:4) with eltype Float64 with indices -4:4×-4:4:
 0.000763447  0.00183141  0.00342153  …  0.00342153  0.00183141  0.000763447
 0.00183141   0.00439334  0.00820783     0.00820783  0.00439334  0.00183141 
 0.00342153   0.00820783  0.0153342      0.0153342   0.00820783  0.00342153 
 0.0049783    0.0119423   0.0223112      0.0223112   0.0119423   0.0049783  
 0.00564116   0.0135324   0.0252819      0.0252819   0.0135324   0.00564116 
 0.0049783    0.0119423   0.0223112   …  0.0223112   0.0119423   0.0049783  
 0.00342153   0.00820783  0.0153342      0.0153342   0.00820783  0.00342153 
 0.00183141   0.00439334  0.00820783     0.00820783  0.00439334  0.00183141 
 0.000763447  0.00183141  0.00342153     0.00342153  0.00183141  0.000763447

julia> using FFTW

julia> fft(kern)
9×9 Array{Complex{Float64},2}:
         1.0+0.0im          …     0.310249-0.26033im    
    0.310249+0.26033im            0.164026-1.38778e-17im
  0.00174698+0.00990761im       0.00312125+0.00261904im 
 -0.00254613+0.00441003im      0.000358128+0.00203104im 
  0.00133217-0.000484872im     0.000287079-0.000497236im
  0.00133217+0.000484872im  …  0.000539532-0.000196374im
 -0.00254613-0.00441003im        -0.001938-0.000705374im
  0.00174698-0.00990761im      -0.00203725-0.00352862im 
    0.310249-0.26033im           0.0284829-0.161534im   
```

That's because we can have arbitrary axes, which is not supported in Python & Matlab.

**Comment by johnnychen94** [comment]
Thanks! `psf2otf` is used here to accelerate the iteration incorporating with the convolution theorem, and changing sizes is needed to do element-wise multiplication.

```julia
# split-bregman iteration, aka ADMM
∇x = psf2otf([1,-1],size(clean_img))
∇y = psf2otf([1;-1],size(clean_img))
∇T∇ = abs(∇x).^2+abs(∇y).^2

d1 = 0*u0; b1 = d1; 
d2 = d1; b2 = d2;
u = u0;
λ = 0.05; μ = 0.05;

for iter=1:200
    Nomin = λ*u0 + μ*(backdiffx(d1-b1)+backdiffx(d2-b2));
    Denom = λ + μ*∇T∇;
    u = real(ifft2(fft2(Nomin)./Denom));
    
    [d1,d2] = shrink2(Dx(u)+b1,Dy(u)+b2,1./mu);
    b1 = b1+Dx(u)-d1;
    b2 = b2+Dy(u)-d2;
end
```

**Comment by timholy** [comment]
I guess a key question is whether we want to target numerical applications or physical concepts. From a conceptual standpoint, the OTF is a *function* of frequencies that have physical units: e.g., if your pixels have 1mm spacing then the highest frequency in your OTF is 0.5/mm. Should we return this as an `AxisArray`? ImageFiltering currently doesn't depend on AxisArrays, but Images does, so it could be implemented here (ref https://github.com/JuliaImages/ImageFiltering.jl/pull/81).

Perhaps an alternative would be to return the AxisArray only if the input has AxisArray-axes.

**Comment by timholy** [comment]
Another question: would you rather use `rfft` and `irfft` rather than `fft`/`ifft`?

**Comment by johnnychen94** [comment]
> Another question: would you rather use rfft and irfft rather than fft/ifft?

`rfft` and `irfft` are great! I wasn't aware of them until now.

> `ImageFiltering` currently doesn't depend on `AxisArrays`, but `Images` does, so it could be implemented here

I guess `ImageFiltering` is more appropriate, even if we implement it here in `Images`, we might move it to `ImageFiltering` eventually since `Images` is quite a huge dependency.

**Comment by timholy** [comment]
OK, let's start with a "numeric" implementation and add others as needed.

**Comment by johnnychen94** [comment]
closed by https://github.com/JuliaImages/ImageFiltering.jl/pull/233
