### ISSUE TITLE
segfault after importing CSV and Images, PyPlot from a separate module

### ISSUE THREAD

**Issue by MaxandreJ** [JuliaImages/Images.jl#759]
Hi,

I get the following segfault
```
signal (11): Segmentation fault: 11
in expression starting at /MyProjectDirectory/Test.jl:4
_platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
```

when I run `/MyProjectDirectory/Test.jl` which contains the code
```
push!(LOAD_PATH, "/MyProjectDirectory")
import CSV
using MyModule
```

that uses `/MyProjectDirectory/MyModule.jl` which contains the code
```
module MyModule
using Images
import PyPlot
end
```

I don't know if this is an issue to do with CSV, Images, PyPlot or Julia itself. This is a minimal working example. I'm using Julia 1.0.1 on MacOS Mojave. The segfault goes away if I don't load any one of these three packages. There is still a segfault if I start Julia with `--check-bounds=yes`.

I hope this can be resolved soon! Segfaults are frightening...

These are the versions of the packages in question + important dependencies
```
Images v0.16.0
PyCall v1.18.5+ #Master (https://github.com/JuliaPy/PyCall.jl.git)
PyPlot v2.6.3
CSV v0.4.1
```

I have also posted this issue on the [`PyPlot.jl` github](https://github.com/JuliaPy/PyPlot.jl/issues/402) and the [`CSV.jl` github](https://github.com/JuliaData/CSV.jl/issues/328).

Best,
Max

**Comment by timholy** [comment]
Can you replicate this without defining a package? I.e., on the REPL? (I can't, just by `using` the 3 packages.)

**Comment by MaxandreJ** [comment]
Hi @timholy and thank you for your answer!
No, there's no segfault if I just run
```
import CSV
using Images
import PyPlot
```
The segfault only happens in the case that I explain in the first post in this thread.

**Comment by ronisbr** [comment]
I am having this same problem when building Cairo (https://github.com/JuliaGraphics/Cairo.jl/issues/271).

I think this can be some incompatibility between Julia and Mojave.

**Comment by johnnychen94** [comment]
FWIW, I no longer see this by trying https://github.com/JuliaPy/PyPlot.jl/issues/402#issuecomment-431214656 in Julia 1.6.0 with macOS BigSur

```julia
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```
