### ISSUE TITLE
move `difftype` to ImageCore

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#765]
Can we move
`difftype` and etc. in
https://github.com/JuliaImages/Images.jl/blob/6b7048a52b8bf9058eefa0b238a4f138c895c983/src/algorithms.jl#L291-L311
to other places such as `ImageCore`

These are very basic helpers to handle different value types, seems not belong here.

I find these really useful to avoid `N0f8` overflow issue (https://github.com/JuliaImages/ImageCore.jl/issues/63) when implement new algorithms.

**Comment by timholy** [comment]
Yes, it's a good idea to move "trait functions" to ImageCore.

**Comment by johnnychen94** [comment]
What should I do then? I haven’t done this kind of work before, not very clear about the “routine” work.

**Comment by Evizero** [comment]
They aren't exported so it should luckily be an easier case of moving functions upstream.

1. copy the functions and their unit tests to ImageCore (in a PR)
2. We'll merge the PR in ImageCore and tag a version.
3. remove them from Images.jl and instead write `using ImageCore: difftype, accumtype, graytype` somewhere sensible. Make sure to also bump the ImageCore version in REQUIRE to the new version above.
4. We'll merge the PR in Images and tag a new version
5. done

**Comment by johnnychen94** [comment]
I'd like to rename the `difftype` to make it more meaningful. Any recommendations?

**Comment by zygmuntszpak** [comment]
Could you guys please clarify what `difftype` is supposed to do? In what context is it used and to what purpose?

**Comment by johnnychen94** [comment]
I used it in my recent PR [here](https://github.com/JuliaImages/ImageDistances.jl/pull/6)

This is useful because according to the nature of `minkowski`, it makes sense to convert everything to `Float` type, so that there's no need to write too many one-line methods to capture all the possible combination of types of input arguments.

```julia
"""
    minkowski_p(imgA, imgB, metric::Minkowski)

minkowski distance to p-th power
"""
function minkowski_p(imgA::AbstractArray, imgB::AbstractArray, metric::Minkowski)
    T = promote_type(difftype(eltype(imgA)), difftype(eltype(imgB))) # Normed -> Float
    imgA = channelview(convert.(T, imgA))
    imgB = channelview(convert.(T, imgB))
    if metric.order == 2
        return reduce(+, abs2.(imgA[:] .- imgB[:]))
    end
    return reduce(+, abs.(imgA[:] .- imgB[:]) .^ metric.order)
end
```

In this case, it would be nice to implement a specialized `minkowski_p` that returns a `N0f8`. However, to be honest there's really low priority -- implementation of these do easily makes all the codes a chaos even for a simple algorithm like this.

Personally, I want to make my ideas implemented fast by writing a generic function using `channelview` and `difftype`, and then optimize it for `Normed` type if I do have this need.

**Comment by zygmuntszpak** [comment]
Perhaps we should rename `difftype` to `widen_type`?

Other ideas:
1. `grow_type`
2. `expand_type`
3. `extend_type`

**Comment by timholy** [comment]
The intent was that `difftype` differs in principle from "plain widening" in that it promises to handle signed arithmetic correctly. For example, you might widen `0xfe` and `0xff` to `0x00fe` and `0x00ff`, respectively, but that widening not be useful if you wanted to compute a sum-of-absolute-differences:

```julia
julia> 0xfe - 0xff
0xff

julia> 0x00fe - 0x00ff
0xffff
```

**Comment by johnnychen94** [comment]
done in #839 `Images v0.19.0`
