### ISSUE TITLE
Do we need to put `channelview` in function implementations whenever necessary?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#766]
This makes me a little confused.

Say we need to implement a `psnr(imgA, imgB)` for `Gray` and `RGB` images, we have two way providing the APIs.

Option 1: no prior knowledge for `Colorant`

```julia
function psnr(imgA::AbstractArray, imgB::AbstractArray)
# implementation
end

# call:
imgA = testimage("lena_color_256"); imgB = copy(imgA);
psnr(channelview(imgA), channelview(imgB)) # works fine if 3-D array is supported
psnr(imgA, imgB) # hope everything works as expected; or throw `MethodError`
```

Option 2: use `channelview` for whatever AbstractArray and whenever necessary
```julia
function psnr(imgA::AbstractArray, imgB::AbstractArray)
imgA = channelview(imgA);
imgB = channelview(imgB);
# implementation

# use colorview if needs to return an image
end

# call:
imgA = testimage("lena_color_256"); imgB = copy(imgA);
psnr(imgA,imgB) # works fine
psnr(channelview(imgA), channelview(imgB)) # works fine
```

Some functions in Images take Option 2 [entropy](https://github.com/JuliaImages/Images.jl/blob/6b7048a52b8bf9058eefa0b238a4f138c895c983/src/algorithms.jl#L143), most takes Option 1.

Personally, I prefer Option 2 for whatever `AbstractArray` unless there are performance requirements since it makes everything consistent.

One more question, If we take Option 1, and when some basic functions are not supported for `RGB`( e.g., `Ones(RGB, 3,3)`), then what should I blame on. Should we add more supports on RGB, or should we adjust our codes to handle this (in this example, we use `channelview`)?

**Comment by zygmuntszpak** [comment]
[Quoting Wikipedia](https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio)
> For color images with three RGB values per pixel, the definition of PSNR is the same except the MSE is the sum over all squared value differences divided by image size and by three. Alternately, for color images the image is converted to a different color space and PSNR is reported against each channel of that color space, e.g., YCbCr or H

Hence, I would do something like this: 

```julia
function psnr(imgA::AbstractArray, imgB::AbstractArray)
    # implementation where  MSE is the sum over all squared value differences divided by image size and by the number of 'channels/slices'
end

function psnr(imgA::AbstractArray{T}, imgB::AbstractArray{T}) where {T<:AbstractRGB} 
    psnr(channelview(imgA), channelview(imgB))
end

# PSNR is reported against each channel of that color space.
function psnr(imgA::AbstractArray{T}, imgB::AbstractArray{T}) where {T<:Color3} 
    slicesA = channelview(imgA)
    slicesB = channelview(imgB)
    psnr_1 = psnr(@view slicesA[1,:,:], @view slicesB[1,:,:])
    psnr_2 = psnr(@view slicesA[2,:,:], @view slicesB[2,:,:]) 
    psnr_3 = psnr(@view slicesA[3,:,:], @view slicesB[3,:,:])  
    psnr_1, psnr_2, psnr_3
end
```

Actually, it is probably possible to write that last function using `map` or `zip` to map `psnr` over a view of each possible channel (thereby generalizing beyond 3 slices).  I attempted something but it ended up constructing and array as a result rather than a tuple.

**Comment by johnnychen94** [comment]
@zygmuntszpak thanks for the explaination. However, this doesn't completely solve my problem because `Gray` is likely not supported for new functions( despite of the `psnr` example)

See this toy example
```julia
julia> using Colors, TestImages, FixedPointNumbers, ImageCore

julia> foo(::Normed) = println("gotcha!")
foo (generic function with 1 method)

julia> img = testimage("came");

julia> function bar(img::AbstractArray)
       foo(img[1])
       end
bar (generic function with 1 method)

julia> bar(img)
ERROR: MethodError: no method matching foo(::Gray{Normed{UInt8,8}})
Closest candidates are:
  foo(::Normed) at REPL[2]:1
Stacktrace:
 [1] bar(::Array{Gray{Normed{UInt8,8}},2}) at ./REPL[4]:2
 [2] top-level scope at none:0

julia> bar(channelview(img))
gotcha!
```

---

Let me restate my problem:

**Option 1**: there are at least four methods needed to write a reliable & robust `psnr` function
```julia
psnr(::AbstractArray, ::AbstractArray)
psnr(::AbstractArray{<:Normed}, ::AbstractArray{<:Normed})
psnr(::AbstractArray{<:AbstractGray}, ::AbstractArray{<:AbstractGray})
psnr(::AbstractArray{<:AbstractRGB}, ::AbstractArray{<:AbstractRGB})

# and perhaps even more
psnr(::AbstractArray{<:Normed}, ::AbstractArray)
psnr(::AbstractArray, ::AbstractArray{<:Normed})

psnr(::AbstractArray{<:AbstractGray}, ::AbstractArray)
psnr(::AbstractArray, ::AbstractArray{<:AbstractGray})
```

if we implement new functions following **Option 1**, it would be very likely to forget writting wrappers for some special types.

**Option 2**: there are only one method needed to write

the usage of `channelview` and `difftype` <https://github.com/JuliaImages/Images.jl/issues/765> makes it possible to write one function to handle all these possibilities ( if there is no need to write specialized version)
```julia
function psnr(imgA::AbstractArray, imgB::AbstractArray)
   T = promote_type(difftype(eltype(imgA)), difftype(eltype(imgB))) # N0fx -> Float
   imgA = channelview(convert.(T, imgA))
   imgB = channelview(convert.(T, imgA))
   # implementation
end

# if we don't want specialized implementation for `Normed` value
# then the following one is unnecessary
function psnr(imgA::AbstractArray{<:Normed}, imgB::AbstractArray{<:Normed})
   imgA = channelview(imgA)
   imgB = channelview(imgB)
   # implementation
end
```

---

Another related question is that I actually don't know how many input types needed to be supported if I want to write a new function.
```julia
# are all of these need to be supported as long as it make sense?
foo(AbstractArray)
foo(AbstractArray{<:Normed})
foo(AbstractArray{<:AbstractRGB})
foo(AbstractArray{<:AbstractGray})
```

**Comment by timholy** [comment]
`psnr(A, B) = 10*log10(length(A) / ssd(A, B))`. I think that's all there is to it.

More generically, design-wise you're better off implementing the "high level" functions in terms of low-level operations that generalize across datatypes. If you load `ColorVectorSpace`, `abs2` is ready-made for both numbers, grayscale, and AbstractRGB.

**Comment by johnnychen94** [comment]
As a conclusion to this issue, unless it has explicit meaning (e.g., psnr of RGB images), we don't need to split pixels into different channels. 

[array elements are pixels](https://juliaimages.org/latest/quickstart/#Array-elements-are-pixels-(and-vice-versa)-1)

Sticking to old conventions in other languages would make things much harder.

Related issue:

https://github.com/JuliaImages/ImageCore.jl/issues/77
