### ISSUE TITLE
GSoC mentors & JuliaImages hackathon

### ISSUE THREAD

**Issue by timholy** [JuliaImages/Images.jl#771]
If you have a project idea for GSoC, now is the time to come forward and submit a pull request (see https://github.com/JuliaLang/www.julialang.org/tree/master/soc and https://julialang.org/soc/projects/images.html). With Julia now stable, I think now is the time to try to flesh out JuliaImages into an ecosystem that can compete with any other. If you have identified missing pieces, it would be great to suggest as a project and be willing to mentor a student through it. Some of my wish-list items:

- a comprehensive set of visual demos, as with http://scikit-image.org/docs/stable/auto_examples/ (and filling in anything that we discover to be missing while trying to create similar demos)
- a set of benchmarks comparing against at least scikit-image and OpenCV (matlab might be nice too)
- GPU support in algorithms

I can't mentor all of these, so help from other contributors would be appreciated. And of course I don't have expertise in many areas, so there are surely many places that need improvement that don't affect my daily work but would help the wider community.

This may also be a good time to mention that I'm trying to get some funding together to help support a JuliaImages hackathon, as a "satellite meeting" before the next JuliaCon. No promises it will happen, but if you're an established contributor you may get an invitation, so if interested please pencil it in on your calendar once dates for JuliaCon are set. Hopefully we could get a set of core contributors and GSoC students together, and in a couple of days make some big decisions and write a bunch of code.

**Comment by johnnychen94** [comment]
I'd like to do part of the "a comprehensive set of visual demos" work when I passed my PhD qualification exam.  (ETA: later March or early April) Some work I've done is re-implementing examples in [Digital Image Processing, Gonzalez](https://github.com/johnnychen94/Digital-Image-Processing-Gonzalez)

@timholy Where should I create a PR at? [juliaimages.github.io](https://github.com/JuliaImages/juliaimages.github.io) or a new repo? If it's the latter case, can you help to initialize a repo for this. It would be the best if you can provide a template I can work on.

**Comment by johnnychen94** [comment]
Some updates to the wish-list:

* With multi-threads supported in julia v1.3, algorithm acceleration with that is definitely worth doing.
* "a comprehensive set of visual demos" can now be powered by my mini project [DemoCards.jl](https://github.com/johnnychen94/DemoCards.jl)
* [Zygote.jl](https://github.com/FluxML/Zygote.jl) makes Julia a differentiable programming language, any project that combines the power of FluxML and JuliaImages would be lovely! For example, https://github.com/FluxML/Flux.jl/issues/326, [differentiable SSIM loss criterion](https://github.com/Po-Hsun-Su/pytorch-ssim).

**Comment by johnnychen94** [comment]
This issue list is a little bit outdated so I'm closing it.
