### ISSUE TITLE
gaussian_pyramid produces artifacts (black pixels)

### ISSUE THREAD

**Issue by rapus95** [JuliaImages/Images.jl#773]
http://juliaimages.github.io/latest/function_reference.html#Images.gaussian_pyramid

Original: 
![railroad 1](https://user-images.githubusercontent.com/5960902/50160414-960b6a00-02d9-11e9-8e8d-605c3c669e46.JPG)

Executing `G = gaussian_pyramid(pic, 5, 2, 1); imshow(G[1])`
results in:
![tmp](https://user-images.githubusercontent.com/5960902/50160505-d4088e00-02d9-11e9-8ac3-e48716349388.jpg)

See the black pixels at the left end of the train.

**Comment by zygmuntszpak** [comment]
Thanks for reporting this. I tried to reproduce this on a windows machine but couldn't---it works correctly for me. Hence, I have a couple of questions:

1.  If you inspect the underlying matrix at the coordinates where you see the artifacts, what values do you have there?
2. Do you see these artifacts at all levels of the pyramid?
3.  How did you save this image? Did you make a screenshot or actually write it to file?

**Comment by rapus95** [comment]
![image](https://user-images.githubusercontent.com/5960902/50221776-8d2c9e00-0396-11e9-94d0-468045b5db5d.png)
(At the lower left of the picture there're the values for one of the "black" pixels)
2. Yes I do see them for all levels
3. Artifacts are there both in file (save function) as well in screenshots

**Comment by zygmuntszpak** [comment]
Thanks. A few further questions come to mind.

What operating system are you running and what version of Julia and Images package? 

Does this happen for other images too? If you resize the image before you do the Gaussian pyramid does it still happen (I noticed the image is quite high resolution)?

If you convert the image to gray before doing the Gaussian pyramid does it still happen?

**Comment by rapus95** [comment]
Win 10 Pro
```
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

```
(v1.0) pkg> status
    Status `C:\Users\necka\.julia\environments\v1.0\Project.toml`
  [c52e3926] Atom v0.7.11
  [5789e2e9] FileIO v1.0.4
  [6218d12a] ImageMagick v0.7.1
  [86fae568] ImageView v0.8.2
  [916415d5] Images v0.17.0
  [90137ffa] StaticArrays v0.10.0
  [1986cc42] Unitful v0.13.0
```

I've got another picture where the focus is in the front area. There I get even more artifacts:
![image](https://user-images.githubusercontent.com/5960902/50223542-d0d5d680-039b-11e9-9226-128b92116507.png)

Even heavy resizing results in similar artifacts:
![image](https://user-images.githubusercontent.com/5960902/50223965-e0095400-039c-11e9-90b9-221ac912961e.png)

Converting to gray before doing the pyramid results in the same artifacts.

**Comment by rapus95** [comment]
Btw doing it manually:
```
function localsum(layer, i,j, sizeX, sizeY)
    su = zero(Float32)
    validIndices = Array{Tuple{Int, Int},1}()
    for m=-sizeX:sizeX, n=-sizeY:sizeY
        if checkbounds(Bool, layer, 2i-1+m, 2j-1+n)
                push!(validIndices, (m,n))
        end
    end
    KER = Kernel.gaussian((1,1), (2sizeX+1, 2sizeY+1))
    quot = zero(Float32)
    for (m,n) in validIndices
        su += KER[m,n]*layer[2i-1+m, 2j-1+n]
        quot += KER[m,n]
    end
    return su/quot
end
```
results in the same artifacts.

**Comment by rapus95** [comment]
Original files can be taken from there: https://www.heliconsoft.com/images/animation/Railroad_model_Enrico_Curschellas/Enrico_Curschellas.html

**Comment by rapus95** [comment]
Found the problem... Entirely my fault. Thanks for investigating, sorry for wasting your time 🤦‍♂️
(Bug was that somewhere I have difference pictures and to be able to view them I did `+1 mod 1` which resulted in 0s where should be ones...)
