### ISSUE TITLE
Contribute to JuliaImages through GSoC 2019

### ISSUE THREAD

**Issue by Deepank308** [JuliaImages/Images.jl#774]
Hello All,
I am Deepank Agrawal, a 2nd year undergrad. student at Indian Institute of Technology Kharagpur, India.
I am very much interested in contributing to JuliaImages as my GSoC 2019 project. I propose to work on implementing Image Processing and Computer Vision algorithms in Julia language. Can also contribute on any other interesting related idea. I have some experience with Image Processing and Computer Vision in OpenCV with Python and C++. Currently, I am learning how to use Julia. How should I start with the project? Please help @zygmuntszpak @timholy 
Thank you.

**Comment by timholy** [comment]
Welcome Deepank! We'd love to have you. The best place to learn about what's available is at https://juliaimages.org/latest/. I'd then suggest playing around with some demos in an area related to your interests. As far as building towards a GSoC project goes, there could be two outcomes of that:

- if everything works as you hoped, you could write it up as a demo and contribute it to the Demonstrations page. (One thought is to mimc demos available in other languages, e.g., scikit-image.)
- you might discover some missing or broken functionality, in which case working to develop the needed functionality/fixes would be great

Either of these would let you get your feet wet with regards to contributing to the ecosystem. I look forward to seeing what you come up with!

**Comment by Deepank308** [comment]
I was going through the JuliaImages GitHub. I found ImageTracking.jl to currently have only two algorithms implemented. I have a keen interest in contributing to tracking package. I also have a good interest in Stereo matching and will love to contribute to it too! So, how should I start with them? 
ping @timholy @zygmuntszpak

**Comment by zygmuntszpak** [comment]
Hi  Deepank,

thanks for your interest and enthusiasm. We could certainly use your help with the `ImageTracking.jl` package. For example, there is a rough outline of a `MedianFlow` implementation which was written for `Julia 0.6` which needs to be brought up-to-date and probably refactored considerably. You could use the current pull-request for `MedianFlow` as a basis for a new implementation. Having said that, I think that the `MedianFlow` algorithm is relatively complicated and may not be the best thing to start with if you are new to Julia. 

My suggestion is that you start by contributing some convenience functions.  For example, in the README file I have a few lines of code which produce a visualisation of dense flow vectors in HSV space. That functionality should go into its own function in some kind of `utility.jl` file. 

There is also currently no convenience function for computing the error between the ground-truth flow and the estimated flow. There are a few standard ways of comparing the error in the literature, so you might start by implementing a few of those.

It would also be very helpful to have some way of plotting the flow vectors as a `quiver` plot. Perhaps there is a way to do this with the `Makie.jl` package. I haven't had time to investigate this and would appreciate it very much if you could figure out how to do this and perhaps write a convenience function for that as well.

**Comment by Deepank308** [comment]
@zygmuntszpak I was going through the ways of computing the errors between the ground-truth flow and the estimated flow, I came across 4 such standard ways(as mentioned [here](http://vision.middlebury.edu/flow/eval/)) namely: 1) endpoint error, 2) angle error, 3)  interpolation error, 4) normalized interpolation error. I read [here](https://stackoverflow.com/questions/49699739/what-is-endpoint-error-between-optical-flows) that endpoint error estimation is used mainly for Computer Vision tasks while the interpolation error is used in video encoding. So, I should only implement endpoint error and angle error, right?

**Comment by Deepank308** [comment]
I am applying for Google Summer of Code 2019 in JuliaImages. I have prepared the first draft of my proposal. Here is the link to the [proposal](https://docs.google.com/document/d/1mrqCMOzSwj9Fom-PaD68OLKJ8T4SLHd7-3DLZT2jLSU/edit?usp=sharing). I’m still deciding about the timeline. I request all the developers to kindly take some of their valuable time to review it and suggest changes. Any feedback regarding the proposal is welcomed and will be highly appreciated.
Ping @timholy @zygmuntszpak @juliohm

**Comment by johnnychen94** [comment]
Hi, I found this in https://julialang.org/soc/guidelines/, not sure if you’re aware of this, but I think it’s worth pointing out.

> Our organization does not have page or formatting requirements, but we recommend building a formal PDF document of less than 10 pages which is formatted using Word or LaTeX.

**Comment by Deepank308** [comment]
Thanks @johnnychen94 for sparing some time to have look into it!! 
I have already aware of the guidelines, but unfortunately was unable to compress it within 10 pages or so. 

BTW previous year proposals(which I have seen) were also quite lengthy(~20 pages) so I don't think there will be a problem with the length.

Thanks for the compliment btw!!
