### ISSUE TITLE
Watershed algorithm results 

### ISSUE THREAD

**Issue by rand5** [JuliaImages/Images.jl#776]
Is there a step missing in the Watershed example from the docs? The end result that I'm getting looks more like a voronoi diagram and doesn't seem to match the segmented image shown in the docs.

![image](https://user-images.githubusercontent.com/17629404/50728648-40b5c200-10fb-11e9-8a91-73d9e4703c65.png)

**Comment by tejus-gupta** [comment]
You need to mask the background region that isn't part of the coins.

```
using Images, ImageSegmentation
img = load(download("http://docs.opencv.org/3.1.0/water_coins.jpg"));
bw = Gray.(img) .> 0.5;
dist = 1 .- distance_transform(feature_transform(bw));
markers = label_components(dist .< -15);
segments = watershed(dist, markers);

using ImageView, Random
function get_random_color(seed)
    Random.seed!(seed)
    rand(RGB{N0f8})
end
imshow(map(i->get_random_color(i), labels_map(segments).*(1 .-bw)))
```
