### ISSUE TITLE
restrict doesn't shrink by a factor of 2

### ISSUE THREAD

**Issue by rapus95** [JuliaImages/Images.jl#780]
For me this somewhat looks strange. Since `8 = 2^3` I expected this to restrict to `4x4`.

```julia
julia> size(restrict(rand(8,8)))
(5, 5)
```

**Comment by timholy** [comment]
`restrict` (and its "inverse," `prolong`) satisfy an adjointness relationship known as the Galerkin condition. The resulting operator is smoother and more symmetric than 2x2 binning. I haven't read it in detail, but https://ocw.mit.edu/courses/mathematics/18-086-mathematical-methods-for-engineers-ii-spring-2006/readings/am63.pdf seems decent.

The case of an even number of data points is not widely treated in the multigrid literature. The obvious approach is to have the prolongation operator do interpolation at 1/4 and 3/4 points grid points; from the adjoint condition the restriction operator follows directly.
