### ISSUE TITLE
Writing a more descriptive README.md and other related files to get started

### ISSUE THREAD

**Issue by salilmishra23** [JuliaImages/Images.jl#781]
I think having a descriptive README.md allows a new user to get most of the important details in one go. 
We do provide this information in the docs(https://juliaimages.org/latest/install.html) but having it here would also be good.

I also propose a CONTRIBUTING.md file describing how can one start making a contribution to the package. It provides beginners a path to follow and makes their journey to their first contribution easier.

**Comment by johnnychen94** [comment]
* The docs(https://juliaimages.org/latest/install.html) is the documentation of the whole Julia Image ecosystem.
* This repository `Images.jl`, however, consists of many dependencies. It would be quite ambiguous to introduce too many details of other repos to Images.jl/README -- which part of it really belongs to this repo?

But yes efforts should be paid to make the documentation more descriptive:

* we can add some quick-to-start snippets in Images.jl/README. 
* Perhaps adding some comparison (code simplicity, benchmark, etc.) to other languages will make this package more attractive. But I think this packages is not mature enough to do this right now.
* Also, I think there are few description to the relationship of this ecosystem at present.
