### ISSUE TITLE
Participation for GSoC 2019

### ISSUE THREAD

**Issue by yashrsharma44** [JuliaImages/Images.jl#782]
Hello people!
I was interested in contributing to Julia Images and hopefully submit a proposal on _Benchmarking of Julia Images_.
I wanted more context regarding this project, and the kind of expectations from this.

Regarding the profiling and benchmarking, what are the requirements for this project.
Ping @timholy @zygmuntszpak

**Comment by timholy** [comment]
Hi @yashrsharma44, sorry for the slow response, I've been swamped by another Julia project but that should be wrapping up soon.

Benchmarking would be a great project. At a minimum you might pick one other image-processing framework (scikit-image, OpenCV, ...) and develop some example problems to run in each. Then you could use, e.g., [BenchmarkTools](https://github.com/JuliaCI/BenchmarkTools.jl) to collect data, and script up an overall analysis and plot.
