### ISSUE TITLE
GSoC 2019 proposal -- Towards Better Images Ecosystem

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#783]
I'm a third-year graduate student in mathematical school of sciences, East China Normal University, Shanghai, and will be a ph.d candidate this fall. My current research field is low-level image processing.

At first I just planned to jump into and develop `Images.jl` this summer [regardless of the existence of GSoC](https://github.com/JuliaImages/Images.jl/issues/771#issuecomment-465003529), but now I'd like to apply for it since I found that I'm eligible to.

Currently I have three projects in mind that I'm capable of working on as GSoc 2019 project:
* clean up and improve the codebase towards a better and consistent API, as disscussed in https://github.com/JuliaImages/Images.jl/issues/772 and https://github.com/JuliaImages/Images.jl/issues/767
To make future development easier this is of higher priority in my opinion. -- **Prefered**
* write demos/tutorials using `Images.jl`
As head TA of "digital image processing" course I'm quite interested in this, some work I've done is re-implementing examples in [Digital Image Processing, Gonzalez](https://github.com/johnnychen94/Digital-Image-Processing-Gonzalez) -- **personal interest**
* Implement an `ImageNoise.jl` package
my current research is on image denoising based on variational model -- **not very urgent** for the `Images.jl` ecosystem but remains as a choice

I do enjoy working in julia community, some of my non-trival merged PRs are: 
* [Add image rotation@ImageTransformations](https://github.com/JuliaImages/ImageTransformations.jl/pull/58) reviewed by `Evizero` and `timholy`
* [Support `repeat` at any dimension@julia](https://github.com/JuliaLang/julia/pull/29626) reviewed by `mbauman`
* [Let `imresize` throw `MethodError` instead of `StackoverflowError`@ImageTransformations](https://github.com/JuliaImages/ImageTransformations.jl/pull/59) reviewed by `Evizero` and `timholy`
* [add support for ≈ operation for types `TrackedArray` and `TrackedReal`@Flux](https://github.com/FluxML/Flux.jl/pull/371) reviewed by `MikeInnes`

@timholy @zygmuntszpak @Evizero @juliohm I'm wondering if any of you guys is available as the mentor for any of this project so that I can draft a proposal before the student application of GSoC.

**Comment by zygmuntszpak** [comment]
Hi Johnny,

I'd love to work with you on your preferred project--clean up and improve the codebase towards a better and consistent API. 

Best wishes,

Zygmunt

**Comment by juliohm** [comment]
Hi Johnny,

I vote for the first option. Reorganizing the API would be a great
contribution.

Thank you for your work,

**Comment by johnnychen94** [comment]
Thanks!  I'll try plot a proposal in next weekend -- after the Ph.d exams.

**Comment by timholy** [comment]
I'm hoping to be done with the debugger well before the summer starts, so I'd be happy to help mentor you.

**Comment by johnnychen94** [comment]
@juliohm @timholy @zygmuntszpak @Evizero 
Sorry for the late draft, I'm stuck in my graduation dissertations now...

Despite my terrible writing, I'd like to hear feedback from you guys on my [GSoC 2019 Proposal -- draft](https://github.com/johnnychen94/GSoC2019_Proposal/blob/master/Proposal/main.pdf)

More specifically, on:

* how would you like this project?
* Do you have any more expectations on this project?
* Is this a project that can be handled within three months? Since I've never done this kind of work before I can't get the ETA
* Actually I don't know what to take care of in the second stage. I don't know what details should be included in this proposal.
* and other things I forgot

The layout and writing details will be refined in the next version.

**Comment by johnnychen94** [comment]
I'd like to implement an `ImageNoise.jl` package just like [ImageBinarization.jl](https://github.com/zygmuntszpak/ImageBinarization.jl), I think this would be a good experimental place to validate some concepts I jump up with.

**Comment by johnnychen94** [comment]
GSoC coding is over, close this now.
