### ISSUE TITLE
GSOC 2019 

### ISSUE THREAD

**Issue by devil-r** [JuliaImages/Images.jl#787]
Hi ,myself Tushar Dubey . I am in 2nd year CSE doing my Bachelor  of Technology(Btech) from NIT Surathkal.
I would love to contribute to JuliaImage. I am interested in the project "contribution to stereo matching package". I developed interest in this project due to my past project which was "Visual question and Answering". I don't have much experience with stereo matching but i have implemented CNN algorithms in the above mentioned project to extract image feature.
Currently i am going through the papers mentioned in the project.
 Can you help me started up this project (i mean what i should really look for so that i can generate proper understanding of project to propose the solution). Thanks:)

**Comment by devil-r** [comment]
@timholy  @zygmuntszpak

**Comment by zygmuntszpak** [comment]
Hi Tushar,

Perhaps a good starting point would be to read some tutorials on stereo matching so that you can familiarize yourself with the key concepts. You might want to start with implementing a simple "block" matching algorithm. There are lots of tutorials on stereo matching online. A quick search popped up this page which discusses block matching: http://mccormickml.com/2014/01/10/stereo-vision-tutorial-part-i/

You want to be able to understand the listed papers to the point where you would know how translate the ideas outlined in the paper into code.

**Comment by devil-r** [comment]
@zygmuntszpak  should i go through the julia image documentation at this stage?
I have already set up the environment for it. Also one more thing, how many algorithms  do you look forward to be implemented for julia stereo matching packages?

**Comment by johnnychen94** [comment]
Hi Tushar,

Sincerely, I don't mean to boo to you,  I was and am a student as well, but I think you're probably not understanding the gaming rule of GSoC so well:

* According to my understanding of GSoC, it is a self-driven hackathon event -- _you decide what you want to do as a project_, ask if there's anyone thinks it as a good idea, and find a mentor who is willing to guide and help you (not as your boss, but as senior collaborator). The project list in https://julialang.org/soc/projects/images.html just serves as an inspiration.
* The clock is ticking. You need to show your ideas as soon as you can, if anyone is interested in this, draft it quickly, show it to your mentor, ask for feedbacks, polish it, and then send the application. -- **Before April 9**
* According to your words, you're not very familiar with Julia yet. Probably you're not yet ready for GSoC. 

Quote from [Julia GSoC guidelines](https://julialang.org/soc/guidelines/):

>The key questions we will ask ourselves when considering it are:
>
> * Is the student committed to the project?
> * Is the plan a reasonable amount to do in three months?
> * Are there clear milestones we can use to assess progress (it should be easy to answer the question “Is the project done?”).

Just want to repeat it again, I don't mean to be rigorous to you. If you're feeling offended, I'm truly sorry.

My suggestion: 

* If you do want to apply a GSoC, make it quick and pay efforts, being interested is far from successfully applying GSoC.
* Contribute is always welcomed as an open-source project, I mean, I learned a lot here and I believe you will too.

Best regards
