### ISSUE TITLE
switching registration system

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#798]
I tried to upgrade `ImageMorphology` to support Julia v1.0 and v1.1 in https://github.com/JuliaImages/ImageMorphology.jl/pull/14 and fix broken CI, also a release `v0.2.0` is published.

But in Julia CLI it says no such release

```julia
(v1.0) pkg> activate .

(jc) pkg> add ImageMorphology@0.2
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ImageMorphology [787d08f9]:
 ImageMorphology [787d08f9] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.1] or uninstalled
 └─restricted to versions 0.2 by an explicit requirement — no versions left
```

Looks like it's because attobot is disabled according to [switching package registration system](https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677), and we need a change from [attobot](https://github.com/attobot/attobot) to [Registrator](https://github.com/JuliaComputing/Registrator.jl)

And looks like installing new Registrator will be enough to fix this release failure, but this's out of my knowledge at present :(

cc: @timholy

**Comment by johnnychen94** [comment]
Looks like this was caused by incorrect release name. It should be `v0.2.0` and I named it `0.2.0`

**Comment by timholy** [comment]
@RalphAS installed the new Registrator, so you should be able to do it now.

**Comment by johnnychen94** [comment]
Looks like the new Registrator isn't compatible with the old one. see PR: https://github.com/JuliaIO/QuartzImageIO.jl/pull/56 (I'm not sure if I'm doing in the right way)

repos that lack of `Project.toml` and need updates: (sorted by update time: from latest to oldest)

- [ ] [ImageMetadata](https://github.com/JuliaImages/ImageMetadata.jl) PR: https://github.com/JuliaImages/ImageMetadata.jl/pull/43
- [ ] [ImageTracking](https://github.com/JuliaImages/ImageMetadata.jl/pull/43) PR: https://github.com/JuliaImages/ImageTracking.jl/pull/21
- [ ] [ImageFiltering](https://github.com/JuliaImages/ImageFiltering.jl)
- [ ] [ImageCore](https://github.com/JuliaImages/ImageCore.jl)
- [ ] [ImageTransformation](https://github.com/JuliaImages/ImageTransformations.jl)
- [ ] [TestImages](https://github.com/JuliaImages/TestImages.jl)
- [ ] [ImageFeatures](https://github.com/JuliaImages/ImageFeatures.jl)
- [ ] [ImageDistances](https://github.com/JuliaImages/ImageDistances.jl)
- [ ] [ImageView](https://github.com/JuliaImages/ImageView.jl)
- [ ] [ImageShow](https://github.com/JuliaImages/ImageShow.jl)
- [ ] [ImageSegmentation](https://github.com/JuliaImages/ImageSegmentation.jl)
- [ ] [ImageInTerminal](https://github.com/JuliaImages/ImageInTerminal.jl)
- [ ] [ImageInpainting](https://github.com/JuliaImages/ImageInpainting.jl)
- [ ] [ImageAxes](https://github.com/JuliaImages/ImageAxes.jl)

Are following repos deprecated, or are they just need someone to maintain?
- [ ] [Tinker](https://github.com/JuliaImages/Tinker.jl)
- [ ] [CameraGeometry](https://github.com/JuliaImages/CameraGeometry.jl)
- [ ] [ImageCL](https://github.com/JuliaImages/ImageCL.jl)
- [ ] [IntegralArrays](https://github.com/JuliaImages/IntegralArrays.jl)

**Comment by johnnychen94** [comment]
> I'm not sure if we should drop julia v0.7 support, more specifically, should I
> 
> * set julia v0.7 compatible in Project.toml
> * drop julia v0.7 test in travis.yml

https://github.com/JuliaImages/ImageCore.jl/pull/71#discussion_r277172826

Conclusion: set v0.7 incompatible when we drop the CI test for it.

> I guess we only need at most three versions under CI test, i.e., 1.0 as LTS version, 1.1 as the latest release version, and nightly build which allows failure.

https://github.com/JuliaImages/ImageView.jl/pull/171#discussion_r277168118

The answer is yes.

**Comment by johnnychen94** [comment]
There's a registrator bug for julia version compatibility `julia = ">= 1.0"` as described https://github.com/JuliaComputing/Registrator.jl/issues/103

The following package versions aren't compatible for julia version `julia = ">=1.3"`:
* Images v0.18.0
* ImageMorphology v0.2.0
* ImageMetadata v0.7.0
* TestImages v0.5.0

**Comment by johnnychen94** [comment]
A large part of the switching procedure is finished except `ImageTracking` and `ImageInpainting`, which are not registered yet.

**Comment by timholy** [comment]
Thanks so much @johnnychen94 for your steadfast stewardship of this transition! :fireworks:
