### ISSUE TITLE
reduce dependency complexity on Colors and FixedPointNumbers

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#802]
The original issue is: https://github.com/JuliaImages/ImageCore.jl/issues/74

The idea is to reexport `Colors` and `FixedPointNumbers` so that other packages under JuliaImages do not need to manually manage the dependency in `Project.toml`. Users don't need to explicitly `]add` and `using` these two packages as well.

This issue will be addressed in two steps:

- [x] reexport `Colors` and `FixedPointNumbers` in `ImageCore` with a patch version bump. PR: https://github.com/JuliaImages/ImageCore.jl/pull/75
- [ ] remove `Colors` and `FixedPointNumber` dependency in downstream packages
  - [x] ImageDistances (https://github.com/JuliaImages/ImageDistances.jl/pull/41) (https://github.com/JuliaImages/ImageDistances.jl/pull/41)
  - [ ] Images (#853)
  - [x] ImageMetadata (https://github.com/JuliaImages/ImageMetadata.jl/pull/61)
  - [x] ImageFiltering https://github.com/JuliaImages/ImageFiltering.jl/pull/133
  - [x] ImageAxes (https://github.com/JuliaImages/ImageAxes.jl/pull/42)
  - [x] ImageDraw https://github.com/JuliaImages/ImageDraw.jl/pull/23
  - [x] ImageShow https://github.com/JuliaImages/ImageShow.jl/pull/16
  - [x] ImageInTerminal https://github.com/JuliaImages/ImageInTerminal.jl/pull/26
  - [x] ImageTransformations (https://github.com/JuliaImages/ImageTransformations.jl/pull/85)
  - [x] ImageMorphology (not under active maintainance and doesn't have upper bound for any package) https://github.com/JuliaImages/ImageMorphology.jl/pull/23

related issue: https://github.com/JuliaImages/Images.jl/issues/792

**Comment by johnnychen94** [comment]
This procedure should not begin until other major julia package ecosystems switching to the new registrators.

A related issue is the version conflict between `Makie v0.9.3` and `ImageDistances v0.2.2` 
https://github.com/JuliaImages/ImageDistances.jl/issues/20

**Comment by timholy** [comment]
Unless the conflict is encoded in the package's `Project.toml` (or `REQUIRE` if it's still using older style), you just need to submit PRs to https://github.com/JuliaRegistries/General. Similar to https://github.com/JuliaRegistries/General/pull/550.

**Comment by johnnychen94** [comment]
During the test, I've met some indirect compatibility issues.

More specifically, `ImageQualityIndexes` *hard* requires `FixedPointNumbers v0.6.1`, which is reexported by `ImageCore`. At first sight, I thought it was okay to have the following `Project.toml` without `FixedPointNumbers`:

```toml
[deps]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"

[compat]
ImageCore = ">= 0.8.3"
```

But it now loses the compatibility requirement on `FixedPointNumbers`. I don't have any good solution to this except "reintroducing the direct dependency on FixedPointNumbers"

**Comment by johnnychen94** [comment]
As the package version control becomes convenient with all the automation of CompatHelpers, TagBot and Registrator, I think it's the right time to push this issue. For most packages, they don't need to directly depend `Colors`, `ColorTypes` and `FixedPointNumbers` unless there's a real need. Instead of set lower package bounds on `Colors`, we can set it on `ImageCore` now. For example, from https://github.com/JuliaImages/ImageCore.jl/releases we can set `ImageCore = "0.8.7"` if we really need the latest feature brought by `Colors v0.10.0`

pros of this strategy are:

* reduce (direct) dependency complexity
* Less likely to hit a version conflict (*I assume so*)
