### ISSUE TITLE
Unsatisfiable requirements when trying to install OMETIFF due to Images.

### ISSUE THREAD

**Issue by kellertuer** [JuliaImages/Images.jl#804]
When I try to `] add OMETIFF` (because I need that for another project, namely `TestImages.jl`, I get

```
ERROR: Unsatisfiable requirements detected for package OMETIFF [2d0ec36b]:
 OMETIFF [2d0ec36b] log:
 ├─possible versions are: [0.0.1, 0.1.0-0.1.2, 0.2.0-0.2.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0-0.1.2, 0.2.0-0.2.1]
 ├─restricted by compatibility requirements with Images [916415d5] to versions: [0.0.1, 0.1.0-0.1.1] or uninstalled, leaving only versions: [0.0.1, 0.1.0-0.1.1]
 │ └─Images [916415d5] log:
 │   ├─possible versions are: [0.2.0-0.2.50, 0.3.0-0.3.3, 0.4.0-0.4.50, 0.5.0-0.5.14, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.5, 0.12.0, 0.13.0, 0.14.0, 0.15.0-0.15.1, 0.16.0-0.16.1, 0.17.0-0.17.3, 0.18.0] or uninstalled
 │   └─restricted to versions 0.18.0 by an explicit requirement, leaving only versions 0.18.0
 └─restricted by julia compatibility requirements to versions: 0.2.0-0.2.1 or uninstalled — no versions left
```

If I read that correctly, `julia` (running version 1.1 on Mac OS here) requires that `OMETIFF` to be at least at version `0.2.0`, while Images requires that `OMETIFF` is less than `0.1.1` (fifth line). I could not find `OMETIFF.jl` in your `project.toml` so I am not completely sure where this requirement comes from, but can someone check, whether Images is ok with a newer version of `OMETIFF.jl` to solve this error? Or is it `OMETIFF` that is wrong here?

**Comment by timholy** [comment]
My guess this is another one of those cases where automatically-imposed upper bounds are getting in the way (https://github.com/JuliaRegistries/Registrator.jl/issues/122). Check Images' and OMETIFF's `Project.toml` to see if there are any "real" version restrictions. Then check `~/.julia/registries/General` and see about editing the Compat.toml files to fix the bounds. If that's what's needed, then please bundle those changes up as a PR to https://github.com/JuliaRegistries/General.

**Comment by kellertuer** [comment]
I already tried that, but OMETIFF does not yet have a `Project.toml` and the `REQUIRE` looks okay. In `Images` there is no direct restriction, so it might come from one of the packages it depends on, but how can I find _that_ out?

For the second part, the `Compact.toml`s might be machine readable but they are not understandable for me (checked my `Images` Compat, since without an installed OMETIFF I don't have their's).

**Comment by timholy** [comment]
You did the right thing. Just submit that change to JuliaRegistries. Thanks!

**Comment by kellertuer** [comment]
Cool.After working with Julia for a while I am slowly getting into fixing things I notice, that's fun :)

**Comment by tlnagy** [comment]
Hey (I'm the author of `OMETIFF.jl` 👋) thanks for taking care of this! I've just updated it to use the new the `Project.toml` setup: https://github.com/tlnagy/OMETIFF.jl/pull/34
