### ISSUE TITLE
Port convexhull.jl and connected.jl to ImageMorphology.jl

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#807]
I propose to move the following two files to `ImageMorphology.jl`

* [`connected.jl`](https://github.com/JuliaImages/Images.jl/blob/master/src/connected.jl)
* [`convexhull.jl`](https://github.com/JuliaImages/Images.jl/blob/master/src/convexhull.jl)

My reason is: graphs are heavily used in morphology operations

ported functions:

* [`label_components`](https://github.com/JuliaImages/Images.jl/blob/master/src/connected.jl#L3-L29) and `label_components!` (This blocks PR: [add `imfill` function](https://github.com/JuliaImages/ImageMorphology.jl/pull/9))
* [`convexhull`](https://github.com/JuliaImages/Images.jl/blob/master/src/convexhull.jl)
* [`component_boxes`](https://github.com/JuliaImages/Images.jl/blob/bdfd044420fa6ffcd34760f804f0c3ce12186945/src/connected.jl#L228-L244), `component_lengths`, `component_indices`, `component_subscripts`, `component_centroids`

All of these functions are exported by `Images`, but it would quite painless since `ImageMorphology` is reexported by `Images`

Possibly, [`labeledarrays.jl`](https://github.com/JuliaImages/Images.jl/blob/master/src/labeledarrays.jl) can be ported to `ImageMorphology.jl` as well.

cc: @juliohm, @aquatiko

**Comment by juliohm** [comment]
Thank you Johnny for proposing the move. I like the idea of moving anything
from Images.jl to subpakcages, and these functions seem to fit well in
ImageMorphology.jl
