### ISSUE TITLE
Storage / pixel aspect ratio

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/Images.jl#813]
**Warning: esoteric issue** 

How should `Images` deal with pixel aspect ratios that are not equal to one?

While this is inherently a videos issue (see [related issue](https://github.com/JuliaIO/VideoIO.jl/issues/185) in `VideoIO`), there can be situations where the pixels in an image are not square (e.g. when extracting images from such videos).

The current method of dealing with this is warping the image accordingly (by stretching/squeezing one of the dimensions of the image). Not only is this method relatively expensive it might not be necessary in all cases! 

How big of a problem is this really? That depends on the number of devices that output images with PAR ≠ 1, how many images those devices output, and what those images are used for.

I suspect that this hasn't been mentioned before partly because people never considered *not* warping the images. But I argue that a lazy approach would be perfectly adequate in most cases.

**Comment by johnnychen94** [comment]
ImageTransformations provides `WarpedView` as a lazy version of `warp` to support this.

I believe a lazy `imresize` is what you're asking for, so I'm closing this in favor of https://github.com/JuliaImages/ImageTransformations.jl/issues/119.
