### ISSUE TITLE
Restrict-ed dims are half size +1 in both dims

### ISSUE THREAD

**Issue by ianshmean** [JuliaImages/Images.jl#818]
This  (1024,1280) image should be halve-able to (512,640).

```julia
using ImageTransformations
size(ImageTransformations.restrict(rand(1024,1280))) 

(513,641)
```

Perhaps it's something wrong with:
```julia
restrict_size(len::Integer) = isodd(len) ? (len+1)>>1 : (len>>1)+1
```
https://github.com/JuliaImages/ImageTransformations.jl/blob/7a5d9ae537f4158757fbcb70aac7f91e495d635e/src/resizing.jl#L157

**Comment by timholy** [comment]
It's not a bug, it's just doing something different than you expect. (There might be room for another function that does what you're expecting.)

References:
- https://github.com/timholy/RestrictProlong.jl
- https://en.wikipedia.org/wiki/Galerkin_method

**Comment by ianshmean** [comment]
I see. I'd PR a tweak to [the docs](https://juliaimages.org/latest/function_reference/#ImageTransformations.restrict) as to the naive user like myself it does seem like the result should be half the dim size, but I'm not sure I can succinctly explain why
