### ISSUE TITLE
Control+C with imread() on TIFF file breaks Images

### ISSUE THREAD

**Issue by cbecker** [JuliaImages/Images.jl#82]
Interrupting `imread()` with Control+C seems to break the Images package somehow, for example doing

```
julia> using Images

# here I press Control+C while the file is being loaded
julia> q=imread("someLargeTiffFile.tif");
^CERROR: interrupt
 in readimage at /home/cjbecker/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:179
 in imread at /home/cjbecker/.julia/v0.3/Images/src/io.jl:192
 in imread at /home/cjbecker/.julia/v0.3/Images/src/io.jl:104

# now this will hang forever, and never return
julia> q=imread("someLargeTiffFile.tif");
```

If I press Control+C again, I only get a message saying "interrupt", instead of a nice backtrace as in the first time.

It also seems to be linked to the format (in this case TIFF), because I can load an nrrd file without problems afterwards, but it won't work for TIFF. I am working with a 3D TIFF file, I am not sure how that affects this problem.

**Comment by Evizero** [comment]
closing as long outdated
