### ISSUE TITLE
How can I get the grayscale image as 0-255 values?

### ISSUE THREAD

**Issue by GrayJack** [JuliaImages/Images.jl#823]
I need the image that the range 0-255 in the latest version, how can I achieve that?

The methods shown on old issues doesn't work for me

**Comment by johnnychen94** [comment]
Short answer is:

```julia
img = 255 .* float32.(img)
```

Unless you know what you're doing, it's not recommended to use `0-255` value range; by default, all julia images use value range `0-1`. Perhaps you need to read [The 0-to-1 intensity scale](https://juliaimages.org/latest/quickstart/#The-0-to-1-intensity-scale-1) 😄

**Comment by GrayJack** [comment]
I do know what I'm doing, and I saw that section of the documentation, but I didn't got it right cause `rawview` needs the array to be `Array{N0f8, 2}`, but I have  `Array{Gray{N0f8}, 2}`.

So in the end I have a `Array{Gray{N0f8}, 2}` for that to work, I would need an `Array{N0f8, 2}`, how do I do that tranformation?

**Comment by johnnychen94** [comment]
you can use `N0f8.(img)` or `channelview(img)` (for a view version) then

**Comment by GrayJack** [comment]
Thanks, that worked amazing!!! I think we can close this issue now
