### ISSUE TITLE
introduce ImageBinarization.jl and ImageContrastAdjustment.jl into Images.jl

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#841]
A large part of legacy codes in Images.jl (`exposure.jl` and `algorithm.jl`)are for histogram and binarization. Since `ImageBinarization.jl` becomes stable now, we could `@reexport ImageBinarization` and do some pruning work.

It's quite difficult to determine which part of codes are legacy and can be safely deleted, this issue is used to track the list and make discussions.

Some functions I've identified (and there're more):

* `otsu_threshold` in favor of `ImageBinarization.Otsu`
* `yen_threshold` in favor of `ImageBinarization.Yen`
* `imhist`, `build_histogram` in favor of `ImageContrastAdjustment.build_histogram`
* `adjust_histogram`, `adjust_histogram!` in favor of `ImageContrastAdjustment.adjust_histogram` 

@zygmuntszpak it would be great if you can give some help 😄

**Comment by zygmuntszpak** [comment]
I would like to implement a few more algorithms in both packages and then perhaps submit these packages to `https://joss.theoj.org/` with at least, @johnnychen94 and @timholy as coauthors. Would that pose a problem?

**Comment by zygmuntszpak** [comment]
If we re-export the contrast adjustment functionality from `ImageContrastAdjustment`, do we replicate the tests that are in the `ImageContrastAdjustment` package in the `Images` package? Or do we want some simpler tests that just verify that the API is callable?

**Comment by johnnychen94** [comment]
> do we replicate the tests that are in the ImageContrastAdjustment package in the Images package?

Regardless of CI pressure, the only problem is those tests (if hosted in Images.jl) are very likely to be outdated soon. Not only tests, but documentation also has the same problem. And the current status of Images.jl as far as I've seen is to do whatever choice here (or even without tests here); many test codes in Images.jl is becoming legacy.

> Or do we want some simpler tests that just verify that the API is callable?

This can be a good choice and I think this is what we can promise so far without too many efforts. (P.S. The current API we use in ImageBinarization doesn't take executing context (e.g., multi-threads, GPU/CPU) into consideration yet.)

As complementary to this option, I'm trying to set up a "syncing" functionality using the power of git submodules in #843 to tackle this issue for documentation, and if that works well I'm planning to do the same thing for tests.

**Comment by timholy** [comment]
Closed by #1030
