### ISSUE TITLE
Unsustainable load times, fails PackageCompiler

### ISSUE THREAD

**Issue by vomout** [JuliaImages/Images.jl#844]
I only need the `Gray` function from Images to pass data to Plots and convert images from TestImages for processing. However loading Images takes the majority of the load time of my package, and it is not little:
```
julia> @time using Images
 10.552608 seconds (13.08 M allocations: 683.794 MiB, 3.37% gc time)
```
(mid-2014 MacBook Pro with 16GB RAM. Slightly better on a 2019 iMac but still unsustainable.) I've tried to use PackageCompiler to improve the load times, but `Images` fails the compilation.
```
ptrtoint not supported for non-integral pointers
inttoptr not supported for non-integral pointers
LLVM ERROR: Broken function found, compilation aborted!
ERROR: failed process: Process(`/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia --sysimage=/Users/tuomov/.julia/dev/PackageCompiler/sysimg/backup/native/sys.dylib --startup-file=no --output-o=sys.a --track-allocation=none --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --compile=yes --track-allocation=none --sysimage-native-code=yes --sysimage=/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib --compiled-modules=yes --optimize=2 /Users/tuomov/.julia/dev/PackageCompiler/sysimg/run_julia_code.jl`, ProcessExited(1)) [1]
```

What to do? If PackageCompiler cannot be made to work, I'd suggest breaking up the package into smaller packages that can be loaded individually when only needing specific parts. These load times are unsustainable when developing and debugging your own code.

**Comment by Tokazama** [comment]
Take a look at Colors.jl and ColorTypes.jl. Only a small portion of concrete types are actually defined under the umbrella of Images.jl.

**Comment by timholy** [comment]
We've already broken Images into many small pieces. Look at https://github.com/JuliaImages, many of those packages are loaded by Images.jl. Images.jl is on its way to being just a meta-package.
