### ISSUE TITLE
Can't use library on Windows 10

### ISSUE THREAD

**Issue by Scriddie** [JuliaImages/Images.jl#846]
I've installed Julia 1.3.0 (64 bits) on Windows 10 Home (64 bits). Now I am trying to run the follwoing commands:
```
import Pkg
Pgk.add("Images")
using(Images)
```

Adding the library seems to work fine, but `using(Images)` fails with the following error:

could not load library "<my_path>\.julia\packages\FFTW\loJ3F\deps\usr\bin\libfftw3-3.dll"
%1 is not a valid Win32 application

I tried older Julia versions as well as the 32 bits version, but nothing worked. Manually replacing the .dlls only left me with a different error.

**Comment by Tokazama** [comment]
Have you tried just `using FFTW`?

**Comment by Scriddie** [comment]
@Tokazama that raises the exact same error

**Comment by Tokazama** [comment]
Then this is likely related to this issue https://github.com/JuliaMath/FFTW.jl/issues/125 and not necessarily a problem with Images.jl.

**Comment by Scriddie** [comment]
Ah, that seems right! the solution linked in the thread (https://discourse.julialang.org/t/help-installing-approxfun-jl/31285/3) solved my problem as well. Thanks a lot!

**Comment by Tokazama** [comment]
@timholy, @johnnychen94  this can probably be closed now
