### ISSUE TITLE
TODO: put PkgEval badges on all repositories

### ISSUE THREAD

**Issue by timholy** [JuliaImages/Images.jl#862]
Now that PkgEval is being used routinely to test the next release of Julia (ref https://discourse.julialang.org/t/ann-nanosoldier-package-evaluation-with-badges/33339), it is particularly important for us to keep our tests working. We should probably add badges to all the repos, just so we have a visual indicator of whether everything is working properly.

Badge format: in the README, up near the top put
```md
[![PkgEval][pkgeval-img]][pkgeval-url]
```
and at the bottom:
```md
# change E/Example to the initial and name of your package
[pkgeval-img]: https://juliaci.github.io/NanosoldierReports/pkgeval_badges/E/Example.svg
[pkgeval-url]: https://juliaci.github.io/NanosoldierReports/pkgeval_badges/report.html
```

**Comment by johnnychen94** [comment]
Except for those unregistered packages, there're two packages I didn't add badges to without write permission:

- [ ] ImageTransformations
- [ ] ImageInpainting (cc: @juliohm )

**Comment by johnnychen94** [comment]
I would say this as closed now.

**Comment by timholy** [comment]
Thanks so much @johnnychen94! All those badges clearly needed a lot of maintenance, the devs & users really appreciate your work here!

For posterity let's also link https://github.com/JuliaImages/juliaimages.github.io/blob/source/DASHBOARD.md
