### ISSUE TITLE
Move feature_transform and distance_transform to ImageMorphology?

### ISSUE THREAD

**Issue by tlnagy** [JuliaImages/Images.jl#883]
I find the `feature_transform` and `distance_transform` functions very useful, but `Images` is a very heavy dependency that I would like to avoid at the package level. Could we move these functions to `ImageMorphology` (or somewhere else that makes sense)?

**Comment by timholy** [comment]
I'd be fine (nay, happy) with that. ImageMorphology seems as good a place as any.

**Comment by tlnagy** [comment]
One issue is that if someone has the old Images.jl and ImageMorphology 0.2.6 (once JuliaImages/ImageMorphology.jl#28 is merged) then they can run into an issue with both packages exporting the functions. The best solution IMO is to retroactively add a cap to the current version of `Images.jl` in the general registry.

**Comment by timholy** [comment]
Yes, agreed. You can use [RetroCap](https://github.com/bcbi/RetroCap.jl) to automate this and submit a PR to JuliaRegistries/General. (Use monotonic bounds.)
