### ISSUE TITLE
Error in 'using Images' - "require_one_based_indexing not found"

### ISSUE THREAD

**Issue by eyhl** [JuliaImages/Images.jl#885]
Dear community I tried loading Images v0.22.1 using

`using Images`

and got the error seen in the images. Downgrading to Images v0.22.0 got things to work again. Maybe the cause is missing definition of  require_one_based_indexing variable in MosaicViews.jl:392 as reported in the error message. 

Have good day!

![fejl1](https://user-images.githubusercontent.com/40029483/79046744-f9c64e80-7c12-11ea-94d5-2f34a69011e1.png)
![fejl2](https://user-images.githubusercontent.com/40029483/79046749-fd59d580-7c12-11ea-9ab2-536c3c8d8ba2.png)

**Comment by johnnychen94** [comment]
Sorry for the trouble, already fixed by https://github.com/JuliaArrays/MosaicViews.jl/pull/18 (tagged as MosaicViews v0.2.2), an `]up` can solve this.
