### ISSUE TITLE
Images conversion on Windows 

### ISSUE THREAD

**Issue by darrencl** [JuliaImages/Images.jl#888]
Hi all,

I would like to ensure that upon `save` I am saving whatever image I am loading to `.png` format.

```julia
img = load("path/to/image")
save("newfile.png", img)
```
I've tested this on my Linux machine and seems okay, but when I use my colleague windows machine, this doesn't work. 
```
Errors encountered while saving "Desktop/test.png".
All errors:
===========================================
WriteBlob Failed `Desktop/test.png' @ error/png.c/MagickPNGErrorHandler/1641
===========================================
ArgumentError: Argument does not support conversion to png.
===========================================

Fatal error:
ERROR: WriteBlob Failed `Desktop/test.png' @ error/png.c/MagickPNGErrorHandler/1641
Stacktrace:
 [1] handle_error(::ErrorException, ::File{DataFormat{:PNG}}) at C:\Users\tjwatson\.julia\packages\FileIO\BcdlR\src\error_handling.jl:82
 [2] handle_exceptions(::Array{Any,1}, ::String) at C:\Users\tjwatson\.julia\packages\FileIO\BcdlR\src\error_handling.jl:77
 [3] #save#30(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(save), ::Formatted, ::Any) at C:\Users\tjwatson\.julia\packages\FileIO\BcdlR\src\loadsave.jl:213
 [4] save at C:\Users\tjwatson\.julia\packages\FileIO\BcdlR\src\loadsave.jl:196 [inlined]
 [5] #save#15 at C:\Users\tjwatson\.julia\packages\FileIO\BcdlR\src\loadsave.jl:118 [inlined]
 [6] save(::String, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2}) at C:\Users\tjwatson\.julia\packages\FileIO\BcdlR\src\loadsave.jl:118
 [7] top-level scope at REPL[13]:1

```
My question is, do I need to explicitly install the ImageMagick v6 on the windows machine first? Looking at the error message, the first part of it seems to come from the ImageMagick, so it seems to be installed, but when I do `convert -version` or `magick` in command prompt, it's seems to be not installed.

If explicitly installing ImageMagick is not required, how can I fix this? It seems coming from the ImageMagick end instead of my code.

Thanks!

**Comment by timholy** [comment]
There is no such thing as a PNG *result*: an image is just an array of values, whether it gets defined by an algorithm, loaded from a PNG file, JPEG file, or whatever. Without having `img` itself I can't imagine what the problem is here.

However, one recommendation is to add the ImageIO package and try again. FileIO (which implements `save`) will use it if available; for PNGs it's both faster and seems more reliable.

**Comment by timholy** [comment]
Also, if you're not using at least Julia 1.3, consider upgrading. The binary-dependency experience got infinitely nicer on Julia 1.3.

**Comment by johnnychen94** [comment]
I vaguely remember to have met similar issues when the `dst_folder`, i.e., `Desktop` doesn't exist and/or not the abspath isn't ASCII encoded.

**Comment by darrencl** [comment]
@timholy the image loaded for this testing is also `.png` image I'm just saving it to another path with different filename. I am already using Julia 1.3 too. 

Anyway, thanks for the suggestions, I will try using `ImageIO` and other `dst_folder` to see if it helps.

**Comment by darrencl** [comment]
@johnnychen94 @timholy `dst_folder` seems to be the issue. Anyway, I will still use `ImageIO` instead of `ImageMagick` though! Thanks for the assistance!
