### ISSUE TITLE
excessive memory allocation when loading tiff

### ISSUE THREAD

**Issue by cbecker** [JuliaImages/Images.jl#89]
I am experiencing huge extra allocations when loading a multi-page tiff. The original file is 68MB. If first I do

``` julia
using Images
```

then measure julia's mem usage (htop), and then run:

``` julia
img = imread("myFile.tif");
```

julia's mem usage (htop) went up by 1GB over what it was before reading the image.
If I know do garbage collection:

``` julia
gc()
```

then I get only 68MB on top of what mem usage was before reading the image (which is what I would expect at the beginning)

I am not sure where this comes from, but seems like a huge problem (crashed my 8GB-ram computer when trying to load a 380MB tif file).

<b>EDIT</b>: though this is weird:

``` julia
julia> @time img = imread("myFile.tif");
elapsed time: 1.443803004 seconds (70277744 bytes allocated)
```

**Comment by juliohm** [comment]
This issue doesn't apply anymore, `imread` is not part of the latest Images.jl.

For loading TIFF images, please check [OMETIFF.jl](https://github.com/tlnagy/OMETIFF.jl).

It would be great if someone could close this issue.
