### ISSUE TITLE
Regarding contribution: a new image edge detection technique

### ISSUE THREAD

**Issue by SujoyKG** [JuliaImages/Images.jl#896]
Hello Sir/ Madam,

I want to contribute to JuliaImages with [a new image edge detection
technique](https://www.ijert.org/research/a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf) which is more generic & better than the similar popular techniques for the same. Few other libraries are also in the process of including this algorithm.
Please go through the paper.
If you like it, please tell me the process to move next.

Thanks & Regards,
Sujoy K Goswami
Principal Data Scientist
TVS Motor Company
India

**Comment by johnnychen94** [comment]
Thanks for the interest! There is a new unregistered package https://github.com/JuliaImages/ImageEdgeDetection.jl, I think the codes could be hosted there. If you were new to Julia and JuliaImages, perhaps it would be good to first come up with a demo so that we could give the first-round feedback before you submitting a PR.

cc: @zygmuntszpak

**Comment by zygmuntszpak** [comment]
Thank you for your interest. Apart from the classic Prewitt and Sobel masks, we also have several other masks for computing the image gradient including [Ando, Scharr and Bickley](https://juliaimages.org/stable/function_reference/#ImageFiltering.imgradients)  which are "optimal" with respect to  various criteria such as isotropy. 

The paper you referenced proposes a different mask. I don't believe the paper makes a convincing case for why the masks that it proposes are truly more generic and better  for computing the gradient of an image. 

However, it is very easy for someone who would like to use the masks that are proposed in the paper to do so. It is just a matter of specifying the masks and calling the  [imfilter](https://juliaimages.org/stable/function_reference/#ImageFiltering.imfilter) function with the mask. 

Perhaps you could take this opportunity to contribute [a demo](https://johnnychen94.github.io/DemoCards.jl/stable/index.html) to our [Documentation ecosystem](https://github.com/JuliaImages/juliaimages.github.io) which showcases how one could specify the mask and threshold the result for edge detection? Further examples of demos can be found [here](https://juliaimages.org/stable/democards/examples/color_channels/color_separations_svd/#color-separations-and-the-svd-1-1).

**Comment by johnnychen94** [comment]
With no response in two weeks, I'm closing this issue.

**Comment by amarbit** [comment]
> Thank you for your interest. Apart from the classic Prewitt and Sobel masks, we also have several other masks for computing the image gradient including Ando, Scharr and Bickley  which are "optimal" with respect to  various criteria such as isotropy.
> The paper you referenced proposes a different mask. I don't believe the paper makes a convincing case for why the masks that it proposes are truly more generic and better  for computing the gradient of an image.
> However, it is very easy for someone who would like to use the masks that are proposed in the paper to do so. It is just a matter of specifying the masks and calling the  imfilter function with the mask.
> Perhaps you could take this opportunity to contribute a demo to our Documentation ecosystem which showcases how one could specify the mask and threshold the result for edge detection? Further examples of demos can be found here.

Dear sir,
I have developed the sujoy's code in Julia. Please give me the exact link where I can post the code.

Thanks
