### ISSUE TITLE
Move Shepp-Logan phantom to TestImages.jl?

### ISSUE THREAD

**Issue by stillyslalom** [JuliaImages/Images.jl#899]
It seems a bit out of place in algorithms.jl.
https://github.com/JuliaImages/Images.jl/blob/7bdd97d9db32c831da394c8423d88a40bf188726/src/algorithms.jl#L598

**Comment by johnnychen94** [comment]
A good idea to me. I've thought about this once a while, but just can't come up with a compatible API to the current `testimage` usage.

**Comment by stillyslalom** [comment]
If there's not a good way to shoehorn it into a `testimage` function call, TestImages.jl can easily have more than one exported method.

**Comment by johnnychen94** [comment]
I'm good to this, mind to make a PR?

Examples can be found at https://github.com/JuliaImages/ImageMorphology.jl/pull/28 and https://github.com/JuliaImages/Images.jl/pull/895

**Comment by timholy** [comment]
I like the idea of moving it. We would have to do this in a way that is non-breaking, though, unless we bump minor or major versions.

**Comment by johnnychen94** [comment]
For clarification, I was suggesting (1) copying it to TestImages, (2) add a deprecation in Images.jl, and finally (3) deleting it in `Images@v1.0.0`

**Comment by johnnychen94** [comment]
One way to make it compatible with the current `testimage` API is to redirect `testimate("phantom", size=(256, 256), high_contrast = true)` to its real generation.

**Comment by johnnychen94** [comment]
Some update on this:

`shepp_logan` is reimplemented in `TestImages.shepp_logan` and `Images.shepp_logan` will be removed in a future release (possibly v1.0.0)

**Comment by timholy** [comment]
This was done for the 0.25 release.
