### ISSUE TITLE
Regarding a new image edge-detection technique

### ISSUE THREAD

**Issue by amarbit** [JuliaImages/Images.jl#913]
Hi,

Please see the issue in the link below:
https://github.com/JuliaImages/Images.jl/issues/896#issue-642408058

I have the Julia code ready with me for Sujoy's paper. Please allow me to contribute and send me the link to upload my code.

Thanks and Regards

**Comment by johnnychen94** [comment]
Thanks for the proposal.

We haven't established a guideline on whether a new algorithm should be accepted or not. But here is some aspects that I'll take into consideration with regard to this:

* whether this algorithm is used widely (Is there an implementation in other image processing libraries? how many citations does the paper has. Etc)
* is this algorithm been superior to existing algorithms in any of the usability and performance aspects. By saying usability I mean, does this algorithm achieve a more stable result without tweaking the parameters, or does this algorithm work on more broad types of images?

As is replied by @zygmuntszpak in https://github.com/JuliaImages/Images.jl/issues/896#issuecomment-647095939, this algorithm does not meet any of the above guildline, and it is not very convincing that we should add this new method as a standard algorithm into the JuliaImages ecosystem.

If you'd like to add this algorithm and advertise it in JuliaImages, I prefer to add it as a [demo card](https://juliaimages.org/latest/democards/examples/) for it with a reference to your paper. You can find some guidance on how to add such demo card in https://github.com/JuliaImages/juliaimages.github.io

**Comment by amarbit** [comment]
Hi 
Locally I clone this repo and build my demo card is working as expected. When trying to commit my changes remote repository not allowing. Could you help me to commit my changes? or steps in details.

**Comment by johnnychen94** [comment]
Have you fork that repo?

**Comment by amarbit** [comment]
Hi
I cloned the repo in the local directory and then added my demo and locally
built.
[image: image.png]
Also, I switched to the source branch and tried to push my changes but
getting permission issues.
remote: Permission to JuliaImages/juliaimages.github.io.git denied to
amarbit.
fatal: unable to access '
https://github.com/JuliaImages/juliaimages.github.io/': The requested URL
returned error: 403


Regards
Amar kumar

**Comment by johnnychen94** [comment]
Yeah, I think you need to fork that repo first, then push your commit to your own fork, and then open a pull request from your fork to the original repo.

The permission issue is that you don't yet have write permission to the original repo. Most of the contributors don't, and we're doing this via a pull request(PR) manner.

**Comment by amarbit** [comment]
Thanks for the quick response. I raised the PR as you gave steps.

Regards
Amar kumar
