### ISSUE TITLE
Make OffsetArray usable in edge.jl

### ISSUE THREAD

**Issue by vis-florum** [JuliaImages/Images.jl#926]
Currently, when trying to detect edges with canny() for an image in an OffsetArray, error occurs because of an indexing issue in thin_edges_nonmaxsup_core!().
In specific, the problem seems to be from line 301 onwards because:
[...]
(height,width) = size(img)

    for x = 1:width, y = 1:height
        (c = img[y,x]) == 0 && continue  # For thresholded images
[...]
the image is addressed by x and y which depend on the absolute size of the array.
Instead, one could maybe change it to use CartesianIndices of the image instead.

I would be great to be able to use OffsetArray and the CartesianIndices because both are extensively used throughout the Images.jl package.

Thanks for your great work!

**Comment by zygmuntszpak** [comment]
Thank you for reporting this issue. I am in the process of finalising a Canny edge detection routine here (https://github.com/JuliaImages/ImageEdgeDetection.jl/pull/9) and can confirm that it works on OffsetArrays. I mainly just need to verify and document the API before I can register that package.

**Comment by knuesel** [comment]
@zygmuntszpak will this replace the implementation in Images.jl?

**Comment by zygmuntszpak** [comment]
@knuesel Yes, the intention is for the `Images.jl` package to use `ImageEdgeDetection.jl` and to depracate the current `canny` function etc.  How to best manage this transition is still something we need to figure out.
