### ISSUE TITLE
alternatives to `@test_approx_eq_sigma_eps` macro

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/Images.jl#942]
I noticed this while trying out test_approx_eq_sigma_eps() which is there in code and works just fine when used directly but is not exported I think so can't be used by public...
https://github.com/JuliaImages/Images.jl/blob/810480a19c879bb3fa1598b6e7ac7801ecdcf4e3/src/algorithms.jl#L282
- are there methods available in Images that does image comparision other than ofcourse seeing images side by side?Visually or mathematical ways?
- https://juliaimages.org/stable/democards/examples/spatial_transformation/image_diffview/#Image-Difference-View has some tricks but those are tricks 😅 
- Relevant issues in past:
  - https://github.com/JuliaImages/Images.jl/issues/364
  - https://github.com/JuliaImages/Images.jl/pull/390

@timholy implemented simple difference testing in https://github.com/JuliaImages/Images.jl/pull/367 but there haven't been much developement on that section I believe after that

**Comment by johnnychen94** [comment]
`@test_approx_eq_sigma_eps` was added for test purposes and is now moved to VisualRegressionTests.jl. Most codes in `src/algorithms.jl` will be deprecated or moved to appropriate places as we're trying to making Images.jl an umbrella package, i.e., by moving implementations to ImageEdgeDetection, ImageBinarization, etc.

- For test purposes, we're using ReferenceTests.jl as an alternative to `@test_approx_eq_sigma_eps`.
- For visual comparison, `mosaicview` (will soon be `mosiac` https://github.com/JuliaArrays/MosaicViews.jl/pull/28#issuecomment-774655243) suits my personal requirements.
-  For numerical comparison, we use ImageDistances.jl and ImageQualityIndexes.jl.

There's definitely room for improvement but I don't have any concrete ideas so far.

**Comment by johnnychen94** [comment]
closing as there're no further replies to this question.
