### ISSUE TITLE
choosing the size of a displayed image

### ISSUE THREAD

**Issue by luigiannelli** [JuliaImages/Images.jl#951]
from the doc:
```ImageShow is used to support image display in Juno and IJulia. This happens automatically if you are using Images```
I am using IJulia. How can I chose the size of the displayed image?
I load the image with `img = load("path/to/img.png")` and i would like the displayed image on my jupyter notebook to be of a fixed size, independent of the size of the real image "path/to/img.png".
Is this possible?

**Comment by johnnychen94** [comment]
As far as I've understood, no. The image is compressed by PNG and then encoded by Base64. The only two places that you can insert such control are 1) a manual `imresize` before showing the image, and 2) set a property in Jupyter that enables this, which I don't know if there is.
