### ISSUE TITLE
Drop ImageCore 0.8, ColorVectorSpace 0.8, and Colors 0.9 compatibility

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#972]
One of the largest changes in ImageCore v0.9 is that it loads ColorVectorSpaces v0.9 by default and it's only compatible with CVS v0.9. And CVS v0.9 is quite distinctive a release that it decides to no longer support `abs(::RGB)` and other similar operations because of the ambiguities (https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/131).

It turns out quite difficult to maintain both the pre-0.9 versions and the post-0.9 versions from my own personal experiences, so I'd like to see this as a chance to revisit and clean out all our legacy codes and build JuliaImages on top of ImageCore 0.9, CSV v0.9, and Colors v0.10.

We've paid a lot of effort maintaining the Julia 1.0 compatibility because it is an LTS release, and because Pkg in Julia 1.0 isn't smart enough to do version resolving. With Julia 1.6.2 as the next LTS release, I'd like to set our acceptable Julia compatibility lower-bound to no-higher-than Julia 1.6. That said, we'll have some mature packages compatible with Julia 1.0 (and even Julia 0.7), and we'll have some new packages that are only compatible with Julia 1.3 or Julia 1.6. But we won't have packages that are only compatible with Julia at least 1.7; if there are such packages, efforts should be paid to support Julia 1.6 before it becomes a part of Images.jl

Packages that 1) should cut-off direct dependency on CVS or 2) has compatibility maintenance issues on CVS:

- [x] https://github.com/JuliaImages/Images.jl/pull/971
- [x] https://github.com/JuliaImages/ImageAxes.jl/pull/60
- [x] ImageBinarization.jl
- [ ] ImageEdgeDetection.jl
- [x] https://github.com/JuliaImages/ImageSegmentation.jl/issues/71
- [x] ImageTransformations.jl
- [x] https://github.com/JuliaImages/ImageView.jl/issues/252

Packages outside JuliaImages that I know:

- [ ] Augmentor.jl
- [ ] MLDatasets.jl
- [ ] PGFPlots.jl depends on Images 😱

**Comment by timholy** [comment]
All but the ImageEdgeDetection is done. I'll close this and we can continue to work on that.
