### ISSUE TITLE
rewrite the `Images` docstring

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#982]
The current docstring is useless so we need a rewrite of it.

https://github.com/JuliaImages/Images.jl/blob/9796acc8bf1d56d9574c555656fdba362f84a988/src/Images.jl#L206-L236

My idea is to remove the verbose list and only give a general introduction. For instance, modify from https://juliaimages.org/stable/pkgs/.

**Comment by timholy** [comment]
I think that's reasonable. Another option is to auto-generate it from https://github.com/JuliaDocs/ModuleDocstrings.jl, but that may not be very satisfying either, and I doubt that package supports `@reexport` properly (yet) and until then would be very incomplete.
